### ISSUE TITLE
BatchProcessor Stops Execution

### ISSUE THREAD

**Issue by PaulWeakley** [influxdata/influxdb-java#118]
The BatchProcessor's thread execution fails after some period of time and the data being transferred to the influx database falls back onto the hard limit. 

My guess is that the connection to the InfluxDB server becomes unstable or a fault occurs and the write() method throws an exception. If this occurs then the executor service will not recover and the write() method will never be called again. Suggest putting a try/catch around the write method contents.

Situation: Pushing 160 samples to influx every 30 seconds. 10 second flush interval with a 2000 entry limit. Then, randomly when requesting data from InfluxDB observing a 6 min gap in data despite the 10 second flush interval. Eventually the data is available (because the server flushed the data to the database) and the gap window of 6 minutes starts again.

**Comment by PaulWeakley** [comment]
Thank you for taking a look. I had some ideas on a clean solution so I created a pull request for you to take a look.

**Comment by majst01** [comment]
Is there anything to do here, otherwise i will close this issue.

**Comment by jiafu1115** [comment]
@majst01  you can close this issue just now, I double check the issue had been fixed by @PaulWeakley .
