### ISSUE TITLE
Retention policy not working

### ISSUE THREAD

**Issue by akk3ra** [influxdata/influxdb-java#125]
I am using infludb-java version 2.0-SNAPSHOT and I am facing issues with the retention policy. 
I created the retention policies through the UI, for eg: one_year, one_month etc..
When I try writing to the DB I see two issues
1) The data does not get written to the DB (select \* from <measurement>) returns ZERO records and my client does not throw any error or any exception.
2) When I set the retention policy to a different one it suddenly starts working BUT it creates a new problem, my queries start to fail.

**Comment by majst01** [comment]
Hi @letitcrash 

please try to use 2.0 (without SNAPSHOT) which is available from maven-central and try to reproduce.

Greetings

**Comment by caoli5288** [comment]
:+1: @majst01

**Comment by letitcrash** [comment]
@majst01 . I used the 2.0 version and I still see this issue. The data only gets written if the new policy I created is the default RP, otherwise the measurement gets created by the data does not get inserted.

**Comment by letitcrash** [comment]
@majst01 . I upgraded to the latest influxdb as well, 0.9.5.1 and the issue still persists. 
Can you please help us fixing the issue ? 
https://github.com/influxdb/influxdb/issues/4953

**Comment by majst01** [comment]
Can you enable Debugging of the data written to influxdb with:

influxdb.setLogLevel(LogLevel.FULL)

To see what is written to influxdb. Then try to reproduce the behavior with a
curl and the same data and check if the problem still persist. If yes this is a influxdb problem.
Otherwise it might be that we send the data in a wrong format to influxdb.

**Comment by letitcrash** [comment]
@majst01 : Ok. I will try that and drop back but just to let you know, when I change my retention policy to another one (one_hour) which is the default. It works. I already mentioned this in https://github.com/influxdb/influxdb/issues/4953 . Will enable logging and let you know how it went.

**Comment by letitcrash** [comment]
@majst01. I tried CURL using -XPOST and it did the same thing which my java client did and I do not see any records returned after I made an insertion through CURL. I saw the measurement getting created with the CURL command as the measurement did not exist before I hit CURL. The interesting thing to note here is that the CURL command was able to successfully insert if I changed the RP to "one_hour"  through the URL using "&rp=one_hour"
The below is the response for the HTTP request:---

HTTP/1.1 204 No Content
Request-Id: XXXXXXXXXXXXXXXXX
X-Influxdb-Version: 0.9.5.1
Date: Mon, 07 Dec 2015 20:41:28 GMT

Therefore is it a influxDB issue ?

Because, no matter what my client is (HTTP or influxdb-java client), it works if I set RP as one_hour (which is default) and fails when I do a insertion using java client or HTTP XPOST, if RP is set to one_year. 

PS: Both the RPs (one_year and one_hour) do exist in my DB.

**Comment by mnuessler** [comment]
I tried to reproduce your problem, but was not able to do so. For it seems to work as expected. Here is what I did:

* Create two retention policies
```
> show retention policies on foo;
name		duration	replicaN	default
default		0		1		false
one_hour	1h0m0s		1		true
one_year	8760h0m0s	1		false
```

* Insert a point using the `one_year` retention policy which is not the default.
```java
InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
BatchPoints batchPoints = BatchPoints.database("foo").consistency(InfluxDB.ConsistencyLevel.ALL).retentionPolicy("one_year").build();
batchPoints.point(Point.measurement("measurement1").field("bar", 1L).build());
influxDB.write(batchPoints);
```

* Check if data has been inserted using the `influx` client
```
> select * from one_year.measurement1;
name: measurement1
------------------
time			bar
1449537763944000000	1
```

Is that the same that you were trying to do? I tested with InfluxDB 0.9.5.1 and the latest influxdb-java client from master.

**Comment by mnuessler** [comment]
It also works for me when using the influxdb-java client to query:
```java
InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
influxDB.setLogLevel(InfluxDB.LogLevel.FULL);
Query query = new Query("select * from one_year.measurement1", "foo");
QueryResult result = influxDB.query(query);
System.out.println(result);
```
Output:
```
---> HTTP GET http://localhost:8086/query?u=root&p=root&db=foo&q=select+*+from+one_year.measurement1
---> END HTTP (no body)
<--- HTTP 200 http://localhost:8086/query?u=root&p=root&db=foo&q=select+*+from+one_year.measurement1 (181ms)
Content-Type: application/json
Request-Id: d045a5c9-9d4f-11e5-8035-000000000000
X-Influxdb-Version: 0.9.5.1
Date: Tue, 08 Dec 2015 02:03:02 GMT
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1449540182685
OkHttp-Received-Millis: 1449540182691

{"results":[{"series":[{"name":"measurement1","columns":["time","bar"],"values":[["2015-12-08T01:22:43.944Z",1]]}]}]}
<--- END HTTP (117-byte body)
QueryResult [results=[Result [series=[Series [name=measurement1, tags=null, columns=[time, bar], values=[[2015-12-08T01:22:43.944Z, 1.0]]]], error=null]], error=null]
```

**Comment by majst01** [comment]
So this seems to be a particular problem with the RP definition, @letitcrash can you show how you created your RPs ?

**Comment by letitcrash** [comment]
@majst01 : 

I created the RPs through the influxdb UI which is exposed on the port 8083 by default. On the Query Templates tab there is option to create RPs. What am I missing here.

name	duration	replicaN	default
default	"0"	1	false
one_hour	"1h0m0s"	1	true
one_day	"24h0m0s"	1	false
one_month	"720h0m0s"	1	false
one_year	"8760h0m0s"	1	false

**Comment by cyrilmhansen** [comment]
Hi akkera83, did you find a bypass for your problem ? 

I use InfluxDB 0.13 (windows build on windows dev box) and influxdb-java 2.2 from maven central, and have the exact same behavior : If I write to a non default retention policy, the measurement is created empty. There is no error in the server output (204 http empty response).

**Comment by patrickvallet** [comment]
Hi cyrilmhansen ,
Same behaviour for me with InfluxDB 0.13. Have you found a workaround or other solution?
Regards

**Comment by majst01** [comment]
This is a influxdb implementation behaviour, no way to get fixed from this library.
