### ISSUE TITLE
Allow unparsed query results too.

### ISSUE THREAD

**Issue by aadrian** [influxdata/influxdb-java#127]
Please allow unparsed (JSON) query results too, especially for the cases where the data needs to be sent in JSON form to other systems.

So it would be nice if the String(JSON) to Object conversion would be done only when it's needed, but the error handling is still needed.

**Comment by majst01** [comment]
Same as for raw writes, raw queries.

If you think this is a useful feature, please prepare a pull request, im happy to review and merge.

**Comment by majst01** [comment]
nothing new here, so closing it, reopen it at any time.
