### ISSUE TITLE
[Request] Enable point batching by default

### ISSUE THREAD

**Issue by jackzampolin** [influxdata/influxdb-java#138]
InfluxDB is significantly more performant when points are written in batches. Making the default behavior of the client point batching should help increase performance for people unfamiliar with InfluxDB.

@majst01, Please consider making the following setting enabled by default:

```
# Enabled by default
influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);

# Disable batching
influxDB.disableBatching();

# Change batching config
influxDB.configureBatching(10000, 200, TimeUnit.MILLISECONDS);
```

**Comment by majst01** [comment]
We will leave the decision to the developer, as he understands exactly how to act on the data.

**Comment by jackzampolin** [comment]
Writing many small requests is a common issue that new users run into. Enabling batching by default will eliminate these support requests. Please reconsider changing the defaults.

**Comment by majst01** [comment]
And what should be sensible defaults for amount, time, and so forth

**Comment by jackzampolin** [comment]
I think the following would be sensible defaults.
```
pointsPerBatch: 2000
batchTime: 1s
```

**Comment by majst01** [comment]
Ok, but if someone wants different settings, what would be the workflow ? stop the already running batchprocessor and create a new one with the desired settings.
Im still against this idea

**Comment by jiafu1115** [comment]
@jackzampolin  agree with @majst01,  every developer should set their batch parameter. if provide batch used hard code one, it may cause issue not found. So I also think this issue should be closed. WDTY?

**Comment by majst01** [comment]
As i already said, this is the wrong idea.
