### ISSUE TITLE
Number of written items in PerformanceTests#maxWritePointsPerformance

### ISSUE THREAD

**Issue by hkrizek** [influxdata/influxdb-java#139]
I try to do some performance tests with influxdb-java 2.1 and influxdb-0.9.6.1.
In influxdb-java repository there is PerformanceTests class with maxWritePointsPerformance method. I tried to run this with some slight changes to find out how fast points are written and if number of written items are really written to db.

``` java
@Test(enabled = true)
    public void maxWritePointsPerformance() {
        String dbName = "d";
        this.influxDB.createDatabase(dbName);
        this.influxDB.enableBatch(1000, 60, TimeUnit.SECONDS);
        int count = 100000;
        Stopwatch watch = Stopwatch.createStarted();
        for (int i = 0; i < count; i++) {
            Point point = Point.measurement("s").field("v", 1).build();
            this.influxDB.write(dbName, "default", point);
        }
        System.out.println(count + " points:" + watch);
        Query query = new Query("select count(v) FROM s", dbName);
        System.out.println(this.influxDB.query(query));
        this.influxDB.deleteDatabase(dbName);
    }
```

The result is that not all items are written to db:

```
Running org.influxdb.PerformanceTests
100000 points:5,553 s
QueryResult [results=[Result [series=[Series [name=s, tags=null, columns=[time, count], values=[[1970-01-01T00:00:00Z, 162.0]]]], error=null
]], error=null]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.491 sec
```

This is probably caused by Point.build() function, where same timestamp is used for several items.

Does anybody have any serious performance tests and results with influxdb-java-2.1?

**Comment by dltc** [comment]
I also encountered the same problem, I wrote a one million Point, but can only find out more than 80,000.

**Comment by majst01** [comment]
Please retest with the most recent combination of influxdb and influxdb-java, if problem still persist reopen this issue.
