### ISSUE TITLE
Use System.currentTimeMillis() for wall-clock

### ISSUE THREAD

**Issue by henrikno** [influxdata/influxdb-java#140]
I saw that the code uses System.nanoTime() when submitting the timestamp to influx. According to the JavaDoc:
`This method can only be used to measure elapsed time and is not related to any other notion of system or wall-clock time`

You should be using System.currentTimeMillis() when you need the "wall-clock" time.

**Comment by haninaguib** [comment]
Has someone looked into this. I seems to me like a major bug.
Point.formatedTime (line 348) which is used by Point.lineProtocol()
