### ISSUE TITLE
Batch scheduler stops working after connection issue

### ISSUE THREAD

**Issue by mmatloka** [influxdata/influxdb-java#143]
Hi,
We have observed the following issue - when using the batch processor, when the connection to db fails, then exception is thrown during https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/BatchProcessor.java#L166 . According to https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/BatchProcessor.java#L137 `scheduleAtFixedRate` java doc
`If any execution of the task
     * encounters an exception, subsequent executions are suppressed.`
So after connection exception next execution is surpresed and batch will be only send when the max size is reached during `put`.

**Comment by andrewdodd** [comment]
Same as issue #118
