### ISSUE TITLE
support UDP Protocol

### ISSUE THREAD

**Issue by gunlee01** [influxdata/influxdb-java#157]
I hope it to support line protocol on UDP for some specific light-weight processing.

**Comment by bentatham** [comment]
@majst01 - would there be an appetite to add this, if I provide a pull request?  

I was thinking of a new subclass of ``InfluxDB`` that throws ``UnsupportedOperationException`` for those methods that require a response.  Alternative approach: extract the ``write`` methods to a super-interface called ``PointsInfluxDB`` or ``WriteOnlyInfluxDB`` or something like that.    Thoughts?

**Comment by mhiller** [comment]
+1 to this. . I would rather not role my own if i dont have to.

**Comment by jiafu1115** [comment]
refer to #226  I am focus on it. Welcome any advices.
