### ISSUE TITLE
xception in thread "main" java.lang.NoClassDefFoundError: retrofit/client/Client

### ISSUE THREAD

**Issue by libra34567** [influxdata/influxdb-java#158]
what does that mean and how i can fix it?

It happened on the line 
InfluxDB influxDB= InfluxDBFactory.connect("http://localhost:8086", "root", "root");

**Comment by caoli5288** [comment]
You should add "retrofit" to you class path.

**Comment by libra34567** [comment]
I download the retrofit jar but its 2nd version and it still doesn't contain retrofit/client?

**Comment by majst01** [comment]
Dont download it manuelly, specify the maven dependency and all is done automatically with the right versions for all dependencies.

**Comment by andrewdodd** [comment]
Are you using [maven](https://maven.apache.org/) for your build / dependency management?
