### ISSUE TITLE
Inserts buffer in Influxdb but http response 204

### ISSUE THREAD

**Issue by bubbajones69** [influxdata/influxdb-java#165]
When trying to load data from a file, getting unusual results.

I have a cvs file with 70 metrics.  I have used the code to process the file two ways for performance testing and schema design.

One model is one insert with one metric and 70 fields.  This processes great - using the "single point" batch model.  38,000 records in under 10 seconds....

The other model is creating a measurement for each column in the file, with one field called value.  This one doesn't run so well...

Program execution completes in about 22 seconds, influx log says it inserted the data, however querying the data shows the inserts "stalled" after about 6331 inserts.  After this the inserts seem to keep happening but VERY slow, maybe 1 - 2 per minute.  Very strange...  

I tested my logic and have dumped my inserts to file and used curl, in both cases they ran perfectly, 3 seconds for the "single measurement" and 10 seconds for the "multi measurement".

Seems for some reason the http interactions are causing a strange behavior on the influxdb side but I don't know where to look for the problem.

I have tried without batching and it works, but VERY SLOW....  I also tried changing the code to take advantage of "batchPoints" - this is a little better, but I also noticed that "batchEnabled is false" - if I turn on batching , this is show the same results.

Here is sample code that will cause issue:
`import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.time.Duration;
import java.time.Instant;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import org.influxdb.InfluxDB;
import org.influxdb.InfluxDBFactory;
import org.influxdb.dto.BatchPoints;
import org.influxdb.dto.Point;

public class InsertSample {

    public static void main(String[] args) throws Exception {

        int numberOfLines = 0;
        try {
            Instant start = Instant.now();

            int numberOfSymbols = 70;
                        
            InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
            String dbName = "mydb2";
            influxDB.createDatabase(dbName);

            // Flush every 2000 Points, at least every 100ms
            influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);

            long timeStamp = 1461168000000L;
            double data = 1;
            for (numberOfLines = 0; numberOfLines < 38000; numberOfLines++) {
                for (int i = 1; i < numberOfSymbols; i++) {

                    Point point = Point.measurement("m"+i)
                            .time(timeStamp, TimeUnit.MILLISECONDS)
                            .tag("source", "second-70")
                            .addField("value", data + i)
                            .build();
                    influxDB.write(dbName, "default", point);

                }
                timeStamp = timeStamp + 30000;
                data = data + 10;
            }

            Instant end = Instant.now();
            System.out.println("Insert time: " + Duration.between(start, end));

            System.out.println("Import complete.  Records Processed:" + numberOfLines);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
`

**Comment by bubbajones69** [comment]
InfluxDB issue - when time between points is 30s something goes crazy within influxdb

**Comment by andrewdodd** [comment]
@bubbajones69 amI to understand that you solved this issue?

**Comment by bubbajones69** [comment]
I don't believe related to influxdb-java.  Using a default influxdb config
if you supply timestamps that are 3000 ms apart with precision=ms influxdb
write performance gets stuck and proceeds very slowly.

The java sample reproduces as well as curl with precision=ms
