### ISSUE TITLE
Is accessing Point.Builder concurrently thread safe ?

### ISSUE THREAD

**Issue by Rajind** [influxdata/influxdb-java#170]
Basically I want to do the following. I create a point builder object like this.
Point.Builder pointBuilder = Point.measurement("measurement");

Then pointBuilder.addField(), pointBuilder.addTag() will be called in multiple threads. 
I saw that in the influxdb-java source TreeMap is used which is not thread safe according to my knowledge. 

I know that TreeMap is used since the ordering is required for better performance. So can I used ConcurrentSkipListMap<>() instead ? And do we need to order fields as well ?

**Comment by Rajind** [comment]
`import org.influxdb.dto.Point;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public class ThreadTest {
    public static Point.Builder pb;
    public static int THREADS =  1000;
    public static long averageTime = 0;

    public static void main(String args[]) throws InterruptedException {
        for (int i = 0; i < 1; i++) {
            pb = Point.measurement("m1");

            long time = System.nanoTime();
            ExecutorService service = Executors.newFixedThreadPool(THREADS);

            for (int j = 0; j < THREADS; j++) {
                final int finalJ = j;
                service.execute(new Runnable() {
                    public void run() {
                        int num = (int) Math.ceil(Math.random() * 100);
                        try {
                            Thread.sleep(THREADS - finalJ);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                        long threadId = Thread.currentThread().getId();
                        //System.out.println("Thread id: "+threadId);
                        pb.tag("tag"+threadId, "hello");
                        pb.addField("field"+threadId, threadId);
                }});
            }

            // Make sure the executor accept no new threads.
            service.shutdown();
            service.awaitTermination(Long.MAX_VALUE, TimeUnit.DAYS);
            long timeUsed = (System.nanoTime() - time) / 1000000L;
            averageTime += timeUsed;
            System.out.println("All threads are completed in "
                    + timeUsed + " ms");
        }
        System.out.println("The average time is " + averageTime / 10 + " ms");
    }
}
`

`Exception in thread "pool-1-thread-569" java.lang.NullPointerException
	at java.util.TreeMap.rotateRight(TreeMap.java:2079)
	at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2111)
	at java.util.TreeMap.put(TreeMap.java:574)
	at org.influxdb.dto.Point$Builder.tag(Point.java:81)
	at ThreadTest$1.run(ThreadTest.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by majst01** [comment]
If you can show you implementation suggestion how to solve this problem we probable will merge it.

Out of curiosity, why do you want to write your points in multiple threads ?

**Comment by Rajind** [comment]
It's for the metrics engine in my program. Data for a single point (different statistics) is collected in multiple threads and written. I used ConcurrentSkipListMap for tag Map and ConcurrentHashMap for field Map in point class. Seems to be working for me.

```
private final Map<String, String> tags = new ConcurrentSkipListMap<>(Ordering.natural());
private Long time;
private TimeUnit precision = TimeUnit.NANOSECONDS;
private final Map<String, Object> fields = new ConcurrentHashMap<>(); 
```

**Comment by andrewdodd** [comment]
Something like:
```
Object lockOBject = new Object();
...
for (...) { 
...
    synchronized(lockObject) {
        pb.tag("tag"+threadId, "hello");
        pb.addField("field"+threadId, threadId);
    }
...
}
```

might be enough?
