### ISSUE TITLE
Flush points in batch

### ISSUE THREAD

**Issue by santinomazzocchi** [influxdata/influxdb-java#172]
Hi all,
I'm using influxdb-java 2.2 and I don't know how to "flush" points written in batch before exiting the process.

For example if InfluxDB has 10 batch points
`influxDB.enableBatch(10, 100, TimeUnit.MILLISECONDS);`
and I write only 2 points, if the process exits I lose 8 point.

What can I do?
Thank you

**Comment by majst01** [comment]
influxDB.disableBatch
