### ISSUE TITLE
Add check if database exists

### ISSUE THREAD

**Issue by henryx** [influxdata/influxdb-java#173]
Current implementation of `InfluxDB` interface doesn't have a check if database exists. Is a good idea to implement an `isDatabaseExists()` method for reporting this information

**Comment by aurrelhebert** [comment]
+1

**Comment by majst01** [comment]
We are open for contribution, so if you need this  functionality you are welcome to raise a pull request with this missing feature.

**Comment by majst01** [comment]
Nothing happened, so closing this. Feel free to reopen it.

**Comment by joshsh** [comment]
As an InfluxDB newbie, I was surprised not to find something like isDatabaseExists().  I came looking for such a feature and landed on this page.
