### ISSUE TITLE
4000+ concurrent objects writing to influxDB using influxdb-java v2.2 slowing down insertion speed.

### ISSUE THREAD

**Issue by akk3ra** [influxdata/influxdb-java#175]
I have a use case where multiple concurrent objects (say 1000) are writing to influxDB. I am unable to scale this as writes to influx are slowing down if I increase the object count to, say **4000+** What is the number of connections of influx should be created using **InfluxDBFactory.connect()** ??? Should it be **1** connection per object **OR** **1** connection shared by all 4000+objects ?? I have tried both ways but none improves the rate at which 'writes' happen to influxDB ?? 
I have also enabled the batch feature using **influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS)**. Do I need to tune this ratio of 2000 and 100 ?? Tried doing that as well but in vain.

InfluxDB claims to do millions of insertions per minute. How do I achieve that speed using this influxdb-java client ?? I am currently using influxdb-java client version **2.2**. Help needed urgently.

**Comment by majst01** [comment]
Please try with latest version and reopen if still persist.
