### ISSUE TITLE
Dependenies

### ISSUE THREAD

**Issue by trevorndodds** [influxdata/influxdb-java#176]
To get a functional influxdb-java client I had to download the below dependencies. Are these all really necessary? I was thinking the client would be as self contained as possible.

gson-2.2.2.jar
guava-19.0.jar
okhttp-2.3.0.jar
okio-1.8.0.jar
retrofit-1.9.0.jar

Thanks

**Comment by majst01** [comment]
You are right, but this is a maven project, so you do not need to download them by hand, the dependencies get downloaded during the build process
```
mvn clean install
```
will do the trick.

Implementing such a library without any external dependencies is of course possible but would mean way more effort and lines of code and therefore more bugs.
