### ISSUE TITLE
Warnings in InfluxDB responses for non read only queries

### ISSUE THREAD

**Issue by cyrilmhansen** [influxdata/influxdb-java#179]
Using Wireshark to understand the InfluxDB protocol, I see this  for many of my queries :

"deprecated use of 'SELECT xxxx INTO xxxx  FROM xxxWHERE xxxx GROUP BY time(1h), xx,xxx' in a read only context, please use a POST request instead.

It seems that the 1.0 protocol will not allow the use of GET method for update type queries. Will influxdb-java support update type queries like create database the time of 1.0 release ?

Regards, CMH.

**Comment by majst01** [comment]
This was fixed with the transition to retrofit2/okhttp3
