### ISSUE TITLE
Compress large batch points write requests using gzip

### ISSUE THREAD

**Issue by cyrilmhansen** [influxdata/influxdb-java#180]
I am currently prototyping the migration from a RRD4J System to InfluxDB. I have archive of data in CSV format, and I am writing the import tool to InfluxDB using influxdb-java.

I used wireshark to look at my network traffic, and it is quite large. I checked with curl and I  see that InfluxDB 0.13 support gzip compression of POST request body. 

As the server supports it, would it be possible to provide an option to compress large write requests with influxdb-java ?

If found this message which may be technically related : https://github.com/square/okhttp/wiki/Interceptors#rewriting-requests

Regards,

Cyril H

**Comment by madhukard** [comment]
+1

**Comment by viragkothari** [comment]
+1

**Comment by har-ki** [comment]
+1

**Comment by majst01** [comment]
Hi,

once #203 is merged this would be an option. If someone wants to show how that would look like, i happily accept pull requests.

**Comment by majst01** [comment]
anyone with a working PR ?

**Comment by jiafu1115** [comment]
@majst01 I can resolve this issue after I complete UDP's PRs.

**Comment by jiafu1115** [comment]
@cyrilmhansen @madhukard @viragkothari @har-ki  @majst01  support it on #241, let's waiting for @majst01 's review and feedback.
