### ISSUE TITLE
Add BatchPoint Builder addField method

### ISSUE THREAD

**Issue by cyrilmhansen** [influxdata/influxdb-java#183]
The Point Builder class provides addField and tag methods, but the BatchPoint Builder provides only the tag method. Would it be possible to support defining fields at the BatchPoint Builder level, this would be very convenient when some field is constant accross the whole data batch.

As tags are more constly in term of performance, using BatchPoint Builder API users will have the tendency to use only tags, which may make InfluxDB write performance and memory use look bad.

**Comment by majst01** [comment]
No update here, closing
