### ISSUE TITLE
Conversion of time after query to influxdb

### ISSUE THREAD

**Issue by andremann** [influxdata/influxdb-java#184]
Hi everybody!
I've been experimenting with influx for a while and I've just encounter a problem with time conversion of influx points. Hope you can help me through.

I have a business class 

```
public class Observation implements Serializable {
    private long timestamp;
    /*...*/
    public Observation() {
        this.setTimestamp(System.nanoTime());
    }
}
```

When I create a new point into influx, I convert my pojo as

```
Point point = Point.measurement(observation.getMetric()).time(observation.getTimestamp(), TimeUnit.NANOSECONDS)...
```

When I get the points back with `influxDB.query(query).getResults();`
I found timestamps like `2016-06-20T11:59:18.568343Z` which I have to convert back into my pojo somehow.
So far I have been using `SimpleDateFormat` as in

```
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse("2016-06-20T11:59:18.568343Z") = {Date@7771} "Mon Jun 20 12:08:46 BST 2016"
 fastTime = 1466420926343
 cdate = {Gregorian$Date@7773} "2016-06-20T12:08:46.343+0100"
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse("2016-06-20T11:59:37.136244Z") = {Date@7679} "Mon Jun 20 12:01:53 BST 2016"
 fastTime = 1466420513244
 cdate = {Gregorian$Date@7775} "2016-06-20T12:01:53.244+0100"
new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").parse("2016-06-20T11:59:49.955436Z") = {Date@7683} "Mon Jun 20 12:15:44 BST 2016"
 fastTime = 1466421344436
 cdate = {Gregorian$Date@7777} "2016-06-20T12:15:44.436+0100"
```

but it pretty much doesn't work right. (`SimpleDateFormat` supports up to milliseconds)
The gregorian dates in fact are not matching and the fastTime fields do not follow the order of the original timestamps

```
convertion(2016-06-20T11:59:18.568343Z) = ...0926343
convertion(2016-06-20T11:59:37.136244Z) = ...0513244
convertion(2016-06-20T11:59:49.955436Z) = ...1344436
```

What should I do to get my `long` initialised properly?

I also tried to query influxdb with `influxDB.query(query, TimeUnit.NANOSECONDS)`
at this point the returned timestamps are doubles and again i don't know exactly how to handle them.

**Comment by andremann** [comment]
It seems I solved (not 100% sure) by querying for `TimeUnit.MILLISECONDS`
and doing
`observation.setTimestamp(new Double((Double) <influxTime>).longValue());`

**Comment by majst01** [comment]
there is a new method for that in TimeUtils.java
