### ISSUE TITLE
Question: Why influxdb-java lost some ponits and response was 204?

### ISSUE THREAD

**Issue by visionarywind** [influxdata/influxdb-java#185]
I used influxdb-java to write some monitor data. And I found it would lost data.
Here is my codes:

    private void batchWrite(List<Point> points) {
        BatchPoints batches = BatchPoints.database(dbName).tag("async", "true")
                .retentionPolicy("default").consistency(InfluxDB.ConsistencyLevel.ALL)
                .build();
        for (Point point : points) {
            batches.point(point);
        }
        synchronized (dbLock) {
            influxDB.write(batches);
        }
    }

batchWrite method would be called per 15 seconds

here is a reponse:

---> HTTP POST http://XX/write?u=fy&p=fy&db=fydb&rp=default&precision=n&consistency=all
Content-Type: text/plain
Content-Length: 1466
algoQueryTest area10to15=29.0,area15to25=52.0,area1to2=7.0,area25to40=59.0,area2to3=8.0,area3to5=19.0,area40to60=56.0,area5to7=13.0,area60to100=89.0,area7to10=9.0,average=82.3622,biggerThan100=179.0,count=530.0,ip="10.210.228.89",lessThan1=10.0,max=297.2222,min=0.0311,type="0" 1467881171285000000
algoQueryTest area10to15=22.0,area15to25=36.0,area1to2=11.0,area25to40=49.0,area2to3=7.0,area3to5=20.0,area40to60=57.0,area5to7=9.0,area60to100=103.0,area7to10=26.0,average=79.387,biggerThan100=156.0,count=502.0,ip="10.210.228.89",lessThan1=6.0,max=283.2459,min=0.4982,type="1" 1467881171286000000
algoQueryTest area10to15=20.0,area15to25=40.0,area1to2=12.0,area25to40=66.0,area2to3=8.0,area3to5=14.0,area40to60=62.0,area5to7=9.0,area60to100=95.0,area7to10=15.0,average=77.1672,biggerThan100=148.0,count=492.0,ip="10.210.228.89",lessThan1=3.0,max=283.4049,min=0.0028,type="2" 1467881171286000000
algoQueryTest area10to15=28.0,area15to25=30.0,area1to2=7.0,area25to40=44.0,area2to3=10.0,area3to5=8.0,area40to60=54.0,area5to7=17.0,area60to100=90.0,area7to10=21.0,average=78.5162,biggerThan100=150.0,count=460.0,ip="10.210.228.89",lessThan1=1.0,max=289.0548,min=0.9368,type="3" 1467881171287000000
algoQueryTest area10to15=0.0,area15to25=0.0,area1to2=0.0,area25to40=0.0,area2to3=0.0,area3to5=0.0,area40to60=0.0,area5to7=0.0,area60to100=0.0,area7to10=0.0,average=0.0,biggerThan100=0.0,count=0.0,ip="10.210.228.89",lessThan1=0.0,max=0.0,min=0.0,type="4" 1467881171287000000

---> END HTTP (1466-byte body)
<--- HTTP 204 http://XX/write?u=fy&p=fy&db=fydb&rp=default&precision=n&consistency=all (4ms)
Content-Encoding: gzip
Request-Id: 415693d3-441f-11e6-9071-000000000000
X-Influxdb-Version: 0.9.4.1
Date: Thu, 07 Jul 2016 08:46:11 GMT
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1467881171292
OkHttp-Received-Millis: 1467881171295

<--- END HTTP (0-byte body)

I opened logging message of REST, but the response was 204.
Thanks for answering.

**Comment by visionarywind** [comment]
Oh, I got it, but why?
here is ...
for (Table.Cell<String, String, MonitorFlap> cell : monitorTable.cellSet()) {
                    Point.Builder builder = Point.measurement(cell.getRowKey())
                            .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS);

                    builder.addField("ip", ip);
                    builder.addField("type", cell.getColumnKey());

                    MonitorFlap val = cell.getValue();
                    List<Field<Double>> feature = val.getFeature();
                    for (Field<Double> field : feature) {
                        builder.addField(field.getName(), field.getValue());
                    }
                    Point point = builder.build();
                    points.add(point);
                }

**Comment by Daniel700** [comment]
you can also enable batch writing this way (see start page of influxdb-java github):
```
influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);
... PointBuilder...
influxDB.write(dbName, "default", point1);
```
Response 204 means that your write was successful to InfluxDB
See the docs here: https://docs.influxdata.com/influxdb/v0.13/guides/writing_data/#http-response-summary

Are you sure that you lose points? 
What are your possible values for your fields? Do they contain string values?

**Comment by visionarywind** [comment]
First of all, thank you.
I am quite sure that I lose some point. And quite frequently... 1 or 2 per 2 minute
In my fields, `type="4"` contains string values.
When I change `type` into tag, it runs well.

So, I got confused. Why does fields with string value work in such a situation?

**Comment by andrewdodd** [comment]
@visionarywind, I feel like maybe this is more of an issue with the usage of the library than a bug in the library.

However, as @Daniel700 kindly pointed out, you received a 204 response, so I think the example you provided did work correctly. Perhaps you can get a grab of a point that didn't succeed?

As for the fields vs tags situation, remember:
 - Fields are meant for your 'data'. They are typed and Influx will throw an error if you write the incorrect type to one.
 - Tags are meant for your 'metadata'. They store all data as Strings.

Although 'type' is not a keyword in InfluxQL, it is one that I would avoid. My opinion.... It is almost always a bad idea to name something 'type' in software, especially in a very generic sense like this. 

Another possibility for what you are seeing it that you have both a field and a tag that share the same name (i.e. a field and a tag called 'type'). See the final dot point [here](https://docs.influxdata.com/influxdb/v0.13/concepts/schema_and_data_layout/#discouraged-schema-design).
