### ISSUE TITLE
Not writing all records in Batch Mode

### ISSUE THREAD

**Issue by jjkirby** [influxdata/influxdb-java#187]
I am using version 2.2 of the client (Java 1.8) going against v0.13 influx.

I have a batch write of about 3600 records and it appears to only write a fraction (approx. 300).  I see no errors in the client

This is outside the SQL Server fetch loop

`InfluxDB influxDB = InfluxDBFactory.connect("http://172.16.21.144:8086", "admin", "admin");
influxDB.enableBatch(3800, 1000, TimeUnit.MILLISECONDS);`

This is inside the loop
`BatchPoints batchPoints = BatchPoints
        .database("power_utilization")
        .retentionPolicy("default")
        .consistency(InfluxDB.ConsistencyLevel.ALL)
        .build();
Point point1 = Point.measurement("power_utilization")
        .time(timestamp, TimeUnit.NANOSECONDS)
        .addField("custid", power.getCustId())
        .addField("powcircid", power.getPowerCircId())
        .addField("panname", power.getPanName())
        .addField("upsname", power.getUpsName())
        .addField("pos", power.getPos())
        .addField("Amp_Hours", power.getAmpHours())
        .addField("Amps", power.getAmps())
        .addField("phase_voltage", power.getPhaseVoltage())
        .addField("kiloWattHours", power.getKiloWattHrs())
        .build();
batchPoints.point(point1);
influxDB.write(batchPoints);`

I am doing BatchPoints/write inside a loop that is fetching data from a SQL Server DB and formatting the data.

When I do a Select count(Amps) from “power_utilization” I get a number like 237.  But I fetched 3600 records from the SQL Server.  Looks like some records didn’t write?

Anybody see anything wrong here?

**Comment by majst01** [comment]
please test with recent version, otherwise will close.

**Comment by jiafu1115** [comment]
@majst01 you can close it, if existed issue @jjkirby  can reopen it
What's more, for his description, we can't make sure if related with server or client.
