### ISSUE TITLE
Measurements with duplicate time value is not inserted

### ISSUE THREAD

**Issue by jvchbabu** [influxdata/influxdb-java#188]
![onerecordinsteadof two records](https://cloud.githubusercontent.com/assets/14213225/17455643/2f570450-5bdc-11e6-9c9f-1c7102e76afd.PNG)
I am using version 2.2 of the client (Java 1.7) going against v0.13 influx. Enabled batch  for single points  with 3 points or 1 minute which occurs earlier.
 But  only two records inserted whose time value  are  unique.  This happening both for batch points as well as single points.

   I tried with  with different time values for the same measurement and observed the records getting inserted. 
The time field has any constraint which will not allow with duplicate time values?

```
           InfluxDB influxDB = InfluxDBFactory.connect("http://xxx.27.xxx.xx:8086", "root", "root");
    String dbName = "aTimeSeries";
    influxDB.createDatabase(dbName);
    influxDB.enableBatch(3, 1, TimeUnit.MINUTES);

    Point point1 = Point.measurement("system")
                        .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                        .addField("idle", 8L)
                        .addField("userid", 8L)
                        .addField("system", 8L)
                        .build();
    long abc=System.currentTimeMillis();
    System.out.println(abc);
    Point point2 = Point.measurement("memory")
                        .time(abc, TimeUnit.MILLISECONDS)
                        .addField("used", 22L)
                        .addField("free", 22L)
                        .build();
     abc=System.currentTimeMillis();
     System.out.println(abc);
    Point point3 = Point.measurement("memory")
            .time(abc, TimeUnit.MILLISECONDS)
            .addField("used", 23L)
            .addField("free", 23L)
            .build();
    influxDB.write(dbName, "default", point1);
    influxDB.write(dbName, "default", point2);
    influxDB.write(dbName, "default", point3);
```

**Comment by jvchbabu** [comment]
Is there unique constraint like index or primary key on time field and only unique time values records get inserted?

**Comment by majst01** [comment]
Any chance to test against influxdb 1.0 ?

**Comment by majst01** [comment]
any news on this topic ? otherwise i will close it.
