### ISSUE TITLE
feature request: query parameters

### ISSUE THREAD

**Issue by retorquere** [influxdata/influxdb-java#189]
It'd be nice if a call to `influxDB.query(query);` would allow passing an parameter array which would be safely substituted for placeholders (something like `?`) in the query, quoting the value (for strings) or append a type indicator (the `i` for integers) as needed.

**Comment by majst01** [comment]
Im happy to accept a PR

**Comment by majst01** [comment]
As influxdb does not have such a feature well known from SQL databases, see: https://docs.influxdata.com/influxdb/v0.8/api/query_language/ 
I dont want to implement influxdb-java such a feature.
