### ISSUE TITLE
Influx 1.0GA - Breaking Changes

### ISSUE THREAD

**Issue by larrywalker** [influxdata/influxdb-java#195]
Saw this snipped in the release notes.  Does the break DB creation with the current 2.2 influxdb-java release?  Seems like db creation will fail with influx 1.0.

--- Here is a snippet from the Influx Release Notes ---
v1.0.0 [unreleased]

Breaking changes

The keywords IF, EXISTS, and NOT where removed for this release. This means you no longer need to specify IF NOT EXISTS for DROP DATABASE or IF EXISTS for CREATE DATABASE. If these are specified, a query parse error is returned.

**Comment by larrywalker** [comment]
I got the 1.0GA installed.

Confirmed that the createDatabase method will not longer work.

influxdb-java-2.2 - InfluxDBImpl.java
public void createDatabase(final String name) {
		Preconditions.checkArgument(!name.contains("-"), "Databasename cant contain -");
		this.influxDBService.query(this.username, this.password, "CREATE DATABASE IF NOT EXISTS \"" + name + "\"");
	}

Verified that the syntax no longer works.
InfluxDB shell version: v1.0.0
> create database if not exists "test"
ERR: error parsing query: found not, expected ; at line 1, char 20
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> create database "test"
> drop database "test"

**Comment by RaphaelAudet** [comment]
Hi, I had the issue too today, I wrote a little fix for this
https://github.com/influxdata/influxdb-java/pull/196

**Comment by larrywalker** [comment]
I read somewhere that the  "default" rp was change to "autogen"

**Comment by beckettsean** [comment]
@larrywalker correct: https://docs.influxdata.com/influxdb/v1.0/administration/013_vs_1/#modified-name-for-the-auto-generated-retention-policy.

**Comment by majst01** [comment]
Closed with: https://github.com/influxdata/influxdb-java/commit/8511af1855f291093d18f8037017a0d39f1f90a0

**Comment by beckettsean** [comment]
thanks, @majst01!

**Comment by beckettsean** [comment]
and many thanks, @RaphaelAudet!
