### ISSUE TITLE
create optional method in InfluxDBFactory().connect() where username is optional

### ISSUE THREAD

**Issue by mhiller** [influxdata/influxdb-java#197]
Based on industry feedback, it seems that its pretty common for internal influxdb instances to not have logins configured and just allow anyone to submit data. Currently connect() does not allow username password to be null or optional. 

If you do not have a login setup in your influxdb instance, you can pass an empty string but this does not "feel right"

**Comment by majst01** [comment]
passing null values is not a good practice and make precondition checking even more error prone.

so sorry i do not agree with this request.

**Comment by mhiller** [comment]
your not supported a common implementation of the service itself then, so the matter should not be considered closed. What is a better approach if the suggested implementation is not to standard ?

**Comment by majst01** [comment]
I know this documentation, but my arguments still apply.
If you disagree, please show me how a valid implementation would look like in a pull request.
