### ISSUE TITLE
Upgrade to okhttp3/retrofit2

### ISSUE THREAD

**Issue by bentatham** [influxdata/influxdb-java#203]
Upgrade to most recent okhttp3/retrofit2.  Luckily, they use different packages, so doesn't cause conflicts if someone is using them in their own code, but still think this should use the lastest library versions.

**Comment by majst01** [comment]
Hi @bentatham 

Do you have you already a working patch ?
I wanted to do that for the next release (2.4) but hadnt enought time to do so.

Greetings

**Comment by bentatham** [comment]
@majst01 Working on it now.  I'm pretty new to retrofit/okhttp, but want to learn about it...so this is a good opportunity.  A lot has changed...and not great migration docs unfortunately.

**Comment by majst01** [comment]
If you have any questions, please ask i will do my best.

**Comment by bentatham** [comment]
Do you really have to install and run influxdb on your local pc to run the tests?  Makes for very non-stand-alone build.

**Comment by majst01** [comment]
No, depends,
look at compile-and-test.sh , as long as you have docker installed on your machine no additional installations are required to run all tests.

**Comment by bentatham** [comment]
sorry about all the squashed commits -- didn't realize they would end up in the list above.  I'm relatively new to using github like this.
