### ISSUE TITLE
Race condition in BatchProcessor with resulting data loss

### ISSUE THREAD

**Issue by brettwooldridge** [influxdata/influxdb-java#207]
The BatchProcessor uses the `LinkedBlockingQueue.drainTo()` API [when it processes a batch](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/BatchProcessor.java#L158).  The documentation for the `drainTo()` method states unequivocally:

> ... the behavior of this operation is undefined if the specified collection is modified while the operation is in progress.

Under load it is _extremely likely_ that the [queue will be modified](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/BatchProcessor.java#L185) by another thread at the time that the batch processor runs, resulting in lost entries.

**Comment by majst01** [comment]
Do you have a sample solution for this problem ?
I would look at a PR

**Comment by nebehr** [comment]
I've got no test to prove it but as I understand it, the collection referred to in BlockingQueue javadoc is the target collection passed as a parameter to drainTo(). Otherwise there would be not much reason for drainTo() method at all.

**Comment by brettwooldridge** [comment]
@nebehr You are correct.  After looking at the implementation of LinkedBlockingQueue it appears to be consistent.  It is possible for ``drainTo()`` to *miss* elements that are added to the queue while it is being drained, but those elements will be picked up by the next call to ``drainTo()``, as far as I can tell.

This issue can be closed.
