### ISSUE TITLE
Connection to influxdb with SSL client certificate

### ISSUE THREAD

**Issue by prli** [influxdata/influxdb-java#209]
Hi,

Does the library support SSL with client certificate?

I am using this java library to connect to influxdb. My influxdb setup require client certificates to access the db.
However, when I use the library to connect, with the client certificate added in the java keystore, i am getting error code 400 back which means the client certificate is not sent.

I also tried to connect to influxdb using native java HttpURLConnection which returns error code 401, not 400 (expected because I didnt send over crendentials) which means the client certificate is successfully sent over and processed.

Thanks

**Comment by majst01** [comment]
Http connections are done using the okhttp library from square: https://github.com/square/okhttp . I am not aware how the handle client certificates but i would recommend asking them.

**Comment by prli** [comment]
Thanks for the reply, I solved the issue with the following link. I created a new instance of InfluxDB with the OkClient from the following link.

http://stackoverflow.com/questions/23103174/does-okhttp-support-accepting-self-signed-ssl-certs
