### ISSUE TITLE
Sending multiple queries in a single API call broken in 2.4

### ISSUE THREAD

**Issue by skovzhaw** [influxdata/influxdb-java#214]
Sending multiple queries to InfluxDB in a single API call is broken in 2.4 (delimiting each query using a semicolon, [see example](https://docs.influxdata.com/influxdb/v1.0/guides/querying_data/#multiple-queries)). It only returns the first result, where in 2.3 it worked flawlessly.

Guys, what has changed?

**Comment by majst01** [comment]
Can you write a test which shows this behavior ? This is actually not part of our unit-test otherwise it would have been seen. 

@bentatham any ideas ?

**Comment by majst01** [comment]
Any updates on this, as this scares me a bit.

**Comment by bentatham** [comment]
Nothing comes to mind.  I don't seen anything explicit in the code about separating based on ``;``, so it must have all been implicitly.  I suppose something might have changed in the switch to moshi when unmarshalling the json response back to java, but not sure what.  We need to add a test case for this for sure.

**Comment by skovzhaw** [comment]
Any ETA on fixing this? One of our use cases relies on it quite heavily. Thanks in advance

**Comment by shanexu** [comment]
okhttp does not encode ```;``` into ```%3B```. Then influxdb will execute the first query command.
for example
```bash
curl "http://127.0.0.1:8086/query?db=testdb&q=select%20*%20from%20notexist%3Bselect%20*%20from%20notexist"
```
the result should be

```json
{"results":[{},{}]}
```
but with ```influxdb-java``` the result is
```json
{"results":[{}]}
```

**Comment by majst01** [comment]
Is this on the request or response side ?

**Comment by shanexu** [comment]
the request side.
influxdb-java 2.3 using okhttp 2.7.5, and okhttp 2.7.5 using URLEncoder.encode encode query string, so there's no problem.
but influxdb-java 2.4 using okhttp 3.4.1, and okhttp 3.4.1 do not encode ```;```, so it make a query request like this
```
curl "http://127.0.0.1:8086/query?db=testdb&q=select%20*%20from%20notexist;select%20*%20from%20notexist"
```
there is a ```;``` in the query string.
influxdb will return a response like this
```json
{"results":[{}]}
```

**Comment by teixi** [comment]
`%3B` decodes to `;`
but `;` also decodes to `;`

The issue is that okhttp3  for browsers' consistency simply doesn't encode `;` anymore.
https://github.com/square/okhttp/issues/2975

Then InfluxDB backend in addition to the encoded `%3B` should also accept: `;`
https://github.com/influxdata/influxdb/issues/7623
