### ISSUE TITLE
JVM hanges after shutting down due to lingering thread

### ISSUE THREAD

**Issue by noamBarkai** [influxdata/influxdb-java#215]
When enabling batch writes, influxdb-java creates a scheduled executor to do the inserts async
Alas, the threads defined there are not daemon meaning that the application will hang if shutdown.
As a work-around one can call InfluxDB.disableBatch() which calls flush() on the batch-processor which in turn shuts down its underlying executor.
I think the proper way to fix this is defining the executor's thread to be daemon.
If on the other hand we want to force explicitly calling disableBatch() - because we want to make sure all events are flushed - then I think this should be explicitly documented.
I can create a PR for either change - LMK what you think?

**Comment by majst01** [comment]
Good point, i think documentation (in the Readme and Javadoc) is the way to go.
If you want to send a MR, this would be nice
