### ISSUE TITLE
Store time in a specific format via the influxdb-java api

### ISSUE THREAD

**Issue by anilhk** [influxdata/influxdb-java#240]
In the JAVA API, I want to know how should I set the time in the format 

```
time                                      location     scientist      butterflies     honeybees
2015-08-18T00:00:00Z      1                 langstroth    12                   23
2015-08-18T00:00:00Z      1                 perpetua      1                     30
2015-08-18T00:06:00Z      1                 langstroth    11                   28
```

**Comment by jiafu1115** [comment]
refer to https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/TimeUtil.java#L60? can this api solve your issue? 
I don't know what's your wanted time, I just see the standard time format used in influxdb.

**Comment by anilhk** [comment]
Actually when I converted time to ms it worked for me. I have the time consistent in Grafana and influxdb as milliseconds and my problem was resolved 

Thanks !
