### ISSUE TITLE
java.lang.IllegalArgumentException: Database name cant contain -

### ISSUE THREAD

**Issue by christiangda** [influxdata/influxdb-java#255]
According to InfluxDB docs in [Creating a database](https://docs.influxdata.com/influxdb/v1.1/introduction/getting_started/)
> Names of databases can contain any unicode character as long as the string is double-quoted. Names can also be left unquoted if they contain only ASCII letters, digits, or underscores and do not begin with a digit.

you can improve the code to send the database name string between  "double-quoted".

**Comment by jiafu1115** [comment]
version 2.5 had fixed the issue. It will on maven central soon

**Comment by majst01** [comment]
2.5 is released now, closing this.
