### ISSUE TITLE
Allow all string-like field values to be correctly double quoted

### ISSUE THREAD

**Issue by jsotelo** [influxdata/influxdb-java#258]
This issue is derived from https://github.com/influxdata/influxdb-java/commit/f084c5513c316ac3ef27dddd9621191348aee830#commitcomment-20181808

Currently field values are only double quoted (when creating an influxdb point) if they are of type String. This makes working with other string-like object such as StringBuilder, StringBuffer, CharBuffer or in my case org.apache.avro.util.Utf8 more cumbersome and error-prone.

If any of these value types are sent to influxdb-java, an invalid influxdb line will be created, sent and rejected by the server (since it produces unquoted text).

Changing the referenced code to:
```
if (value instanceof CharSequence) {
        String stringValue = value.toString();
```
will avoid sending invalid influxdb lines to the server, provide a better user experience as well as remain performant.

**Comment by asashour** [comment]
Is this still valid? Can you provide a test case please?
