### ISSUE TITLE
BatchPoints and Point should implement equals() and hashCode()

### ISSUE THREAD

**Issue by joelmarty** [influxdata/influxdb-java#266]
In order to test that my programs correctly build the BatchPoints and Point objects, I like to use hamcrest matchers. Since the dto objects don't implement equals and hashCode, I cannot do that:

`assertThat(actualBatch, is(expectedBatch))` will always return false since we fall back to Object.equals() behavior.

Very simple :)

**Comment by majst01** [comment]
If you provide a PR which also includes some additional unittests i will review it

**Comment by joelmarty** [comment]
I think I can manage to have some spare time to do that
