### ISSUE TITLE
Nanosecond value in Point time field is stored in Long?

### ISSUE THREAD

**Issue by gmegan** [influxdata/influxdb-java#267]
When creating points to write to influx using Java Instant:

```
        Instant stamp = Instant.now();
        Point point1 = Point.measurement("cpu")
                .time(stamp.getEpochSecond() * 1000000000 + stamp.getNano(), TimeUnit.NANOSECONDS)
                .addField("idle", 90L)
                .addField("system", 1L)
                .build();
```

From Java Instant documentation:
>The range of an instant requires the storage of a number larger than a long. To achieve this, the class stores a long representing epoch-seconds and an int representing nanosecond-of-second, which will always be between 0 and 999,999,999. 

So the previous code may overflow the Long field for time. Maybe time would be better as BigInteger?

**Comment by J0s3f** [comment]
I totally support this. Currently it is not easily possible to store Java Instant values in InfluxDB using this driver (or is there another way?). A long in nanosecond has only about 292 years as maximum value.

**Comment by bednar** [comment]
@J0s3f 

Maximum value of `long` is `9,223,372,036,854,775,808`. This allow store date up to `Friday, April 11, 2262 11:47:16.854 PM`. It is not enough?

**Comment by J0s3f** [comment]
@bednar we use this to implement a software where users can upload arbitrary data, so we can't make assumptions.

**Comment by jjathman** [comment]
I believe the fix to this actually breaks binary compatibility because of the move from `long` primitive to `Long` the object. With the latest release we are getting this error with our code at runtime.

```
'org.influxdb.dto.Point$Builder org.influxdb.dto.Point$Builder.time(long, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'org.influxdb.dto.Point$Builder org.influxdb.dto.Point$Builder.time(long, java.util.concurrent.TimeUnit)'
```

This is using Java 11, but I don't think that makes a difference. Could we put the API back to what it was before with `long` as a primitive?
