### ISSUE TITLE
Preventing SQL Injection

### ISSUE THREAD

**Issue by r0man** [influxdata/influxdb-java#274]
Hello, 

what's the proper way to prevent SQL injection in the Java client? I found this ticket for the Go client, but could not find anything related in the Java sources.

https://github.com/influxdata/influxdb/issues/2926

Thanks, Roman.

**Comment by majst01** [comment]
Hi @r0man 

This is indeed required. Any idea how we could implement such a prepared statement parse with as least effort as possible ?

**Comment by r0man** [comment]
@majst01 Thanks for the confirmation. No, don't have an idea yet. I'll let you know if I do :)

**Comment by joelmarty** [comment]
Perhaps the most obvious way would be to support prepared statements in the jdbc lib or hibernate framework does i.e. :

```
PreparedQuery pq = new PreparedQuery("SELECT * FROM measures WHERE time > :lowerBound and time < :upperBound and device = :device");
pq.setDate("lowerBound", myLowerDate);
pq.setDate("upperBound", myUpperDate);
pq.setString("device", myDevice);
```
this way you can sanitize the input for each argument.

**Comment by majst01** [comment]
sure, but i dont want to add hibernate for example as a direct dependency to influxdb-java.

Is there any small implementation out there which can be reused easily ?

**Comment by majst01** [comment]
From Influxdb [documentation](https://docs.influxdata.com/influxdb/v1.2/tools/api/) this must look like:

```bash
curl -G 'http://localhost:8086/query?db=mydb' --data-urlencode 'q=SELECT * FROM "mymeas" WHERE "myfield" > $field_value' --data-urlencode 'params={"field_value":30}'
```

so adding a `params` parameter to the Influxdb.query should do the trick.

**Comment by r0man** [comment]
Thanks!

**Comment by majst01** [comment]
But the current implementation does not allow this kind of query. We need to add this ability.

**Comment by majst01** [comment]
I quite simple impl of Select is here https://github.com/gocraft/dbr/blob/master/select.go but apperently in golang. Could be used as a starting point
