### ISSUE TITLE
Incorrect json conversion because of new Influx 1.2 statement_id in returned json

### ISSUE THREAD

**Issue by jefferyKuhn** [influxdata/influxdb-java#277]
I was testing using the new influx 1.2, and noticed that the json coming back has a new attribute, statement_id. I'm not sure what it's for, but when I try to use the QueryResult to convert the json to the queryResult, it fails because of this new tag. I've attached my changes to queryResult class which makes the conversion work. I'm not sure how to make a request that this get changed in the code base. This allowed me to correctly work with the results from the new Influxdb 1.2.0 version. 
[QueryResult.zip](https://github.com/influxdata/influxdb-java/files/736287/QueryResult.zip)

**Comment by majst01** [comment]
Today i added influxdb 1.2 to the unit-tests and they all worked as with 1.1 and 1.0. So i wonder why you see this breakage.

Any chance to write a unit test which can show this failure ?

**Comment by jefferyKuhn** [comment]
Hmm, interesting. Are you seeing the new statement_id in the json? I was performing a "show retention policies on <dbName>". Do the current tests make that query? I am using jackson to perform the conversion, I'm not sure if the rest of the influxdb-Java project uses that or another method for converting to objects. I'm only using the queryResult class in my client. Nothing else from this project. 
Unfortunately, I'm not familiar with writing unit tests. Do you have an example I can look at to follow?

**Comment by majst01** [comment]
influxdb-java uses https://github.com/square/retrofit which uses internally https://github.com/square/moshi for (de)serialization of json objects. And this works pretty well for a lot of users.

For example tests look at https://github.com/influxdata/influxdb-java/blob/master/src/test/java/org/influxdb/InfluxDBTest.java

Greetings
