### ISSUE TITLE
All dependencies at runtime

### ISSUE THREAD

**Issue by MrDienns** [influxdata/influxdb-java#280]
Hi,

I'm currently making a Java project and I need to push data to InfluxDB. I found this project and it seemed pretty legit, untill I looked at the ridiclious amount of dependencies.

How do I get all of these dependencies working for Java at runtime, without adding all sorts of .jar files in my servers?

Thanks

**Comment by majst01** [comment]
This is a maven project, so you just have to add

```xml
<dependency>
  <groupId>org.influxdb</groupId>
  <artifactId>influxdb-java</artifactId>
  <version>2.5</version>
</dependency>
```
to your pom.xml and all is calculated automatically. 
If you build a .war for example all needed jars will be included in the war.
No need to copy several jars by hand.

hope this helps

**Comment by MrDienns** [comment]
Yes, I managed to execute a maven command that builds the jar _including dependencies_, which was what I needed.

**Comment by saumyaAgupta** [comment]
how do you know which version to add in the dependency?
