### ISSUE TITLE
Introduction of Java 8

### ISSUE THREAD

**Issue by bentatham** [influxdata/influxdb-java#288]
It seems that java 8 has been introduced (for example, use of ``java.util.function.Consumer`` in PR #259, 5e743df, among other places).

However, the pom.xml still sets the java source/target to 1.7. So I'm curious that status of java version here.

According to #88, there were no plans to go to java8 back in 2015, but I wonder if that has, or should be, revisited.

**Comment by majst01** [comment]
This is what i personally do not understand, how can the maven-compiler-plugin compile code with source and target set to 1.7 if there are 1.8 only imports in the codebase.

On the other side, in 2017 with the upcoming java9, i think time is ready to switch to java-8 only.

I would like to poll all users, but i dont know how.

Do you have an idea, objections ?

**Comment by bentatham** [comment]
> This is what i personally do not understand, how can the maven-compiler-plugin compile code with source and target set to 1.7 if there are 1.8 only imports in the codebase.

This is because of the different between the java language and the java library.  The code introduced use of the Java8 Library updates -- ie interfaces/classes defined in Java8, but did NOT introduce the use of any language features (like lambda syntax).  Therefore, as long as you building with Java8 SDK & Libraries, even if the target/source is 1.7, you can still reference classes defined in Java8.  Hence, it all still compiles.  It is clear though that the author of the PR was using lambdas in the application code around the influxdb-java.

 > On the other side, in 2017 with the upcoming java9, i think time is ready to switch to java-8 only.

I totally agree.  At this point, I think any uses of influxdb-java who require Java 7 or older can stick with old versions of the library.  I have no idea how to poll the users, but it seems that Oracle and the Java community are pushing forward quickly by stopping to create security patches for older java releases.  I suspect when Java 9 is released, that might happen to Java 7 as well.

**Comment by pjmyburg** [comment]
I fully support switching to Java 8, but just want to add that my PR #284 removes the Java 8 dependency in case that helps.

**Comment by majst01** [comment]
#312 is related as well
