### ISSUE TITLE
[feature request] Create and Drop retention policy

### ISSUE THREAD

**Issue by kostasb** [influxdata/influxdb-java#295]
Feature request to provide a createRetentionPolicy method in a proposed form of:

`influxDB.createRetentionPolicy(rpName,dbName,duration,shardDuration,replication,default);`

Respectively, a dropRetentionPolicy method should accompany this:

`influxDB.dropRetentionPolicy(rpName,dbName);`

**Comment by majst01** [comment]
If you are willing to write a PR i will review it.
