### ISSUE TITLE
I could only query 10000 pieces data a time? what's the reason? 

### ISSUE THREAD

**Issue by xiahaohuan001** [influxdata/influxdb-java#301]
I could only query 10000 pieces data a time? what's the reason?

**Comment by xiahaohuan001** [comment]
I have 7 million pieces data in my DB.when i query the data,for example ## select * from measurement_name.## 

It can return 7million pieces data when I query in "localhost:8083/3000".But it can only return 10000 pieces data in "Series" when I query in java client.It always be 10000.I can't get data more then 10000 pieces from my DB. 
My Influxdb version is 1.2.0
java sdk:1.8
java client version:2.5

**Comment by tdeleeuw** [comment]
Did you checked the parameter "max-row-limit" (in the http section) of the InfluxDB server?
Note that this default value will change after upgrade to 1.2.1
See https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v122-2017-03-14

**Comment by xiahaohuan001** [comment]
How can I change the "max-row-limit"?

**Comment by tdeleeuw** [comment]
Hi
You must edit the Influx DB server configuration. Please read the manual for instruction.
Thierry

**Comment by xiahaohuan001** [comment]
Thank you very much,I have solved the problem.Thanks for your help!!!!

**Comment by tdeleeuw** [comment]
You are welcome. Could you please close the issue?
Thanks
