### ISSUE TITLE
Inserting slashes as a field gives a bad timestamp error

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb-java#303]
Hi, 
If I attempt to insert backslashes in a field I get bad timestamp errors: 

If I use the following code: 
 ```
 Point point1 = Point
                            .measurement("TestSlash")
                            .time(rundate1Sec, TimeUnit.SECONDS)
                            .tag("precision", "Second")                       
                            .addField("MultipleSlash" ,  "echo \\\".ll 12.0i\\\";")                            
                            .build(); 
        
         currentPoints.point(point1); 
           
         Influxdb.write(currentPoints.build());

```
I get the following error:
`{"error":"unable to parse 'TestSlash,precision=Second MultipleSlash=\"echo \\\\\".ll 12.0i\\\\\";\" 1490273411000000000': bad timestamp"}
`

**Comment by majst01** [comment]
This is probable a lack of functionality of the influxdb line protocol. Influxdb-java escapes backslashes as required and sends

```
'TestSlash,precision=Second MultipleSlash=\"echo \\\\\".ll 12.0i\\\\\";\" 1490273411000000000'
```

to the database, which seems correct.
The error you see is coming from the database.

**Comment by rossmcdonald** [comment]
I think the correct escaping should be:

```
TestSlash,precision=Second MultipleSlash="echo \\\\\".ll 12.0i\\\\\";" 1490273411000000000
```

Where the first and last `"` are not escaped, which marks the field value as a string type. If the strings are escaped properly, then this works as expected:

```
> insert TestSlash,precision=Second MultipleSlash=\"echo \\\\\".ll 12.0i\\\\\";\" 1490273411000000000
ERR: {"error":"unable to parse 'TestSlash,precision=Second MultipleSlash=\\\"echo \\\\\\\\\\\".ll 12.0i\\\\\\\\\\\";\\\" 1490273411000000000': invalid boolean"}
> insert TestSlash,precision=Second MultipleSlash="echo \\\\\".ll 12.0i\\\\\";" 1490273411000000000
> select * from TestSlash
{"results":[{"series":[{"name":"TestSlash","columns":["time","MultipleSlash","precision"],"values":[[1490273411000000000,"echo \\\\\".ll 12.0i\\\\\";","Second"]]}]}]}
```

**Comment by ivanscattergood** [comment]
It looks like I was using an older version of the library. 

I have built a test to prove the correct functionality:

`
/**
	 * Test for ticket #303
	 *
	 */
	@Test
	public void testTicket303() {
		String dbName = "ticket303_" + System.currentTimeMillis();
		this.influxDB.createDatabase(dbName);
		
                
                Date rundate1 = new Date() ; 
                long rundate1Sec = rundate1.getTime() / 1000;
       
        
     Point point1 = Point
                            .measurement("TestSlash")
                            .time(rundate1Sec, TimeUnit.SECONDS)
                            .tag("precision", "Second")                       
                            .addField("MultipleSlash" ,  "echo \\\".ll 12.0i\\\";")                            
                            .build(); 
		this.influxDB.write(dbName, TestUtils.defaultRetentionPolicy(this.influxDB.version()), point1);
		this.influxDB.deleteDatabase(dbName);
	}
`

**Comment by majst01** [comment]
fine, if it works as expected please close this issue.

**Comment by ivanscattergood** [comment]
Is it worth adding this test to your suite?

**Comment by majst01** [comment]
every added corner case in tests is a win, i would merge it if you raise a PR.
