### ISSUE TITLE
Chunking and flushing?

### ISSUE THREAD

**Issue by Dromit** [influxdata/influxdb-java#308]
Based on the changelog file it seems like chunking is available since v2.5, but I don't see it as part of the .query() methods in that version. Was it really added? It's again in the changelog of v2.6 so I'm guessing it wasn't really added in the current release.

Regarding v2.6, it adds .flush() which is also pretty helpful. Is there an estimate release date for that version?

**Comment by Dromit** [comment]
For anyone else looking to try these features before v2.6 is released, you can use JitPack on your Maven file like this:

```
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>

<dependency>
    <groupId>com.github.influxdata</groupId>
    <artifactId>influxdb-java</artifactId>
    <version>3a87da8e8b</version>
</dependency>
```

3a87da8e8b is currently the last commit.

Be aware chunked queries are just like normal queries, except that the results are returned in smaller chunks. ALL records will be iterated through eventually, since there's no way to stop it (https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L359).

It would be nice to have an Iterable (or Iterator) instead, the usage would be something like this:

```java
Iterable<QueryResult> results = conn.query(new Query("sql here", "database"), 10000);
for (QueryResult result : results) {
    // Do something
}
```

Otherwise chunking is not that useful in my opinion, it's NOT like creating a cursor in a relational database such as PostgreSQL or paginating the results.

Regards,
Matt

**Comment by Dromit** [comment]
I'm sending a pull request with that method implemented.

The signature is as follows.

```java
  public Iterator<QueryResult> query(Query query, int chunkSize);
```

I've tried it to iterate over a 350m rows measurement with no problem. As expected, the first chunk is returned after only a few seconds, the rest is processed without increasing the memory consumption.

I hope to see this method on the next release!

**Comment by J0s3f** [comment]
A method that adds an iterator for the result would be really great.
It is a easy way to add chunking to existing code.
The need to implement callbacks and whatnot as in the current implemented methods is a huge overhead.
