### ISSUE TITLE
Subclass RuntimeException?

### ISSUE THREAD

**Issue by gnebehay** [influxdata/influxdb-java#313]
As far as I can see, the error handling in influxdb-java consists of Exceptions wrapped in a `RuntimeException`, like here: https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L101
I presume that one reason for doing so was to make the Exception handling unchecked, which I am in principle not opposed to. However, this pattern forces me to surround calls to influxdb-java in try-catch blocks catching `RuntimeExceptions`. I just now ran into a case where I had a NullPointerException within this try-catch block that, being an instance of `RuntimeException` also gets caught. Wouldn't it be much better to create a custom exception, e.g. `InfluxException` that inherits from `RuntimeException`? This way client-side error handling gets much easier and if I am not mistaken, it would not even break existing code.

**Comment by majst01** [comment]
Yes, checked Exceptions are considered harmful nowadays. Where did you get a NPE ? If this is caused by influxdb-java it can be considererd as a bug and should reported as such. Im not keen to introduce a new exception for no clear reason.

**Comment by gnebehay** [comment]
The NPE was caused by a bug in my own code, which ended up being caught by the try-catch block surrounding the influxdb-java calls, which is undesirable.

To make the whole thing clearer by an example:
```
try {
InfluxDB influxDB = InfluxDBFactory.connect(connectionString, username, password);

//myOwnCustomObject is set to null due to a bug
Object myOwnCustomObject = null;

//NPE occurs            
influxDB.write(... myCustomObject.myProperty ...)

catch (RuntimeException e) {
  // Want to handle only influxDB errors here, but the NPE gets caught here, too
}
```
If there was a custom InfluxException (extending RuntimeException), this would allow for this error handling: 
```
try {
InfluxDB influxDB = InfluxDBFactory.connect(connectionString, username, password);

//myOwnCustomObject is set to null due to a bug
Object myOwnCustomObject = null;

//NPE occurs            
influxDB.write(... myCustomObject.myProperty ...)

catch (InfluxException e) {
  // Only influxDB errors end up here, the NPE bubbles up the stack
}
```
Not only NPEs cause this behaviour, but a ton of other Exeptions, too, as can be seen from the docs: https://docs.oracle.com/javase/7/docs/api/java/lang/RuntimeException.html

**Comment by gnebehay** [comment]
Here is a reference to back up my claim: https://www.securecoding.cert.org/confluence/display/java/ERR07-J.+Do+not+throw+RuntimeException%2C+Exception%2C+or+Throwable
