### ISSUE TITLE
batch 10000 point lose data

### ISSUE THREAD

**Issue by afreetgo** [influxdata/influxdb-java#314]
1. run program:

public void save(int num){
     influxDB.enableBatch(2000,100,TimeUnit.MILLISECONDS);
     for (int i = 0; i < num; i++) {
           point = Point.measurement("cpu").tag("devNo", "FC"+RandomUtil.random(100000, 100010))  
	                .time(calendar.getTimeInMillis(), TimeUnit.MILLISECONDS)  
	                .field("value", RandomUtil.randomDouble(0, 1))
	                .field("date", DateUtil.getNewFormatDateString(new Date()))
	                .build();
           influxDB.write("test_db","autogen",point);
     }
}
public static void main( String[] args ) throws Exception {
    InfludbSaver saver = new InfludbSaver();
    InfluxDB influxDB = InfluxDBFactory.connect("http://127.0.0.1:8086", "root", "root");
    saver.save(influxDB,10000);
}

2.  select count(*) from "cpu" 
     but Data is only 4646, should be 10000
3. influxdb-java version 2.5 
    influxdb version 1.2.2

**Comment by majst01** [comment]
You need to flush you data with:
```java
influxDB.flush()
```
before querying

**Comment by afreetgo** [comment]
no this method

**Comment by afreetgo** [comment]
add influxDB.flush() . But there is no one batch of 2000 points, the performance is not high。

**Comment by majst01** [comment]
Writing multiple points at the same timestamp are condensed to a single point.

**Comment by afreetgo** [comment]
thanks ，At the same timestamp , I find  the same tags saves only the first data. but I want to save all data.

**Comment by majst01** [comment]
But as for all time series databases, timestamp must be unique. If you need higher precision, use a higher precise timestamp.

**Comment by afreetgo** [comment]
thanks very much, Set nanosecond level can be solved。

point = Point.measurement("cpu").tag("cabinNo", "FC"+RandomUtil.random(100000, 100010))  
	                .time(calendar.getTimeInMillis(), TimeUnit.MILLISECONDS)  
	                .field("value", RandomUtil.randomDouble(0, 1))
	                .field("date", DateUtil.getNewFormatDateString(date))
	                .time(System.nanoTime(), TimeUnit.NANOSECONDS)
	                .build();

In addition,I modified the BatchProcessor.write method, No call influxDB.flush ();

void write() {
    try {
      if (this.queue.isEmpty()) {
        return;
      }
      if (this.actions>this.queue.size()){
    	  return;
      }
     ......
