### ISSUE TITLE
Write nothing to an existed database but received 204 No Content

### ISSUE THREAD

**Issue by yuguangchuan** [influxdata/influxdb-java#315]
**Problem description**:
- **Writing to an existed database will receive "204 No Content", which seems to have successfully finish write operations. However, no measurement or point is there in this database.**
- When the API create a new database and write into the new API created database, all goes fine.

Executable file and InfluxDB are all in local environments. Any one can give some advices? Thx~

**InfluxDB Log info**:
> [I] 2017-04-26T10:03:56Z Write body received by handler: cpu,network=network1 impression=1i 321876639556798
> cpu,network=network1 impression=1i 321876639845910
> cpu,network=network1 impression=1i 321876639851278
>  service=httpd
> [httpd] 127.0.0.1 - admin [26/Apr/2017:18:03:56 +0800] "POST /write?consistency=all&db=test_geode&p=%5BREDACTED%5D&precision=n&rp=three_days&u=admin HTTP/1.1" 204 0 "-" "okhttp/3.4.1" a8cf6ace-2a67-11e7-80b4-000000000000 146
> [httpd] 127.0.0.1 - - [26/Apr/2017:18:04:11 +0800] "GET /ping HTTP/1.1" 204 0 "-" "InfluxDBShell/v1.2.0" b1d4077d-2a67-11e7-80b5-000000000000 40

**Java API Log info(with `LogLevel.BASIC`)**:
> gcyu-mac:GeodeInfluxDB gcyu$ java -jar target/GeodeInfluxDB-1.0-SNAPSHOT-jar-with-dependencies.jar
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: --> POST http://localhost:8086/write?u=admin&p=admin&db=test_geode&rp=three_days&precision=n&consistency=all http/1.1
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: Content-Type: text/plain; charset=utf-8
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: Content-Length: 510
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息:
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: cpu,network=network1 impression=1i 320390000948172
> cpu,network=network1 impression=1i 320390001211009
> cpu,network=network1 impression=1i 320390001216095
> cpu,network=network1 impression=1i 320390001219702
> cpu,network=network1 impression=1i 320390001222846
> cpu,network=network1 impression=1i 320390001225932
> cpu,network=network1 impression=1i 320390001229013
> cpu,network=network1 impression=1i 320390001232066
> cpu,network=network1 impression=1i 320390001235097
> cpu,network=network1 impression=1i 320390001238087
> 
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: --> END POST (510-byte body)
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: <-- 204 No Content http://localhost:8086/write?u=admin&p=admin&db=test_geode&rp=three_days&precision=n&consistency=all (19ms)
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: Content-Type: application/json
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: Request-Id: 32ba0c20-2a64-11e7-80b3-000000000000
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: X-Influxdb-Version: v1.2.0
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: Date: Wed, 26 Apr 2017 09:39:09 GMT
> Apr 26, 2017 5:39:09 PM okhttp3.internal.platform.Platform log
> 信息: <-- END HTTP

**Comment by majst01** [comment]
can you please retry with the latest snapshot, there have been some infrastruktur changes and rerun the same test with LogLevel.FULL  enabled.

**Comment by wlami** [comment]
@yuguangchuan I've had this situtation (http 204 return but no data visible) when I was inserting data that had a timestamp older than the retention period. Your timestamps are looking weird to me. The timestamp of the moment (06/14/2017 @ 11:08am (UTC)) I am writing this is `1497438489` (in seconds precision) or `1434067467000000000` (in nanoseconds). Your timestamps start with "3" which could be the problem.

**Comment by yuguangchuan** [comment]
@wlami Thank you for your reply, it's really the point that caused the problem. All goes right when the timestamp, time precision and retention policy were set correctly.

**Comment by majst01** [comment]
@yuguangchuan feel free to close the issue, once you are satisfied.
