### ISSUE TITLE
TimeUtil.fromInfluxDBTimeFormat does not handle timestamp rounded to seconds

### ISSUE THREAD

**Issue by tobyfan1980** [influxdata/influxdb-java#326]
If the timestamp happen to be at a second with 0 nano, the rfc3339 string is like "yyyy-mm-ddTHH:mm:ssZ" 

timeDF.parse(timePart) throw exception "unexpected date format"

**Comment by majst01** [comment]
Please show the actual java code which produces this Exception (including the whole stacktrace)

**Comment by tobyfan1980** [comment]
`TimeUtil.fromInfluxDBTimeFormat("1970-01-01T00:00:00Z")`

Exception in thread "main" java.lang.RuntimeException: unexpected date format
	at org.influxdb.impl.TimeUtil.fromInfluxDBTimeFormat(TimeUtil.java:88)
	at tools.ilabservice.influxdb.InfluxTest.TestQueryCount(InfluxTest.java:92)
	at tools.ilabservice.influxdb.InfluxTest.main(InfluxTest.java:160)
Caused by: java.text.ParseException: Unparseable date: "00:00:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.influxdb.impl.TimeUtil.fromInfluxDBTimeFormat(TimeUtil.java:86)
	... 2 more

**Comment by majst01** [comment]
This is obviously not the actual code:
https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/TimeUtil.java#L88
is a comment.

please try with actual code from source

**Comment by tobyfan1980** [comment]
I see the difference.  Why the code is different?  I added the dependency in pom.xml.  Is the code in github newer?

<dependency>
            <groupId>org.influxdb</groupId>
            <artifactId>influxdb-java</artifactId>
            <version>2.5</version>
</dependency>

**Comment by fmachado** [comment]
@tobyfan1980 yes, usually the source-code available [here](https://github.com/influxdata/influxdb-java/tree/master/src) reflects the latest changes to the project, things that you will probably see when you upgrade the Maven artifact from an old to a new version.

With the current existing code, I cannot reproduce this issue. @tobyfan1980 are you able to update to the latest version (2.6) and try again? If it works, could you please close this issue?

**Comment by tobyfan1980** [comment]
Verified that the above issue is resolved in 2.6.

**Comment by majst01** [comment]
Great, btw. version 2.7 is available since a few days with a lot of important improvements.
