### ISSUE TITLE
Feature Request:  support Query String Parameters

### ISSUE THREAD

**Issue by tobyfan1980** [influxdata/influxdb-java#328]
As described in [document](https://docs.influxdata.com/influxdb/v1.2/tools/api/#query-string-parameters) ,  it would be nice to pass some query string parameters into the Query constructor. 

For example, using curl, we can do 
curl -G 'http://localhost:8086/query?db=mydb&epoch=s' --data-urlencode 'q=SELECT * FROM "cpu"'

Correspondingly, we should be able to pass "epock=s" to the Query object.

**Comment by majst01** [comment]
Please check if issues are already raised for the same topic

duplicate of #274
