### ISSUE TITLE
QueryResult to Object mapper

### ISSUE THREAD

**Issue by fmachado** [influxdata/influxdb-java#340]
I had some issues in the past handling the QueryResult and the internal data structure. In order to make the result manipulation more simple, I created an object mapper between the QueryResult and an annotated POJO.

https://github.com/fmachado/influxdb-pojomapper

Do you have any plans to add a similar feature to influxdb-java?

BTW, thank you Stefan and everyone here working to maintain this library.

**Comment by majst01** [comment]
Hi @fmachado,

This would be a great enhancement to influxdb-java ! I would love to integrate it. If you mind you can create a pull request for the integration and we can discuss on that how to proceed.

**Comment by fmachado** [comment]
@majst01 thanks for the quick response on this issue.

I'll give you a hand if there is anything reported related with this feature. Also, I've already got an OK from my employee ([azeti Networks AG](http://azeti.net)) to keep contributing with more improvements, if necessary.

I'm closing this issue.

**Comment by majst01** [comment]
This is interesting, greetings to your CEO i know him personally from a former bank project in munich :-)
