### ISSUE TITLE
Is it impossible to get tag using 'InfluxDBResultMapper' with group by?

### ISSUE THREAD

**Issue by ilias-y** [influxdata/influxdb-java#343]
Hi, InfluxDBResultMapper helps me to use influxdb-java. 
But I wonder how to use tag in '@Column(name="a", tag=true)'. I want to get the tags from QueryResult with toPOJO(). is it impossible to get the tags of series in QueryResult?

This is my QueryResult.
`QueryResult [results=[Result [series=[Series [name=tb_network, tags={CARRIER=000/00, DEVICE_OS_VERSION=4.4.2}, columns=[time, median, min, max], values=[[1970-01-01T00:00:00Z, 233.8, 0.0, 3090744.0]]], Series [name=tb_network, tags={CARRIER=000/00, DEVICE_OS_VERSION=9.3.5}, columns=[time, median, min, max], values=[[1970-01-01T00:00:00Z, 552.0, 135.0, 267705.0]]]], error=null]], error=null]`

I got the values but not the tags.

**Comment by fmachado** [comment]
@ilias-y you are right: "group by" results are not currently supported but I'm working on it.

"Stay tuned." :)

**Comment by ilias-y** [comment]
I'm looking forward to work it. When do you plan to complete this?

**Comment by fmachado** [comment]
@ilias-y could you please test it?
Just a heads up: InfluxDB tags are always _String_ and currently we do not support Class field declarations other than... String. :)
