### ISSUE TITLE
Enable configuration of timeouts ..

### ISSUE THREAD

**Issue by sjerman** [influxdata/influxdb-java#347]
could this PR be merged to master: #123 ... 
Thanks

**Comment by majst01** [comment]
You can use this https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/InfluxDBFactory.java#L59  Constructor and pass your own instance of a OkhttpClient with your settings.

**Comment by fmachado** [comment]
@sjerman If the proposed solution works for you, could you please close this issue?

**Comment by sjerman** [comment]
OK. thx will do what you suggest

**Comment by rozpuszczalny** [comment]
I'd like to reopen this issue.
In my opinion, knownledge of OkHttpClient shouldn't be necessary to set timeout for connections. Being able to specify timeout will make code much cleaner and more resistant to faulty configs. Also I think that passing instance of a OkHttpClient should stay anyway, if someone wants to do more complicated configuration. Timeout is common scenario.
