### ISSUE TITLE
Add possibility to let InfluxDB handle the timestamp itself

### ISSUE THREAD

**Issue by wasnertobias** [influxdata/influxdb-java#349]
Due to a [bad support of accurate timestamps](https://stackoverflow.com/a/33487917) (especially in older Java versions) I would love to let InfluxDB handle the timestamps by itself.

> A point is uniquely identified by the measurement name, tag set, and timestamp. If you submit a new point with the same measurement, tag set, and timestamp as an existing point, the field set becomes the union of the old field set and the new field set, where any ties go to the new field set. This is the intended behavior.

[read more](https://docs.influxdata.com/influxdb/v1.2/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points)

As I have several data-points in a single measurement per second and it is not very recommended to have a unique-id in a tag (performance reasons) I would like to have an accurate timestamp. Otherwise I would loose data!

In the method build of Point I found the following behavior:

>             if(this.time != null) {
>                 point.setTime(this.time);
>                 point.setPrecision(this.precision);
>             } else {
>                 point.setTime(Long.valueOf(System.currentTimeMillis()));
>                 point.setPrecision(TimeUnit.MILLISECONDS);
>             }

So, if no time is provided for a certain point this library does not what I want it to do. I can't find any simple way to let InfluxDB handle the timestamp using this library?

**Comment by majst01** [comment]
#312 is addressing this issue, i liked the approach, but the current author is not able to fix merge conflicts. So if you are interested you can catch up there.

**Comment by fmachado** [comment]
The [line protocol](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/) states that "Timestamp" is optional.
@majst01, dropping the _else_ block mentioned above and adjusting  _org.influxdb.dto.Point.formatedTime(StringBuilder)_ seems to be enough to fix this issue.

Am I missing something?

**Comment by wasnertobias** [comment]
@majst01 Why should there be a need to update the Java-version of this lib? I think you got me wrong.

I just want to act according to the documentation which says, that whilst writing data it is **optional to provide a timestamp**.
[read more](https://docs.influxdata.com/influxdb/v1.2/introduction/getting_started/#writing-and-exploring-data)

**Comment by wasnertobias** [comment]
Working on a fix.
