### ISSUE TITLE
android.os dependency not found

### ISSUE THREAD

**Issue by mabunixda** [influxdata/influxdb-java#352]
Hi,

i added influxdb-java using maving to an Atlassian Plugin. now the spring scanning mechanism detects the android.os dependency and is not able to laod this ... 

How can i prevent loading android.os dependency?
`Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle my-atlassian-plugin[194]: Unable to resolve 194.0: missing requirement [194.0] osgi.wiring.package; (osgi.wiring.package=android.os)
`

Martin

**Comment by majst01** [comment]
I'm afraid, i do not have any deeper OSGI knowledge and i cant test this here. My guess is that this is introduced by the guava dependency.

**Comment by majst01** [comment]
What version of influxdb-java are you using, since 2.7 guava dependency is gone.

**Comment by mabunixda** [comment]
I am using the latest 2.7 version 

>         <dependency>
>             <groupId>org.influxdb</groupId>
>             <artifactId>influxdb-java</artifactId>
>             <version>2.7</version>
>         </dependency>

**Comment by majst01** [comment]
Reading the Exception again, i cant see any pointer to influxdb-java ? Are you sure in you bundle "my-attlasian-plugin" all dependencies are well configured ?

I doubt that this is caused by influxdb-java.

**Comment by mabunixda** [comment]
but the problem just happens when adding influxdb-java :( 
The problem is may be caused by the spring environment Atlassian is using in their products. Those auto-magic loading stuff sometimes sucks ;-(

**Comment by fmachado** [comment]
Google Guava artifact is still used (test scope) but IMO it is not related with the reported issue here.

@mabunixda could you please check the [Atlassian comunity forum](https://community.atlassian.com/t5/Answers-Developer-Questions/Why-am-I-getting-quot-Unresolved-constraint-in-bundle-quot/qaq-p/557505) and make sure that you are following [all necessary steps](https://developer.atlassian.com/docs/getting-started/set-up-the-atlassian-plugin-sdk-and-build-a-project/put-the-final-polish-on-the-project-in-eclipse) to build your own plugin?

```mvn dependency:tree -Dincludes=com.google.*
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building influxdb java bindings 2.7-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ influxdb-java ---
[INFO] org.influxdb:influxdb-java:jar:2.7-SNAPSHOT
[INFO] \- com.google.guava:guava:jar:22.0:test
[INFO]    +- com.google.code.findbugs:jsr305:jar:1.3.9:test
[INFO]    +- com.google.errorprone:error_prone_annotations:jar:2.0.18:test
[INFO]    \- com.google.j2objc:j2objc-annotations:jar:1.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.155 s
[INFO] Finished at: 2017-07-11T09:41:14+02:00
[INFO] Final Memory: 22M/429M
[INFO] ------------------------------------------------------------------------```

**Comment by mabunixda** [comment]
The plugin is building - with or without influxdb-java dependency, the problem occures when the plugin is loaded. 
I gonna modify the pom import scopes.

**Comment by mabunixda** [comment]
@fernandopeinado  The import *;resolution="optional" solved the problem 

Thanks
