### ISSUE TITLE
OkHttpClient creates a large number of threads

### ISSUE THREAD

**Issue by ivanscattergood** [influxdata/influxdb-java#353]
I have found that if I use a OKIOHTTP builder class to set a client timeout I get a number of threads started for a connection pool for each query run. This has been causing us issue in a Tomcat hosted application. 

Looking at the documentation below: 
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

We should use a single OkHttpClient and use the newBuilder() method to share the connection pool. 

I have amended my code locally, and this reduces the connection pool issue. 

Happy to try an put together a test to prove this and offer a fix...

**Comment by fmachado** [comment]
@ivanscattergood could you please provide more details about this issue?
* A single unit test showing your code (are you creating new `OkHttpClient.Builder` or reusing an existing one?);
* What changes have you done to "reduce the connection pool issue"?

If this ticket is not valid anymore, could you please close it? (I'll do it anyway in 1 week if there is no answer from you).

**Comment by ivanscattergood** [comment]
Hi Fernando,

I found that if even if I re-used a OkHttpClient.Builder the number of threads would increase.

However, if I re-used a OkHttpClient (by adding another overloaded method) then there would be an initial increase, created by its first use, then subsequent calls would work ok.

Let me put together a Unit test and make sure it’s still happening with the latest version. I’m tied up for the rest of the week, so I should be able to do it on Monday  20th November.




Ivan Scattergood



Apogee Software



Office:  +44(0)207 0971639
Mobile:  +44 (0)7813 79 7753



Ivan@ApogeeSoftware.co.uk<mailto:Ivan@ApogeeSoftware.co.uk>



http://www.ApogeeSoftware.co.uk<http://www.apogeesoftware.co.uk/>

**Comment by ivanscattergood** [comment]
@fmachado 

Good work! looks like the issue is fixed in the latest version. 

Here are a couple of tests (one for each Overload) that prove the thread count doesn't go up anymore after the initial call
`@Test
	public void testTicket353_noHttpClient() {
		String dbName = "ticket353_" + System.currentTimeMillis();
		int numThreadsBefore = Thread.activeCount();
		InfluxDB influxDBThreads = InfluxDBFactory.connect("http://" + TestUtils.getInfluxIP() + ":" + TestUtils.getInfluxPORT(true), "admin", "admin");
		int numThreadsBeforeCall = Thread.activeCount();
		assertEquals("There should be no extra threads after the connection to influxdb", numThreadsBefore, numThreadsBeforeCall);
		String sql = "SHOW MEASUREMENTS";
		Query queryGetMetric = new Query(sql, dbName);
		QueryResult metric = influxDBThreads.query(queryGetMetric);
		int numThreadsAfterCall = Thread.activeCount();
		assertEquals("There should be an extra thread after the first call to influxdb", numThreadsBeforeCall + 1, numThreadsAfterCall);
		Query queryGetSecondMetric = new Query(sql, dbName);
		QueryResult secondMetric = influxDBThreads.query(queryGetSecondMetric);
		int numThreadsAfterSecondCall = Thread.activeCount();
		assertEquals("There should be no extra threads after the second call to influxdb", numThreadsAfterCall, numThreadsAfterSecondCall);
	}


		@Test
		public void testTicket353_HttpClientBuilder() {
			int readTimeout = 20 ; //If a query takes more than 60 seconds, it will get killed by the DB anyway
			int connectionTimeout = 1 ;

			//From
			//https://github.com/square/okhttp/issues/2738
			OkHttpClient.Builder client = new OkHttpClient.Builder()
					.connectTimeout(connectionTimeout, TimeUnit.SECONDS)
					.readTimeout(readTimeout, TimeUnit.SECONDS)
					.retryOnConnectionFailure(true);



			String dbName = "ticket353_" + System.currentTimeMillis();
			int numThreadsBefore = Thread.activeCount();
			InfluxDB influxDBThreads = InfluxDBFactory.connect("http://" + TestUtils.getInfluxIP() + ":" + TestUtils.getInfluxPORT(true), "admin", "admin", client);
			int numThreadsBeforeCall = Thread.activeCount();
			assertEquals("There should be no extra threads after the connection to influxdb", numThreadsBefore, numThreadsBeforeCall);
			String sql = "SHOW MEASUREMENTS";
			Query queryGetMetric = new Query(sql, dbName);
			QueryResult metric = influxDBThreads.query(queryGetMetric);
			int numThreadsAfterCall = Thread.activeCount();
			assertEquals("There should be an extra thread after the first call to influxdb", numThreadsBeforeCall + 1, numThreadsAfterCall);
			Query queryGetSecondMetric = new Query(sql, dbName);
			QueryResult secondMetric = influxDBThreads.query(queryGetSecondMetric);
			int numThreadsAfterSecondCall = Thread.activeCount();
			assertEquals("There should be no extra threads after the second call to influxdb", numThreadsAfterCall, numThreadsAfterSecondCall);


		}`
