### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/Interceptor

### ISSUE THREAD

**Issue by brunnot** [influxdata/influxdb-java#362]
Hi,

I'm trying to use the Java library with Spring Boot, but I can't solve this problem. This occours when I tried to open connection.
I already tried to put manually all dependencies, but no success.

## Error:

**java.lang.NoClassDefFoundError: okhttp3/Interceptor**

## **pom.xml**

...

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.4.RELEASE</version>
		<relativePath /> 
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.influxdb</groupId>
			<artifactId>influxdb-java</artifactId>
			<version>2.7</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

## Connection Call

```
private InfluxDB connection() {
		InfluxDB influxDB = InfluxDBFactory.connect("http://172.16.12.111:8086", "admin", "xxxx");
		influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);
		
		return influxDB;
	}
```

**Comment by fmachado** [comment]
@brunnot could you please add here the output of ```mvn dependency:tree``` ?

Just a heads up: AFAIK, InfluxDB instances are thread-safe (well, there is a small issue caused by #334 but will only affect you IIF you are using UDP). Anyway, my point is: you can reuse the same connection instead of creating a new.
