### ISSUE TITLE
Doesn't support urls not under '/'

### ISSUE THREAD

**Issue by n3g** [influxdata/influxdb-java#365]
Hi,
I'm using a JMX wrapper [jmxtrans](https://github.com/jmxtrans/jmxtrans) that uses this library to push data to influx.
Unfortunately my influxdb is not mapped under '/', so the URL is something like `https://xyz.com/influx/`. I tracked down the issue until this library, which appears to use all URLs directly under '/'.
Example in [InfluxDBService.java](https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBService.java) line 40:
```
  @GET("/query")
  public Call<QueryResult> query(@Query(U) String username, @Query(P) String password, @Query(DB) String db,
      @Query(EPOCH) String epoch, @Query(value = Q, encoded = true) String query);
```
This causes the library to fail because it defaults to '/' urls (which don't exist in my case):

```
java.lang.RuntimeException: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /query was not found on this server.</p>
</body></html>
```
I couldn't find a way around this.
Thanks for any help!

**Comment by vicctor** [comment]
I fixed this issue for my own purposes in my fork https://github.com/vicctor/influxdb-java
Pull request is set to influxdada. I'm not sure if I fixed all possible cases, at least all what I need works now. My problem was that I wish to put the influxdb behind nginx, so all my services will be accessible over one TCP  port.
