### ISSUE TITLE
differentiate between client vs. server errors in InfluxDbException

### ISSUE THREAD

**Issue by jack-kerouac** [influxdata/influxdb-java#375]
When dealing with an `InfluxDbException`, it would be useful to know whether the HTTP error code was 4xx, indicating a problem with the client, e.g. an invalid query, or whether it was a 5xx error, indicating a problem with the server.

Currently, these cases cannot be differentiated. This is important for us, because we are using Hystrix and would only like to count 5xx failures against the metrics for the circuit breaker.

**Comment by majst01** [comment]
OK, this would require some refactoring of the code talking to influxdb. If you have some ideas howto differentiate, your are welcome to show this in a PR.

**Comment by dubsky** [comment]
This has been already done in #410. See InfluxDBExcetion.isRetryWorth()
