### ISSUE TITLE
java.lang.StackOverflowError:okhttp3

### ISSUE THREAD

**Issue by bbamber** [influxdata/influxdb-java#379]
Single instance influxdb connections query a large amount of data, memory explosion occurs, when I try to establish a new query influxdb query data each time, or memory overflow occurs.
```
java.lang.StackOverflowError
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:48)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144)
```

**Comment by majst01** [comment]
At least version of influxdb-java and the code which triggers this is required.

**Comment by bbamber** [comment]
I'm a new programmer, and I don't know much about influxdb。

- The dependency information of POM is:
`<dependency>
            <groupId>org.influxdb</groupId>
            <artifactId>influxdb-java</artifactId>
            <version>2.7</version>
        </dependency>`

- The influxdb I'm using is version 1.3

- Here is the Java code I wrote:
`public void getData(){

        StringBuffer command = new StringBuffer();
        ..........

		OkHttpClient.Builder builder = new OkHttpClient.Builder().readTimeout(100, TimeUnit.SECONDS);
        InfluxDB influxDB_query = InfluxDBFactory.connect("http://192.168.1.86:8086", "XXX", "XXX",builder);
        influxDB_query.setDatabase(dbName);
        influxDB_query.enableGzip();
		
        QueryResult qr = influxDB_query.query(new Query(command.toString(), dbName),TimeUnit.MILLISECONDS);
        List<QueryResult.Result> res = qr.getResults();

        if(res.get(0).getSeries() != null) {
            QueryResult.Series series = res.get(0).getSeries().get(0);
            List<List<Object>> values = series.getValues();
            ..........
        }
        influxDB_query.close();
		
    }`

**Comment by fmachado** [comment]
@bbamber there are a couple of things that I would like to suggest you:
* It is "safe" to reuse your `InfluxDB influxDB_query` object (i.e. instead of creating an object every time `getData()` is called, you may do it only once);
* Instead of iterating on array lists, you could declare a class and annotate it (like you do when you are using EclipseLink or Hibernate). Check https://github.com/influxdata/influxdb-java#queryresult-mapper-to-pojo-version-27-required for more information.

Now for the specific issue reported here, I cannot reproduce it. Could you please enable a more verbose logging by adding `influxDB_query.setLogLevel(LogLevel.FULL);` after `influxDB_query.enableGzip();` ? Also, are you behind some kind of HTTP proxy?
