### ISSUE TITLE
How to create connection pool for influxDb

### ISSUE THREAD

**Issue by bilalsha** [influxdata/influxdb-java#380]
Can SomeOne guide me about connection pool for influxDb? I need to know If I need to implement it or it already exists?

**Comment by majst01** [comment]
Hi,

there is no need for a connection pool because the connection is made via http which is stateless.

**Comment by Cyrus8** [comment]
Can't doing a connection pool at the InfluxDB client level improve performance ? 

I tried using 2 InfluxDB client in the same code, writing 10 000 points from one client then 10 000 points from the other (from the same timeseries) and it's arround 2 times faster for me than writting all points from the same client (both client use batch size of 10 000).

**Comment by majst01** [comment]
Can you please show a usage example where we can see how exactly you gained twice the performance, so  we can eventually see where we have room for improvements.

**Comment by majst01** [comment]
Need to add the fact that you can pass a httpclient instance to `InfluxDBFactory.connect` this client can handle the stateful connection.

**Comment by Cyrus8** [comment]
Maybe I am doing something wrong in the first place for a such use to improve performance but this is how I am instanciating the clients : 
With numClients = 2 I gained around twice the performance, with more client I gained around 2.5 the performance.

```		
for (int i = 0; i < numClients; i++) {
	InfluxDB client = InfluxDBFactory.connect(fullUrl, user, password);
	client.enableBatch(BatchOptions.DEFAULTS.actions(10000).flushDuration(200));
	clients.add(client);
}
```

I am then simply taking a different client each time I need : 

```
public InfluxDB getClient() {
	return (clients.get(current++ % numClients));
}
```

And this is pseudo code of how I insert into influx, I am getting a new client every 10000 points. (not even sure if this has an impact) I also tried to manually flush before switching clients but insertion time went slower.

```
int max = pool.batchSize;
int count = 0;
InfluxDB influxclient = pool.getClient();
while (line != null) {
	count++;
	if (count == max) {
		count = 1;
		influxclient = pool.getClient();
	}
        // Some other code to build the point
        Point influxPoint = Point.measurement(measurement).time(ts, tu).fields(values).tag(tags).build();
	influxclient.write(database, "autogen", influxPoint);
}
```

**Comment by chabapok** [comment]
> there is no need for a connection pool because the connection is made via http which is stateless

Connection pool saves query time because it persist tcp-connections in the ESTABLISHED state. Without pool each new InfluxDb instance needs to pass tcp-handshake procedure (sending SYN, waiting to receive SYN+ACK, sending ACK). This procedure usually takes 20~40 microsecnods (depends on hardware), even if influxd daemon worked at same server. If we are make http request  to remote influxd daemon, it may takes more time.

In case the SYN+ACK packet is lost by the network, tcp connection process may be very long (depend on OS and tcp stack configuration, but may take tens of seconds). Usually, the TCP retransmission timeout starts at 3 seconds, but if the client tries to resend after a timeout and still receives no answer, it doubles the wait to 6 s.

So, connection pool is useful.

**Comment by majst01** [comment]
@chabapok you are right, if the distance/latency between the client and the database is significant, a connectionpool will help.

the underlaying http client library in use does support connectionpool:
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-connection-pool/

If someone is willing to show how we can integrate into influxdb-java i am happy to review any PR´s.

**Comment by vatechie** [comment]
Hi @majst01 
Is the connection pool functionality has been added in influxdb-java API.

**Comment by majst01** [comment]
no not yet, as far as i can tell there is no MR open for this.

**Comment by teekcode** [comment]
I think the underlaying http client library `okhttp` already init a connection pool. In `influxdb-java` it's init at
`    return new InfluxDBImpl(url, username, password, new OkHttpClient.Builder());
`

**Comment by rajm3180** [comment]
@majst01 @teekcode  What should be the ideal okhttp client configuration. And will this builder be initialized each time I create influx db connection? or Will this work on the concept of bean initialization. Thanks a lot in advance
        
       final OkHttpClient.Builder http = new OkHttpClient.Builder();
        Dispatcher dispatcher = new Dispatcher();
        dispatcher.setMaxRequests(2); dispatcher.setMaxRequestsPerHost(2);
        http.dispatcher(dispatcher);
        http.connectionPool(new ConnectionPool(threads, 5, TimeUnit.MINUTES));

**Comment by user9891365** [comment]
is the connection pool functionality added for Influxdb-java (Influxdb 2x)
