### ISSUE TITLE
loop write single point, enable batch, always lost datas 

### ISSUE THREAD

**Issue by king116116** [influxdata/influxdb-java#382]
I'm doing the database migration, from sql server to influxdb, about 200 thousand records, loop write to influxdb with batch write, my batch setting is influxDB.enableBatch(1000, 100, TimeUnit.MILLISECONDS);
I tried to load all records into a list, then batch write to influxdb once, but I found, when I count(*) from influxdb, some reads lost.
Then I done another test, batch write with 1000 records, then flush use influxDB.disableBatch(), loop done the write, the same situation.
At last, use influxDB.write(batchPoints) done the same test,  the same situation, I think this is a issue, maybe is a influxdb issue,  hope your help, thanks.

**Comment by fmachado** [comment]
@king116116 my first guess is that your problem is related with duplicated points. Please, [check this link](https://docs.influxdata.com/influxdb/v1.3/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points) to see how InfluxDB handle duplicated points.

If you are sure this is not your case, I would suggest to split your migration process into multiple steps (e.g. load 50k and check, load more 50k and check again and so on...) until you narrow down the exact moment where you start missing data.

**Comment by king116116** [comment]
I tried to write 10k once a time, then count the measurement, write down the count in my notepad, drop the measurement, do the batch write again, the total count in my sql server is 110710, blow is count from influxdb, ten times:
110700,
110709,
110698,
110709,
110700,
110708,
110691,
110703,
110700,
110693
It seams like a random data missing, I think this is a influxdb issue, I can debug the code,  found that, before invoke influxDBService.writePoints, the batchPoints.size() is correct, but write to influxdb, the data radom missing,below is my java code to do the batch write, 10k once a time.

if(!influxDB.isBatchEnabled()){
	influxDB.enableBatch(5000, 500, TimeUnit.MILLISECONDS);
}
for (int i = 0; i < currentCount; i++) {
    Point point = Point
				.measurement(measurement)
				.time(time, TimeUnit.MILLISECONDS)
				.fields(fields)
				.tag(tags)
				.build();
    influxDB.write(database,"autogen",point);
}
if(influxDB.isBatchEnabled()){
	influxDB.disableBatch();
}

By the way, I'm using influxdb 1.4.1

**Comment by fmachado** [comment]
> - I would suggest to split your migration process into multiple steps (e.g. load 50k and check, load more 50k and check again and so on...) until you narrow down the exact moment where you start missing data.
- Could you please disable the "batch mode" and do it again?
- How are you counting how many points exists in one measurement?
- One last thing (and I know it's a long shot) but is there any chance that you are performing the count while data is still being sent to InfluxDB?

**Comment by king116116** [comment]
I disabled batch mode, write the point each time. I have done the testing for 3 times, count(*) from influxdb, the total count is 110694,11710,11709, the second time is correct, the other 2 times still missing datas.
My system is windows 10, here is how to count the data record from measurement:
First, start the java application, then start the command window to login influxdb, count data manually, "select count(*) from m_data" until the number not changed, drop the measurement and start the test again.

**Comment by majst01** [comment]
But still influxdb will only write the last point if 2 or more have the same timestamp given. Im sure that your code is able to create more than one point per millisecond, can you try to write in Nanos instead ?

**Comment by fmachado** [comment]
@king116116 is this still an issue? If so then please reopen it with more information about what happened when you used `ns` instead of `ms`.

**Comment by gitgeorge** [comment]
Hi @fmachado ,
Having a similar issue with what you guys are/were discussing sometime back ie data loss everytime am writing to influxdb, Is this the only reason why this would happen as explained here https://bit.ly/2EGz0D9

**Comment by fmachado** [comment]
@gitgeorge AFAIK yes

**Comment by pKrivic23** [comment]
I had the same issue, and I ensured that each timestamp is different but the problem remained each time. This is the code I used:
`  
for(int k=0;k<100000;k++) {

	    	//saving data to influxdb

	    	Point point = Point.measurement("electricityReading")
	        		  .time(System.currentTimeMillis()-k, TimeUnit.MILLISECONDS)
	        		  .tag("serialNumber", Long.toString(er.getSerialNumber()))
	        		  .addField("currentState", k)
	        		  .addField("workingEnergy", er.getWorkingEnergy())
	        		  .addField("fallowEnergyPositive", er.getFallowEnergyPositive())
	        		  .addField("fallowEnergyNegative", er.getFallowEnergyNegative())
	        		  .addField("maxPower", er.getMaxPower())
	        		  .build(); 
	    		influxDB.write(point);
	    		try {
					Thread.sleep(5);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
    }`
I have run each test with putting thread to sleep for 5 ms, and without putting it to sleep (commenting this part out). I used 100, 1000, 10000, 100000 as number of iterations and the results were always the same - with putting thread to sleep there would be no data losses, and without it data loss would happen...
So delays resolve losses but it is significantly slower :(
Do you have any other suggestions maybe?

**Comment by majst01** [comment]
How do you check that all points are written ? In the example you only write the points and do not read them. I also can not see how you create the *influxdb* instance, is batching enable ?

Greetings

**Comment by pKrivic23** [comment]
batching is enabledwith following command:  
influxDB.enableBatch(BatchOptions.DEFAULTS);

I check it directly in influxdb bash, after the test is finished running (I do it with following command: select COUNT(*) from electricityReading)

**Comment by majst01** [comment]
But you have to wait, or flush in your code after all writes, otherwise the written points will still be in memory of the client.

**Comment by pKrivic23** [comment]
Ok, so I added the line:
influxDB.flush();
after the for loop, and with 100 points to write, only 98 are written.
Then I added the same line after each write (below the line influxDB.write(point);) and it got all 100 point written. But with 1000 data points to write, there is already some data loss (only 989 are written). So flushing cannot assure me in a scenario where I cannot have any data losses. I am just not sure why 5 ms delay helps, and it creates significant time overhead, but if I dont want to have any data losses it seems that it will be a price that I must accept...
If you have any other suggestions I can try them out, so we can resolve this strange behaviour..

**Comment by fmachado** [comment]
Why do you think ‘System.currentTimeMillis()-k’ will guarantee you an
unique timestamp? I highly suggest you to create a small java program with
this isolated piece of code and evaluate what happens.

**Comment by pKrivic23** [comment]
You were right, so I captured a single System.currentTimeMillis() moment before the for loop and used it to be sure each timestamp is unique, and after it there are no data losses.

Thanks for your help :)

**Comment by majst01** [comment]
This type of irritation happens quite often, but i dunno howto avoid it for newcomers, any ideas ?

**Comment by pKrivic23** [comment]
Well there is nothing that could be done from your side, since it was my bug. So for the newcomers you just ensure that timestamp is unique and there wont be any data losses. It works also without flushing, so it is really fast and efficient. The code I used for testing now is the following:
`	    	
long startTime = System.currentTimeMillis();
	    	
	    	for(int k=0;k<100000;k++) {
	    	//saving data to influxdb
	    	Point point = Point.measurement("electricityReading")
	    			  .time(startTime-k, TimeUnit.MILLISECONDS)
	        		  .tag("serialNumber", Long.toString(er.getSerialNumber()))
	        		  .addField("currentState", k)
	        		  .addField("workingEnergy", er.getWorkingEnergy())
	        		  .addField("fallowEnergyPositive", er.getFallowEnergyPositive())
	        		  .addField("fallowEnergyNegative", er.getFallowEnergyNegative())
	        		  .addField("maxPower", er.getMaxPower())
	        		  .build(); 
	    		//log.info(""+processed++);
	    		influxDB.write(point);
    }`

And it works perfectly fine with million measurements (under 20 secs to store the all in my case)

**Comment by gitgeorge** [comment]
Hello guys,

I know I might be coming in a bit late, but adding some sleep time within the loop helps.I experienced the same issue sometime back.

**Comment by majst01** [comment]
No sleep will only ensure all possible points are written (if sleep is longer than batch duration), but if you add points with identical time(s) only the first of them will be written.
