### ISSUE TITLE
no data written?

### ISSUE THREAD

**Issue by biohazardxxx** [influxdata/influxdb-java#383]
Somehow this code does not write anything into the DB but also doesn't give any error.
Any clue what is wrong?
```
InfluxDB influxDB = InfluxDBFactory.connect(cfg.url());
		influxDB.setDatabase(cfg.dbname());
		// Flush every 2000 Points, at least every 100ms
		System.out.println("CPU: " + cpu);
		influxDB.write(Point.measurement("cpu")
		    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
		    .tag("host",cfg.hostname())
		    .tag("dc",cfg.dc())
		    .addField("PercentProcessingUnitUsed", cpu)
		    //.addField("JobsInSystem", jobs)
		    //.addField("CurrUnprotStorageUsed", unprotStore)
		    //.addField("PercentSystemASPUsed", aspUsed)
		    .build());
		System.out.println("Wrote to influxDB");
		Query query = new Query("SELECT PercentProcessingUnitUsed FROM cpu", cfg.dbname());
		QueryResult result = influxDB.query(query);
		System.out.println(result.getResults().toString());
```

This is the output:

> CPU: 61.2
> Wrote to influxDB
> [Result [series=null, error=null]]

**Comment by fmachado** [comment]
@biohazardxxx I cannot reproduce your issue. Are you enabling the match mode (`influxDB.enableBatch`) but forgot to add the respective line to your sample above?

Here is my code:
```Java
/**
 * Test for ticket #383
 */
@Test
public void testTicket383() {
	String dbName = "ticket383_" + System.currentTimeMillis();
	influxDB.createDatabase(dbName);
	influxDB.setDatabase(dbName);
	//influxDB.setLogLevel(LogLevel.FULL);

	influxDB.write(Point.measurement("cpu")
	        .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
	        .tag("host", "foo")
	        .tag("dc", "bar")
	        .addField("PercentProcessingUnitUsed", 61.2d)
	        .build());

	Query query = new Query("SELECT PercentProcessingUnitUsed FROM cpu", dbName);
	QueryResult result = influxDB.query(query);
	System.out.println(result);
	
	influxDB.deleteDatabase(dbName);
	//influxDB.setLogLevel(LogLevel.NONE);
}
```

**Comment by biohazardxxx** [comment]
No I don't have it. But I tried to add enableBatch & flush with same result
that nothing is written. Any thing that could be wrong on server side? Data
collection with telegraf works there.

Am 20.11.2017 01:30 schrieb "Fernando Machado" <notifications@github.com>:

**Comment by biohazardxxx** [comment]
Tried your example code and it worked. I then replaced step by step with my variables and it turns out is tops working when I use the existing DB. Checking the DB I belive it is a bad retention policy:

> name     duration  shardGroupDuration replicaN default
> ----     --------  ------------------ -------- -------
> autogen  0s        168h0m0s           1        false
> 12_weeks 2016h0m0s 24h0m0s            1        true

I'll check further on that. However this lib is working super. Thanks!
