### ISSUE TITLE
Async response

### ISSUE THREAD

**Issue by gianarb** [influxdata/influxdb-java#386]
Hello! 

I am working on integration between Zipkin and InfluxDB with @goller  these days.
At the moment we are using this library. We would like to have back the async response other than the sync one as it happens now.

You can see why here in this comment

https://github.com/openzipkin/zipkin/pull/1781#issuecomment-344807126

What do you think about exposing this capability maybe creating a sync and async adapter in the client itself?

Thanks a lot

**Comment by majst01** [comment]
Nice to see the integration into zipkin !
I'm happy to review PRs.

**Comment by gianarb** [comment]
Please do @majst01 I am not a java dev and I am doing my best to look like one! :D

**Comment by majst01** [comment]
I have not spare time actuall to invest a lot into this library, sorry.

**Comment by timhallinflux** [comment]
@ivankudibal -- is this something your team can work on?

**Comment by dubsky** [comment]
@gianarb -- Do you have batching enabled ?  When you do so, influxdb client will collect the data points into a buffer and it will flush it automatically in a separate thread when certain properties of the entries in the buffer will be met (count, age).

For queries there are methods that are asynchronous:

InfluxDb.java:
public void query(final Query query, final Consumer<QueryResult> onSuccess, final Consumer<Throwable> onFailure);

**Comment by fmachado** [comment]
@gianarb I added some comments directly to the mentioned zipkin PR.

**Comment by gianarb** [comment]
I didn't know about this method. I will have a look. Thanks
```
public void query(final Query query, final Consumer onSuccess, final Consumer onFailure);
```
We spoke about batch writing but it's something that zipkin can manage by itself and I am not sure if having 2 resource managers will be good. At the moment we decided to avoid baching.

Thanks @fmachado !!
