### ISSUE TITLE
Not able to insert object type into the influx using influxdb-java API

### ISSUE THREAD

**Issue by Vish17agr** [influxdata/influxdb-java#387]
I am inserting the data into the influx using java API.

I am creating a point to insert the data into the influx but i don't know what is my data type of the object, as i would be passing a result set object and based my result set a point will be created and data will be inserted into the influx. 

point = Point.measurement(oraObj.getCacheName())	// measurement name same as table name
		.time(System.currentTimeMillis(),TimeUnit.MILLISECONDS)
		.addField(attributes[0],rsObj.getString(attributes[0]))
		.tag("MeasurementTag", "MeasurementTagValue") 
		.build();

**I can only insert the field values as string as there is no overloaded function as below
addField(String field, Object value) in builder.**

Is there any way to insert the object type filed value into the influx.

**Comment by fmachado** [comment]
@Vish17agr InfluxDB only supports the following data types:
- Float
- Integer
- String
- Boolean
- Timestamp

Source: https://docs.influxdata.com/influxdb/v1.3/write_protocols/line_protocol_reference/#data-types

influxdb-java client does not support data serialization and you have to do it by yourself (e.g. convert to JSON and store as string or get the base64 representation and store as string (which I don't recommend)).

**Comment by Vish17agr** [comment]
Thanks for your input 👍  @fmachado

**Comment by saurabh275** [comment]
@Vish17agr
 does it resolved your issue as i am stuck in similar kind of issue wanna store simple "hello world" kind of  mqtt broker message in influx db using java
