### ISSUE TITLE
Is there any way to write asynchronously?

### ISSUE THREAD

**Issue by tttMelody** [influxdata/influxdb-java#388]
Current use Call#execute() will synchronously send the request and return its response.

**Comment by gianarb** [comment]
Hello @tttMelody !

As you can see in the README.md you can able batching in this way:

```
// Flush every 2000 Points, at least every 100ms
influxDB.enableBatch(2000, 100, TimeUnit.MILLISECONDS);
```

**Comment by tttMelody** [comment]
Hi @gianarb  
Thank a lot. I go through the code and found it was lay down there clearly😄! BatchProcessor#put().

It would be much nicer if it can be described in this comment explicitly,  may like:"Flush every 2000 Points, at least every 100ms, asynchronously".There are some mention about this in README, but it will be more clear and can catch programers's eyes in comment, in my opinion.
Thank.
😄😄😄

**Comment by tttMelody** [comment]
Another question is, in README:
`Note that the batching functionality creates an internal thread pool that needs to be shutdown explicitly as part of a graceful application shut-down, or the application will not shut down properly. To do so simply call: influxDB.close()`

but in the code I can not see any close calling?

Hoping for you advise.

**Comment by gianarb** [comment]
Well, I think it's not there because it really depends on how and where do you track application shutdown. But in general you can read this:

https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread-
and you should call `influxDB.close()` when your app detect the shutdown hook.

**Comment by tttMelody** [comment]
I got, thank you.
