### ISSUE TITLE
Support for MessagePack

### ISSUE THREAD

**Issue by dvanwest** [influxdata/influxdb-java#389]
Is it possible to update the InfluxDB Java API to allow query data to be returned in MessagePack format?  This format is supported. when reading, in the new 1.4 version of InfluxDB.

**Comment by majst01** [comment]
we use retrofit for the backend communication and therefore a converter for messagepack is needed.
Luckily such a converter exists:

https://github.com/komamitsu/retrofit-converter-msgpack
