### ISSUE TITLE
returned points limit to 10k

### ISSUE THREAD

**Issue by qiaojialin** [influxdata/influxdb-java#394]
I am using Influxdbv1.2.0 and influxdb-java v2.7. When I executed a query, there are only 10000 points returned. I want to get the whole  result. So I add a "limit 0"  but it doesn't work. Is it normal? 

refer:  https://github.com/influxdata/influxdb/issues/61

**Comment by fmachado** [comment]
@qiaojialin This is the default configuration for InfluxDB 1.2.

> In versions 1.2.0 and 1.2.1, the max-row-limit option is set to 10,000 by default. (...) In versions 1.2.2+, max-row-limit is set to 0 by default and allows an unlimited number of returned rows.

-- Source: https://docs.influxdata.com/influxdb/v1.2/administration/config/#max-row-limit-0

Check the InfluxDB docs for more information about how to configure it.
