### ISSUE TITLE
Too many InfluxDB.enableBatch(...) methods

### ISSUE THREAD

**Issue by dubsky** [influxdata/influxdb-java#396]
When working on #397 I discovered the following:

There are multiple methods to enable batching right now.

* enableBatch(actions, flushDuration, flushDurationTimeUnit);
* enableBatch(actions, flushDuration, flushDurationTimeUnit, threadFactory);
* enableBatch(actions, flushDuration, flushDurationTimeUnit,  threadFactory, exceptionHandler);

The problem is that with each added parameter that affects batching we need to add an extra method with increasing number of parameters. (Even better a couple of methods based on the needs of the user to override certain combinations of default parameters only). 

Adding few more parameters would make the use of the API difficult and also the implementation would not be very nice.

As a solution I propose to add the following method:

``` java
enableBatch(BatchOptions options)
```
where options would hold all the configuration properties.
This is how it would be used:

```java
influxDB.enableBatch(BatchOptions.DEFAULT.actions(1000).flushDuration(10000))
```
This way it would be possible to set all the existing parameters and override only the values the user needs to.

**Comment by fmachado** [comment]
For me it's fine. Could you please deprecate the old methods that are not using `BatchOptions` and create a PR? @majst01 is this ok for you?
