### ISSUE TITLE
Influx Query Client - connection pooling

### ISSUE THREAD

**Issue by idobarash** [influxdata/influxdb-java#405]
Hello, 

On load, My client returns connection time out.

` Error fetching from influx: java.net.SocketTimeoutException: timeout `

I searched if I can define a pool, or increase http connections for the DB.
Found nothing.

How can I fix this?

Regards, Ido

**Comment by turetsky** [comment]
Hello!

You can try configure an instance of `okhttp3.OkHttpClient.Builder` (there are such methods: connectTimeout, writeTimeout, readTimeout) and pass it into `InfluxDBFactory.connect`.

BR, Andrey K.
