### ISSUE TITLE
Write int but read double

### ISSUE THREAD

**Issue by qiaojialin** [influxdata/influxdb-java#406]
I write an int field but read double, is this normal?

<img width="367" alt="2018-01-03 7 37 56" src="https://user-images.githubusercontent.com/7240743/34519173-be85a7fe-f0bd-11e7-82ac-5858709fb29d.png">

<img width="360" alt="2018-01-03 7 37 42" src="https://user-images.githubusercontent.com/7240743/34519175-bfe722c6-f0bd-11e7-8758-68f66d6c2126.png">

**Comment by fmachado** [comment]
@qiaojialin Yes. For more information, check this [comment](https://github.com/influxdata/influxdb-java/issues/153#issuecomment-259681987) from another user who reported the same issue.
