### ISSUE TITLE
.Jar file anyone

### ISSUE THREAD

**Issue by powertronglobal** [influxdata/influxdb-java#411]
Anyone have a compiled Jar file?

**Comment by irufus** [comment]
There's docker support and it can be build by using Maven.

**Comment by fmachado** [comment]
@powertronglobal if you want to build your own .jar using the most recent source-code, follow these steps:

1) Clone the project repository into your local machine:
`git clone https://github.com/influxdata/influxdb-java.git`
2) Build the .JAR file using the Maven command-line:
`
cd influxdb-java/
mvn package -DskipTests
`
3) Check the _target_ folder. You will find the following files:
  - influxdb-java-2.11-SNAPSHOT.jar
  - influxdb-java-2.11-SNAPSHOT-javadoc.jar
  - influxdb-java-2.11-SNAPSHOT-sources.jar

**Comment by ashuptdr** [comment]
can we have influx data or influx db executables packages or files like prometheus and atlas:
e.g.
https://github.com/prometheus/prometheus/releases/download/v2.5.0/prometheus-2.5.0.linux-amd64.tar.gz

https://github.com/Netflix/atlas/releases/download/v1.5.3/atlas-1.5.3-standalone.jar

**Comment by majst01** [comment]
You can always pull them from:

https://mvnrepository.com/artifact/org.influxdb/influxdb-java/2.14

**Comment by ashuptdr** [comment]
@majst01 provided link is only for maven dependency. i want github url for executables packages/jar or files.

**Comment by majst01** [comment]
for me:

wget http://central.maven.org/maven2/org/influxdb/influxdb-java/2.14/influxdb-java-2.14.jar works
