### ISSUE TITLE
"error":"partial write:\nunable to parse

### ISSUE THREAD

**Issue by qiaojialin** [influxdata/influxdb-java#415]
I got a partial write error in batch write.

```
{"error":"partial write:
unable to parse 'meas1,protocolId=8193,transtype=0,wfId=632864,wtId=632864801 METT_Hum_Ra_F32_layer1=-8.307000160217285,METT_WSpd_Ra_F32_layer1_AVG_': invalid field format
unable to parse '=651.323974609375,METT_WSpd_Ra_F32_layer2_AVG_': missing tag value
unable to parse '=0.08500000089406967,METT_Wdir_Ra_F32_layer5max=30.957000732421875,METT_Wdir_Ra_F32_layer5min=31.631000518798828 1517277674293000000': invalid field format
```

the insert statement of this point should be 

```
insert meas1,protocolId=8193,transtype=0,wfId=632864,wtId=632864801 METT_Hum_Ra_F32_layer1=-8.307000160217285,METT_WSpd_Ra_F32_layer1_AVG_=651.323974609375,METT_WSpd_Ra_F32_layer2_AVG_=0.08500000089406967,METT_Wdir_Ra_F32_layer5max=30.957000732421875,METT_Wdir_Ra_F32_layer5min=31.631000518798828 1517277674293000000
```

**Comment by fmachado** [comment]
@qiaojialin my guess (and this is a long shot) is that you have a `\n` character at the end of the fields `METT_WSpd_Ra_F32_layer1_AVG_` and `METT_WSpd_Ra_F32_layer2_AVG_` and this is breaking the current implementation responsible for creating a single "line"[1].

[1] https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/

**Comment by qiaojialin** [comment]
Thank you!  I found the '\n' character at the end of these fields.

![image](https://user-images.githubusercontent.com/7240743/35657791-49cc23e2-0739-11e8-9940-6c899c03fb81.png)
