### ISSUE TITLE
Request tags value is null

### ISSUE THREAD

**Issue by ArthasGong** [influxdata/influxdb-java#417]
Dears,
  I met with a problem on InfluxDB v 1.2.4. And I used influxdb-java client v2.8.
I set a point like this:  Insert payment,device=mobile,method=credit,product=Notepad billed=33,licenses=3
So the tag keys are: device,method,product
![tagkeys](https://user-images.githubusercontent.com/4346774/35671222-a8d46250-0775-11e8-8772-714f57822af7.jpg)

Now, I requested the db like this:
http://localhost:8086/query?u={userName}&p={password}&db=mydb&q=select+*+from+payment
But the response body doesn't contain tags
![tagkeys2](https://user-images.githubusercontent.com/4346774/35671286-e366343e-0775-11e8-86cd-d036faa9b829.jpg)

And this is my debugging info:
![tagkeys3](https://user-images.githubusercontent.com/4346774/35671440-65d17a6e-0776-11e8-943b-6460e0708d2c.jpg)

Has anyone got the idea?

Thx a lot!

**Comment by thedoctor** [comment]
Getting the same issue with influxdb v1.4.2

**Comment by mschwore** [comment]
You have to use a group by clause to have influxdb return tags to you. For instance, if your query was instead:

select * from payments group by *

You should see your device, method and product show up as tags. For each tag set in your group by, you would get a series returned from influxdb.

Check out the influxdb docs as well https://docs.influxdata.com/influxdb/v1.4/query_language/data_exploration/#the-group-by-clause

**Comment by phantomdrake077** [comment]
Thanks that worked.

**Comment by thedoctor** [comment]
@mschwore Fair point, the query response doesn't expose which columns are tags. Nevertheless, I think you can probably see how this could cause confusion. 
I think a javadoc on the result class would clear this up for people.
