### ISSUE TITLE
InfluxDBResultMapper.toPOJO(...) returns 0 for NULL field values

### ISSUE THREAD

**Issue by michailx** [influxdata/influxdb-java#431]
Dear community,

We have installed influxDB on an Ubuntu 16.04.4 LTS server.

```
$ uname -a
Linux claire 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ /usr/bin/influxd version
InfluxDB v1.4.3 (git: 1.4 60d27e6995558f38a39e90b35a92cbac080310a3)
```

We are performing the following query:

`SELECT sum("bits") AS bits, sum("packets") AS packets, sum("drops") AS drops FROM "load" WHERE device_id='of:0000000000000001' AND "time" > now()-40s GROUP BY time(1s),device_id fill(null)`

and use InfluxDBResultMapper.toPOJO(...) to map the QueryResult to our POJO:

```
@Measurement(name = "load")
public class LoadMetric {

    @Column(name = "time")
    private Instant time;

    @Column(name = "device_id", tag = true)
    private String deviceId;

    @Column(name = "port_id", tag = true)
    private String portId;

    @Column(name = "bits")
    private long bits;

    @Column(name = "packets")
    private long packets;

    @Column(name = "drops")
    private long drops; 
```

Problem definition:
When executing the query using the influxDB shell (version 1.4.3), some fields have NULL value.
However, when executing the same query using influxdb-java, these NULL values are returned as 0 instead.

Has anybody come across this problem before?

**Comment by fmachado** [comment]
@michailx you have to declare the fields `bits`, `packets` and `drops` as `Long` instead of `long`.

**Comment by michailx** [comment]
Thank you @fmachado ; this resolved the issue indeed.
Much appreciated for the prompt help!
