### ISSUE TITLE
Create a stress test suite for Enterprise InfluxDB and Open source InfluxDB 

### ISSUE THREAD

**Issue by lxhoan** [influxdata/influxdb-java#436]
We need a more thorough stress test suite against the Enterprise version and OSS version. The current 
PerformanceTests stresses DB by the number of data point. The new stress test suite should consider more on the number of :
   + measurements
   + tag sets
   + tag set(series)
   + fields
   + points

(Inspired by [inch](https://github.com/influxdata/inch))

**Comment by ivankudibal** [comment]
Done. See https://github.com/influxdata/inch-java

**Comment by majst01** [comment]
Hi @ivankudibal 
https://github.com/influxdata/inch-java is not public visible, why is this the case ?
