### ISSUE TITLE
how to make the client to use log4j?

### ISSUE THREAD

**Issue by IdanFridman** [influxdata/influxdb-java#443]
Our app's using log4j and slf4j. Seems like influxdb-java client writing logs to stderr output.

```
INFO: <-- 204 No Content http://influxdb.qa.com:8086/write?u=admin&p=devadmin&db=winner&precision=n&consistency=one (3ms, unknown-length body)
Apr 24, 2018 11:42:06 AM okhttp3.internal.platform.Platform log
INFO: --> POST http://influxdb.qa.com:8086/write?u=admin&p=devadmin&db=wallet&precision=n&consistency=one http/1.1 (10694-byte body)
Apr 24, 2018 11:42:06 AM okhttp3.internal.platform.Platform log
```

Any idea how to make those logs to be written to our logs using our log4j property ?

thanks.

**Comment by majst01** [comment]
I dont want to add a dependency to a logging framework, i would vote for a framework agnostic way to pass a logger instance

**Comment by fmachado** [comment]
> (...) we wont transfer all our services (which using influx-java-client) to JUL from log4j (...)
I didn't say that. I said "you have to find a way to route JUL to Log4J". If the link that I provided does not work then you will have to find another way (jul-to-slf4j maybe?)

**Comment by IdanFridman** [comment]
@fernandopeinado tried few.. no idea how to nail this:(

**Comment by IdanFridman** [comment]
@fmachado thanks. it worked. do you want me to resolve this issue? as it's work around

**Comment by majst01** [comment]
I think we should add this to the documentation, this is a very useful hint, thanks @fmachado .

@IdanFridman Do you mind adding some doc to README.md from a user perspective ?

**Comment by IdanFridman** [comment]
never done this before. want to guide me? i can do that.

**Comment by majst01** [comment]
Hi @IdanFridman 
Just add a section "Logging" to README.md and add a example howto change the logging the way you did, maybe the explanation @fmachado created is a good starting point.
