### ISSUE TITLE
Garbage characters exist in synchronous writing results 

### ISSUE THREAD

**Issue by KaiboFu** [influxdata/influxdb-java#461]
Hi  all,

First of all thanks for your great work on InfluxDB implementation for java.  It is really working quite well in my **1.0.2** environment.

But recent days, I just came across one problem: garbage characters existing in synchronous writing results. Just as the following figure shows:
![image](https://user-images.githubusercontent.com/10770807/41333415-47fc2114-6f14-11e8-9a0c-fe3f075ed97e.png)

Also, when I want to another tag values for "paltform" with such a command: SHOW TAG VALUES FROM "rec-rpt-groupby-platform-scene" WITH KEY = "platform" . There is also a strange result, as the following figure just shows some part:
![image](https://user-images.githubusercontent.com/10770807/41333599-f89230a4-6f14-11e8-9053-b89ad8436d38.png)
We can see that the platform 'an' just appear three times. It really should not ! 

I really do not know how to deal with such problems. Is there anyone could help me?

**Comment by KaiboFu** [comment]
@majst01 @jiafu1115  Would you help me ?

**Comment by asashour** [comment]
Can you please provider a complete case, in which the code for writing and reading is shown? So others can reproduce the issue.
