### ISSUE TITLE
Use Jackson (instead of Moshi) as the JSON parser library

### ISSUE THREAD

**Issue by lxhoan** [influxdata/influxdb-java#464]
Currently JSON parser in influxdb-java is Moshi. However we are going to support MessgagePack format (issue #389).
The Retrofit converter (referred to in Retrofit wiki page) for MessagePack is https://github.com/komamitsu/retrofit-converter-msgpack

This convertor depends on Jackson. To ensure the consistency we should switch to Jackson as well
(Moreover, seems we can also consider to drop JSON in influxdb-java due to some limitations of JSON, refer to this influxdb [Proposal: Stop using JSON as the standard response format](https://github.com/influxdata/influxdb/issues/8330) for more information)

**Comment by majst01** [comment]
Hi Hoan,

we should put this into the 3.x milestone, because dropping json support means dropping support for influxdb versions < 1.4 which would be a major change from the user perspective.

**Comment by lxhoan** [comment]
Hi Stefan,
>(Moreover, seems we can also consider to drop JSON in influxdb-java due to some limitations of JSON, refer to this influxdb Proposal: Stop using JSON as the standard response format for more information)

This sentence is a proposal and not in the scope of this issue.

Basically this issue is to switch to Jackson only (for MessagePack and JSON), we are not going to drop JSON in 2.12

**Comment by majst01** [comment]
On question, why do we need a json deserializer at all if we switch to messagepack ? 
https://github.com/msgpack/msgpack-java for example does not have any external dependencies, which for me would be a perfect fit for a core library usage as in our case.

**Comment by majst01** [comment]
Who decided that ?

**Comment by lxhoan** [comment]
> https://github.com/msgpack/msgpack-java for example does not have any external dependencies, which for me would be a perfect fit for a core library usage as in our case.

This msgpack-core does not have object binding, and this library also suggest we had best to use jackson-databind (which depends on jackson-core) for object binding (you can check this https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md)

**Comment by lxhoan** [comment]
closed since I will implement a MessagePack retrofit convertor for influxdb-java
