### ISSUE TITLE
tags should be sorted by key in line protocol to reduce db server overheads

### ISSUE THREAD

**Issue by lxhoan** [influxdata/influxdb-java#468]
We can replicate this telegraf enhancement to influxdb-java

[InfluxDB output plugin should sort tags](https://github.com/influxdata/telegraf/issues/3452)

according to the benchmark there seems a pretty good performance gain at server side

**Comment by majst01** [comment]
Should be quite easy to implement.

**Comment by majst01** [comment]
can we close this ?

**Comment by lxhoan** [comment]
close as merged
