### ISSUE TITLE
Please remove ping checks from query method

### ISSUE THREAD

**Issue by dmoebius** [influxdata/influxdb-java#470]
In `InfluxDBImpl::query()` there are two version checks at the top, both pinging the server _*twice*_ (!!!) for the version number:

    public void query(final Query query, final int chunkSize, final Consumer<QueryResult> consumer) {
        if (version().startsWith("0.") || version().startsWith("1.0")) {
            throw new UnsupportedOperationException("chunking not supported");
        }
        ...

Please either remove those version checks completely (I think nobody uses these old versions anymore), or cache the result of `version()`, or query each server only _once_ for it's version number.

**Comment by majst01** [comment]
Hi @dmoebius ,

good catch, do you mind prepping a MR ? It will take a while because holidays are coming :-)
