### ISSUE TITLE
Duplicate entries in influxdb 1.5 with influxdb-java 2.8 and batching enabled!

### ISSUE THREAD

**Issue by woblume** [influxdata/influxdb-java#473]
Hi
I am using 
InfluxDB 1.5
with influxdb-java:
<dependency>
	<groupId>org.influxdb</groupId>
	<artifactId>influxdb-java</artifactId>
	<version>2.8</version>
</dependency>

I have also activated batching.

Now I have duplicate entries in influx:
2018-07-19T18:04:15.08Z  928830 MSG_AUTHREQ sessionAufbauOk         -1
2018-07-19T18:04:15.081Z 928830 M_FSM       messageSentFirst        1
2018-07-19T18:04:15.081Z 928830 M_FSM       messageSentFirst        1
2018-07-19T18:04:15.088Z 928830 M_FSA       responseOk              -1

How can that be?
Thanks, Wolfgang

**Comment by martin-g** [comment]
I would recommend you to upgrade to the latest released version of influxdb-java (2.11) and test again. It might have been fixed since 2.8.

**Comment by woblume** [comment]
Hi Martin,
Yes, we'll upgrade influxdb to 1.6 and the Java api to 2.11.
But are you aware of any duplicate issues with 1.5 and 2.8?
I had been working with the older versions for quite a while now, before I first realized the issue last week.
Wolfgang

**Comment by woblume** [comment]
Yes I am sure I didnt write my records with the same timestamp due to my application logs.
The above is only an example for a duplicate, there are multiple!

**Comment by majst01** [comment]
If you didnt write them twice, it is a influxdb problem and not related to the driver influxdb-java.
