### ISSUE TITLE
Can I specify my own retrofit converterFactory?

### ISSUE THREAD

**Issue by scmod** [influxdata/influxdb-java#486]
Sometimes I want to just get the responseBody of string, then redirect it to some other applications through thrift, but I can't find how to set my own converterFactory of InfluxDBImpl. 
An extend of InfluxDBImpl, or implement of InfluxDB may have no visibility of some fields, methods or constructors in InfluxDBImpl.
So may be a loose restrictive constructor is needed?

**Comment by lxhoan** [comment]
Hi @scmod,
Thank for the idea, however I don't think we will plan it in short-term
It's rather easy to initialize your own OkHttp client and send a query to influxdb server

BYT, If you still want to stick to InfluxDBImpl, I think you can work around by a custom OkHttp interceptor (InfulxDBImpl constructor takes a OkHttpClient.Builder parameter) which will read the string from response body

**Comment by scmod** [comment]
@lxhoan Yes! let me have a look about interceptor work around, or may be initialize my own okhttp client will be better. Thank you!
