### ISSUE TITLE
Any other faster protocol than http available to read the data from InfluxDB?

### ISSUE THREAD

**Issue by algotradersxyz** [influxdata/influxdb-java#489]
Any other faster protocol than http since both my datasource and engine are on same machine

**Comment by lxhoan** [comment]
influxdb-java supports both tcp (http) and udp
if you dont feel happy with http, can give udp a try

**Comment by lxhoan** [comment]
the influxdb server supports none other than http and udp, so does this client

**Comment by fmachado** [comment]
As mentioned by @lxhoan and explained on https://docs.influxdata.com/influxdb/v1.6/supported_protocols/ , there is only support to HTTP and UDP.

I don't know your current scenario and probably you are aware that you will have, at the end, both software competing for CPU time. As far as I remember, by using `loopback` address you will skip the physical layer.

I'm closing this ticket as it's not an InfluxDB issue.
