### ISSUE TITLE
Communications link failure

### ISSUE THREAD

**Issue by gentixharavina** [influxdata/influxdb-java#490]
So I did everything as in an example on how to connect and send data to the InfluxDB but after running the application it fails and i get this error: 
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

Can anyone please help, im new to Influx and im trying to send some data through my Java application to InfluxDB.

Thank you

**Comment by fmachado** [comment]
@gentixharavina the error you reported here is not related with InfluxDB but with MySQL:
```
**com.mysql**.cj.jdbc.exceptions.CommunicationsException: Communications link failure
```
I'm closing this ticket as it's not InfluxDB related.
