### ISSUE TITLE
losing precision when query with epoch=ns

### ISSUE THREAD

**Issue by scmod** [influxdata/influxdb-java#494]
the default converter-moshi convert time as a double, so when the  time is returned in millis, it maybe ok, but will lose precision when in nanos.
for example,  nanoseconds of 1534906009915285377 comes to be 1.5349060099152855E18, it's confusing when there is a need to display the time with nanosecond, or failure updating a value by time

**Comment by lxhoan** [comment]
you can consider to use MessagePack format (supported from  influxdb-java version 2.12) which encodes/decodes time in Unix epoch format as Long value
