### ISSUE TITLE
Too many waiting threads (okhhtp3)

### ISSUE THREAD

**Issue by EgoVas95** [influxdata/influxdb-java#507]
Hi
I use the influxDB 1.7.0 + graphana 5.2.2 + java.
encountered a problem. Data is coming to me from one device every 10 seconds. And when you write data from the device to the database opens an incredible number of threads (about 6 thousand) which are in the standby mode. If to judge by dump - flows ohntp3 ConnetionPool, which is not used in my project directly.
    
I tried to record and using batch, I also used synchronous recording, but still, every connection opens, and close () does not change anything.

Is this a problem or am I panicky?

**Comment by EgoVas95** [comment]
The code of the last record:

`      public static booleanwriteToInfluxDB( long time, ProtocolV1Class protocol, InfluxDB influxDB )
          try {			
			String table_name = "table";
			
			influxDB.setDatabase(dbName);
	
	        //BatchPoints batchPoints = BatchPoints.database(dbName).build();
	        
	        Builder builder = Point.measurement(table_name)
    				.time( Time.secondsToMillis( time ), TimeUnit.MILLISECONDS )
    				.tag("uid", UID)
    				.addField( "name", locationName )
    				.addField( "geohash", GetGeoHash.getGeoHash(latitude, longitude) )
        			.addField("geo_val", 5);		        		
			
			Point point = builder.build();
  
    		influxDB.write(point);
    		influxDB.close();

    		builder = null;
    		locationName = null;
    		builder = null;
    		point = null;
    		
    		return true;
			
		} catch( Exception e ) {
			log.severe("InfluxDbWriter/writeGPS " + e);
		}
		return false;	
	}`

**Comment by lxhoan** [comment]
Hi @EgoVas95 , first please make sure InfluxDB instance is shared across the JVM
If you have to create many InfluxDB instances (e.g. your application is writing to many influxDB servers), also consider reusing OkHttpClient.Builder so we can share the connection pool

BTW, I have no idea with TsongnethionPool, some mix-up in your project and it causes this problem ?

**Comment by EgoVas95** [comment]
ConnetionPool instead TsongnethionPool, sorry for that

**Comment by lxhoan** [comment]
>ConnetionPool instead TsongnethionPool, sorry for that
OK @EgoVas95 , so just make sure for the remaining of my suggestion above

**Comment by EgoVas95** [comment]
The project uses servlets, so yes InfluxDB instance is shared across the JVM, but each time a new servlet is created with a new instance.
The only solution that I see is to forcefully terminate the stream after writing, judging by the description it should be done by the close () method, but it does not work for me.
Forgive me if I'm stupid somewhere, not so long ago I started programming for Java

**Comment by EgoVas95** [comment]
It helped. Thanks for the help!
