### ISSUE TITLE
Request certificate issue

### ISSUE THREAD

**Issue by licunzhi** [influxdata/influxdb-java#511]
In my project, there already exists a request interface that requires HTTPS authentication

When I use it again, I get a null pointer problem

how to do to solve the problem

**Comment by majst01** [comment]
Stacktrace ?

**Comment by licunzhi** [comment]
what?

**Comment by majst01** [comment]
To identify the root cause of your problem, we need at least a Stacktrace with the mentioned NPE.

**Comment by fmachado** [comment]
@licunzhi without showing your code or the complete error message we cannot help you with your issue. I highly suggest you to post your questions on StackOverflow, where you may get some help.
