### ISSUE TITLE
batch write loss data random

### ISSUE THREAD

**Issue by renkang** [influxdata/influxdb-java#527]
When I use ` influxDB.write(batchPoints); ` some data always random loss. How can I prevent the thing  happening?
the following pom.xml :

    <dependency>
      <groupId>org.influxdb</groupId>
      <artifactId>influxdb-java</artifactId>
      <version>2.8</version>
    </dependency>

**Comment by majst01** [comment]
Hi @renkang 

please try with the most recent version of influxdb-java which is 2.13 and in the next few days 2.14. There have been a lot of fixes in this area.

**Comment by renkang** [comment]
Hi @majst01 , I upgrade the version of influxdb-java to 2.13 and run my application for the whole day, and add about 10 thousand records into influxdb with `influxDB.write(batchPoints)`. But the situation of lossing data still happens.  The num of lossing data is about 33 record.Anything can I do for ensuring all record added into influxdb successfully? Thanks for you help.

**Comment by fmachado** [comment]
@renkang without knowing (1) how you are storing your data points and (2) how you are verifying that your data points are missing we cannot provide you more help.

Could you please add a test case where we could reproduce your issue?
