### ISSUE TITLE
Cannot find InfluxDBMapper 

### ISSUE THREAD

**Issue by ARUNJOHNSONPUTHUPARAMBIL** [influxdata/influxdb-java#538]
I could not find the influx DB mapper in  2.9 and 2.14 releases. I am using spring boot project, by default, it gives 2.9 release and could not find InfluxDBMapper and I tried to override the version to 2.14 again it did not give the DB mapper. Is there anything to add for that particular class?????

**Comment by gkatzioura** [comment]
If you mean [this](https://github.com/influxdata/influxdb-java/blob/master/INFLUXDB_MAPPER.md) one, I think it is currently on the 1.5-SNAPSHOT (not yet relases). Most probably you need to build and install locally. Someone may correct me if I am wrong.

**Comment by ARUNJOHNSONPUTHUPARAMBIL** [comment]
Then  Why it is included in document????? It is inluded in readme.md  but not in release. Please try  to update it to the latest readme or try to include everythig in the readme in releases. One who try to download this jar will always refer to the README.MD. Appreciate  the good work have done so far....... Thank you

**Comment by ARUNJOHNSONPUTHUPARAMBIL** [comment]
Any one please tell me when you are going to include this [InfluxDBMapper](https://github.com/influxdata/influxdb-java/blob/master/INFLUXDB_MAPPER.md) in the main release. Eagerly waiting for that feature as i am  using spring boot. It will help me a lot in the development of application using influx db.

**Comment by msiczek** [comment]
I would also vote for this feature, and I'd love to see it released anytime soon.
I got here in fact looking for info whether you plan to include it in next release and when would this be.
Or maybe if the master branch is quite stable I should build it on my own just for now?

**Comment by fmachado** [comment]
This issue was solved with the newest version.
