### ISSUE TITLE
Does influxdb-java lib supports https connection ?

### ISSUE THREAD

**Issue by PauloDevelo** [influxdata/influxdb-java#539]
Hello,

I have issues to connect on an Influxdb with an https URL. The certificate is self-signed, so I was looking for an option to ignore unsafe SSL, like in Chronograf, telegraf or the Influx CLI.
Do you know guys if this is a limitation of this library?

**Comment by fmachado** [comment]
Depending on your security requirements, you may solve your issue by trusting the certificate at JVM level or just create a custom OkHttp client configured with your custom certificate (or just ignore errors if you are in a test environment).

Check this link for more information: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java

**Comment by rhajek** [comment]
Hi, you can use the self-signed certificate with influxdb-java, but the underlying okhttp client library is strict about the host name verification. The certificate must contain the Subject Alternative Name entry (2.5.29.17) matching your hostname. Certificate that was created according https://docs.influxdata.com/influxdb/v1.6/administration/https_setup/#step-1-generate-a-self-signed-certificate will not work with influxdb-java client.

**Comment by PauloDevelo** [comment]
Thank you for your answers, I will check them out very soon.

**Comment by fmachado** [comment]
@rhajek I managed to have the influxdb-java unit tests running against an InfluxDB instance using a self-signed certificate as described on the link you provided. If you are having issues matching the hostname, you may try something like:
```Java
OkHttpClient.Builder builder = new OkHttpClient.Builder();
//...
builder.hostnameVerifier(new HostnameVerifier() {
    @Override
    public boolean verify(String hostname, SSLSession session) {
        return true; // please don't use this in production code
    }
});
```
@PauloDevelo I'm closing this ticket as this is not a real issue.
