### ISSUE TITLE
InfluxDBResultMapper.toPOJO(...) after query with tz() clause throws java.time.format.DateTimeParseException

### ISSUE THREAD

**Issue by gachdn** [influxdata/influxdb-java#573]
### Problem:
When adding the tz() clause to a working query the InfluxDBResultMapper.toPOJO(...) cannot parse the time String returned by Influx. Please see details below.

### Versions: 
- InfluxDb 1.7.1
- influxdb-java 2.14 

### Possible solution:
line 62 in _org.influxdb.impl.InfluxDBResultMapper.java_ defines the format  with the .appendPattern("X").
The **"X"** pattern only parses 'Z' or '-18' to '+18'

putting **"XXX"** pattern solved the parsing issue -**BUT**- i have no ideas which other formats are returned by InfluxDB...

DateTimeFormatter Javadoc:
> Offset X and x: This formats the offset based on the number of pattern letters. One letter outputs just the hour, such as '+01', unless the minute is non-zero in which case the minute is also output, such as '+0130'. Two letters outputs the hour and minute, without a colon, such as '+0130'. Three letters outputs the hour and minute, with a colon, such as '+01:30'. Four letters outputs the hour and minute and optional second, without a colon, such as '+013015'. Five letters outputs the hour and minute and optional second, with a colon, such as '+01:30:15'. Six or more letters throws IllegalArgumentException. Pattern letter 'X' (upper case) will output 'Z' when the offset to be output would be zero, whereas pattern letter 'x' (lower case) will output '+00', '+0000', or '+00:00'. 

### Traces:
- JSON Response without **tz('Europe/Berlin')** clause: ( toPOJO(...)  works fine ! )
`...
			"columns": ["time",
			"minmax",
			"firstlast"],
			"values": [["2019-01-01T00:00:00Z",
			37,
			37],
			["2019-01-02T00:00:00Z",
			202,
			202],
...
`

- JSON Response with **tz('Europe/Berlin')** clause: ( throws exception )
`...
			"columns": ["time",
			"minmax",
			"firstlast"],
			"values": [["2019-01-01T00:00:00+01:00",
			37,
			37],
			["2019-01-02T00:00:00+01:00",
			202,
			202],
...
`

- The Exception:
`java.time.format.DateTimeParseException: Text '2019-01-01T00:00:00+01:00' could not be parsed, unparsed text found at index 22
	at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
	at java.time.format.DateTimeFormatter.parse(Unknown Source)
	at org.influxdb.impl.InfluxDBResultMapper.fieldValueModified(InfluxDBResultMapper.java:321)
	at org.influxdb.impl.InfluxDBResultMapper.setFieldValue(InfluxDBResultMapper.java:295)
	at org.influxdb.impl.InfluxDBResultMapper.parseSeriesAs(InfluxDBResultMapper.java:246)
...
`

**Comment by fmachado** [comment]
@gachdn PR #575 will fix this issue. Let's wait for review/approval.

**Comment by fmachado** [comment]
@gachdn this was fixed with the newest version 2.15.
