### ISSUE TITLE
tag isn't work 

### ISSUE THREAD

**Issue by Justmysteriousman** [influxdata/influxdb-java#574]
here is my class:
```Java
@Measurement(name="memory")
public class MemoryPoint {
	@Column(name="time")
	private Instant time;
	@Column(name="name",tag=true)
	private String name;
	@Column(name="free")
	private Integer free;
	@Column(name="used")
	private Integer used;
	@Column(name="buffer")
	private Integer buffer;
...
}
```
the name should be a tag key,but it is not,
save like this:
```Java
		BatchPoints points = BatchPoints.database("unit").build();
		HashMap<String, Object> map = new HashMap<>();
		map.put("time", 1550554651058659500l);
		map.put("name", "tom");
		map.put("free", 100);
		map.put("used", 1);
		map.put("buffer",88);
		Point point = Point.measurement("memory").fields(map).build();
		influxDb.write(points.point(point));
```
in cli ,
```
![cli](https://user-images.githubusercontent.com/47545727/53003187-5c85e500-3469-11e9-8109-3e7fc59ef140.png)
```
my version is 2.14,and influxdb is 1.7.2

**Comment by Justmysteriousman** [comment]
if i  use
map.put("time",Instant.ogEpochMilli(1550554651058659500l)).
i got exception below:
Exception in thread "main" org.influxdb.InfluxDBException$UnableToParseException: unable to parse 'memory buffer=88i,free=100i,name="tom",time=+49137090-11-17T06:04:19.500Z,used=1i': invalid boolean
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:147)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:796)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455)
	at top.mysteriousman.influx.unit.InfluxData.setPoint(InfluxData.java:46)
	at top.mysteriousman.influx.unit.InfluxData.main(InfluxData.java:33)

**Comment by Justmysteriousman** [comment]
> here is my class:
> @measurement(name="memory")
> public class MemoryPoint {
> @column(name="time")
> private Instant time;
> @column(name="name",tag=true)
> private String name;
> @column(name="free")
> private Integer free;
> @column(name="used")
> private Integer used;
> @column(name="buffer")
> private Integer buffer;
> ...
> }
> the name should be a tag key,but it is not,
> save like this:
> BatchPoints points = BatchPoints.database("unit").build();
> HashMap<String, Object> map = new HashMap<>();
> map.put("time", 1550554651058659500l);
> map.put("name", "tom");
> map.put("free", 100);
> map.put("used", 1);
> map.put("buffer",88);
> Point point = Point.measurement("memory").fields(map).build();
> influxDb.write(points.point(point));
> in cli ,
> ![cli](https://user-images.githubusercontent.com/47545727/53003187-5c85e500-3469-11e9-8109-3e7fc59ef140.png)
> my version is 2.14,and influxdb is 1.7.2

today,i find there are two map fields in Point,i use another to put tag,it works,but what's effect about @column(name="name",tag=true)?

**Comment by domixr** [comment]
the annotation @**column**(name="name",tag=true) (as well as the annotations to the other fields in the bean) hasn't effect in the moment that you store your data in influxDB, but it has effect to store in your bean the result of a query to influxDB using the `toPojo` method like the example below. 

`QueryResult queryResult = influxDB.query(new Query("SELECT * FROM cpu", dbName));

InfluxDBResultMapper resultMapper = new InfluxDBResultMapper(); // thread-safe - can be reused
List<Cpu> cpuList = resultMapper.toPOJO(queryResult, Cpu.class);`

**Comment by fmachado** [comment]
@Justmysteriousman it seems your measurement class is correct but you are writing to InfluxDB using a HashMap and I'm not sure what behavior do you expect here. Also, as @domixr explained, the `tag` property is only used when you are writing to InfluxDB passing your measurement instance as parameter.

I'm closing this ticket. If something still does not work for you, please reopen it.

**Comment by Justmysteriousman** [comment]
> The annotation `@column(name="name",tag=true)`
> 
> Has effect when you use the following method to insert your data in InfluxDB: https://github.com/influxdata/influxdb-java/blob/master/README.md#writing-using-pojo
> 
> Moreover, using this annotation is possible to store in your object "MemoryPoint", in the field "name", the value of the tag "name" present in influxDB, returned from your query when you use this method: https://github.com/influxdata/influxdb-java/blob/master/README.md#queryresult-mapper-to-pojo-version-27-required

i cann't find the method Point.measurementByPOJO
