### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by saumyaAgupta** [influxdata/influxdb-java#577]
how do you know version to mention while adding dependency in the pom.xml file?

**Comment by majst01** [comment]
I dont understand your question, you just have to add:

```xml
<dependency>
  <groupId>org.influxdb</groupId>
  <artifactId>influxdb-java</artifactId>
  <version>2.14</version>
</dependency>
```
to your pom.xml.

**Comment by saumyaAgupta** [comment]
yeah like you mentioned 2.15 as version, I wanted to know if the version is different for everybody or what basis the version is defined?

**Comment by majst01** [comment]
No the version is not different, 2.15 is the latest and the one you should use.

**Comment by saumyaAgupta** [comment]
thank you so much for clarifying.
