### ISSUE TITLE
how can I use InfluxDBResultMapper in group influxql ?

### ISSUE THREAD

**Issue by flykarry** [influxdata/influxdb-java#579]
I want to use InfluxDBResultMapper to simply my query, but How can I use it in group influxql? I got 2 series. And I need the result is like List<List<Object>>, but the toPojo method return is List<Object>

**Comment by fmachado** [comment]
Please add here a more detailed description of your problem including your queries, an example of what is happening and what do you expect as result.

**Comment by flykarry** [comment]
I use regular expression slved my question. thanks for reply
