### ISSUE TITLE
NoSuchMethodError: okHttp3.HttpUrl.get(L java/lang/String:)Lokhttp3/HttpUrl

### ISSUE THREAD

**Issue by heshengbang** [influxdata/influxdb-java#580]
When i use influx-java version 2.15, i created InfluxDB use follow code:
```
OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.connectionTimeout(60, TimeUnit.SECONDS);
builder.readTimeout(60, TimeUnit.SECONDS);
InfluxDB influxDB = InfluxDBFactory.connect("localhost:8086", "influx", "influx", builder);
```
when i use influxDB to query some data like:
```
influxDB.query(new Query("select count(*) from cpu", "db_computer"));
```
there will have some error happen, exception message like below:
```
caused by: java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(L java/lang/String:)L okhttp3/HttpUrl:
    at refrofit2.Retrofit$Builder.baseUrl(Retrofit.java:458)
    at org.influxdb.iml.InfluxDBImpl.<init>(InfluxDBImpl.java:178)
```

In my opinion,  there have some dependencies in pom.xml , is not suitable with okhttp3.
I don't know if there are anybody have same question with me, if you have it , please comment and tell me.

**Comment by fmachado** [comment]
@heshengbang could you please execute `mvn dependency:tree` and add the output here ?

**Comment by heshengbang** [comment]
[INFO] \- org.influxdb:influxdb-java:jar:2.15:compile
[INFO]    +- com.squareup.retrofit2:retrofit:jar:2.5.0:compile
[INFO]    +- com.squareup.retrofit2:converter-moshi:jar:2.5.0:compile
[INFO]    |  \- com.squareup.moshi:moshi:jar:1.5.0:compile
[INFO]    +- org.msgpack:msgpack-core:jar:0.8.16:compile
[INFO]    +- com.squareup.okhttp3:okhttp:jar:3.8.1:compile
[INFO]    |  \- com.squareup.okio:okio:jar:1.13.0:compile
[INFO]    \- com.squareup.okhttp3:logging-interceptor:jar:3.8.1:compile

**Comment by heshengbang** [comment]
```
[INFO] \- org.influxdb:influxdb-java:jar:2.15:compile
  [INFO]    +- com.squareup.retrofit2:retrofit:jar:2.5.0:compile
  [INFO]    +- com.squareup.retrofit2:converter-moshi:jar:2.5.0:compile
  [INFO]    |  \- com.squareup.moshi:moshi:jar:1.5.0:compile
  [INFO]    +- org.msgpack:msgpack-core:jar:0.8.16:compile
  [INFO]    +- com.squareup.okhttp3:okhttp:jar:3.8.1:compile
  [INFO]    |  \- com.squareup.okio:okio:jar:1.13.0:compile
 [INFO]    \- com.squareup.okhttp3:logging-interceptor:jar:3.8.1:compile
```

**Comment by majst01** [comment]
There is something wrong, you can see here: https://github.com/influxdata/influxdb-java/blob/master/pom.xml#L271 that influxdb-java has a dependency to okhttp 3.13.1, your dependency is to 3.8.0 which is for sure the reason that the Exception above occurs. Do you have any other components in your app which have a dependency to okhttp ?

**Comment by heshengbang** [comment]
no, i have found all denpendencies in my project, there only have okhttp3 in influxdb-java. i have no idea why the okhttp3 's version isn't 3.13.1 .

**Comment by majst01** [comment]
But mvn dependency:tree proves that a old version is in use, dunno what your local setup looks like. Maybe you can search your maven cache directory for downloaded jars with okhttp in the name.

**Comment by heshengbang** [comment]
ok，i guess the problem what happen not cause by influxdb-java, i will close this issue.

**Comment by jakubskalak** [comment]
Hi, 
I had similar issue.
Gradle dependencies:
```
`+--- org.influxdb:influxdb-java:2.15
|    +--- com.squareup.retrofit2:retrofit:2.5.0
|    |    \--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.8.1
|    |         \--- com.squareup.okio:okio:1.13.0
|    +--- com.squareup.retrofit2:converter-moshi:2.5.0
|    |    +--- com.squareup.retrofit2:retrofit:2.5.0 (*)
|    |    \--- com.squareup.moshi:moshi:1.5.0
|    |         \--- com.squareup.okio:okio:1.13.0
|    +--- org.msgpack:msgpack-core:0.8.16
|    +--- com.squareup.okhttp3:okhttp:3.13.1 -> 3.8.1 (*)
|    \--- com.squareup.okhttp3:logging-interceptor:3.13.1 -> 3.8.1
|         \--- com.squareup.okhttp3:okhttp:3.8.1 (*)`
```

I solved it by explicitly add to Gradle dependencies:

```
`   api 'com.squareup.okhttp3:okhttp:3.13.1'
    api 'com.squareup.okhttp3:logging-interceptor:3.13.1'`
```

```
`+--- org.influxdb:influxdb-java:2.15
|    +--- com.squareup.retrofit2:retrofit:2.5.0
|    |    \--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.13.1 (*)
|    +--- com.squareup.retrofit2:converter-moshi:2.5.0
|    |    +--- com.squareup.retrofit2:retrofit:2.5.0 (*)
|    |    \--- com.squareup.moshi:moshi:1.5.0
|    |         \--- com.squareup.okio:okio:1.13.0 -> 1.17.2
|    +--- org.msgpack:msgpack-core:0.8.16
|    +--- com.squareup.okhttp3:okhttp:3.13.1 (*)
|    \--- com.squareup.okhttp3:logging-interceptor:3.13.1 (*)`
```

**Comment by SUKF** [comment]
我的项目排除okhttp后重新引入一个新版本就解决了。
```
<dependency>
    <groupId>org.influxdb</groupId>
    <artifactId>influxdb-java</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
    <version>2.15</version>
</dependency>
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>4.0.1</version>
</dependency>
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>logging-interceptor</artifactId>
    <version>4.0.1</version>
</dependency>
```

**Comment by majst01** [comment]
There is no support for okhttp 4.x at the moment
