### ISSUE TITLE
Android to InfluxDB connection not working when screen locked

### ISSUE THREAD

**Issue by eneko28** [influxdata/influxdb-java#585]
Hi,

I’m developing an Android application using this library. The connection to my database is correctly stablished but since the screen is locked the data transmission in interrupted.
I’ve other background task running in the application and they are not stopping right after the screen lock. Would you know if the functions this library use are not working with Android locked screen?

I’d like to precise that I used WakeLocks in order to keep the CPU alive (that is the reason why the rest of the background processes are still running).

Thanks

**Comment by majst01** [comment]
I have no developer experience with android sorry.
