### ISSUE TITLE
Bad database query in callback returns nothing/success

### ISSUE THREAD

**Issue by maxemann96** [influxdata/influxdb-java#602]
This `influxDB.query(Query("SHOW SERRIES"))` (Note the double R) is working as intended and throwing an InfluxDBException with a good error message 
> error parsing query: found SERRIES, expected ...

Working with a callback 
```java
influxDB.query(new Query("SHOW SERRIES"), result -> {
        println(result) // This code is executed
    }, error -> {
        error.printStackTrace()
    })
```
the result is that `null`is printed to stdout. I think this is incorrect behaviour, since it should be possible to handle any error. I don't know whether it is usefull to call the error callback or call the success callback with a QueryResult containing an error and no result.

If you want, i can fix this and make a pullrequest, but the behaviour should be defined first

**Comment by majst01** [comment]
Good catch, i am happy to review a PR !
