### ISSUE TITLE
Are there any plan to implement FLEX query?

### ISSUE THREAD

**Issue by gogangipark** [influxdata/influxdb-java#604]
Influxdb has supported FLEX  for advanced query.

Do you have any plan to implement library?

**Comment by bednar** [comment]
Hi @gogangipark,

currently it is implemented in [/bonitoo-io/influxdb-client-java](https://github.com/bonitoo-io/influxdb-client-java).

The [/bonitoo-io/influxdb-client-java](https://github.com/bonitoo-io/influxdb-client-java) will be moved into InfluxData repository after the InfluxDB 2.0 will be move into the beta phase.

**Comment by gogangipark** [comment]
Good.

+1
