### ISSUE TITLE
Method problem

### ISSUE THREAD

**Issue by 1457275815** [influxdata/influxdb-java#607]
influxDB.write(batchPoints) and influxDB.write(batchPoints.lineProtocol())
The data is written in batches, and the second type of writing is faster. It is not good to use the second one when it is used again. Or are there any restrictions on the usage of these two methods?

**Comment by fmachado** [comment]
@1457275815 one of the reasons this tool was built for was to help you pushing/pulling data to/from InfluxDB so you don't have to worry creating/assembling the line protocol.
Unless you have a really specific scenario like "you are reading the line protocol from a text file", please use this library as recommended by the documentation.
