### ISSUE TITLE
TimeColumn annotation non-exististent, POJO helper unusable

### ISSUE THREAD

**Issue by tristancf** [influxdata/influxdb-java#608]
In the latest release (2.15), there is no TimeColumn.java. The documentation leaves no reference to this.

The bug in [this issue](https://github.com/influxdata/influxdb-java/issues/586) means there is no generic way to add a time column/field to a POJO, and [the fix](https://github.com/influxdata/influxdb-java/commit/8d4a85371d6d876a4df96a066cb95788cf712a1f) has not been released.

Is this something that will likely be released soon? Will it take a couple more weeks, months, half years ...?

**Comment by majst01** [comment]
Thanks for the trigger, i will ask the release team from influxdb to help ship that release out soon.

**Comment by tristancf** [comment]
Could you give a ballpark as to what you mean by soon? Soon could mean many (quite different) times.

**Comment by majst01** [comment]
I asked them and will tell you when we can expect a new release.

**Comment by hgromer** [comment]
I want to emphasize this issue. This has some pretty serious implications, especially considering the documentation of the library is written dependent on this fix being implemented. A good portion of the documentation is not useful due to this fact.

**Comment by majst01** [comment]
@ivankudibal please consider a release.

**Comment by feitgraph** [comment]
Sadly still see a problem in 2.15.
Which version does not contain this issue?

**Comment by kshitijcode** [comment]
Please consider a release with this fix.

**Comment by tymons** [comment]
Is there any updates for this issue?

**Comment by majst01** [comment]
The fix landed in 2.16
