### ISSUE TITLE
ability to use custom http client or to import separated lib only for formatting

### ISSUE THREAD

**Issue by aimazh** [influxdata/influxdb-java#610]
Hi there!

I would have an option to setup my **own http client** to transfer the data into InfluxDB. By default `influxdb-java` offers an OkHttp lib. That's nice, but ...

Problem is I have already another http client for my app and i want to use them instead of OkHttp. Including OkHttp as an extra dependency is a bit redundant.

Otherwise, I would have a separated `influxdb-java-formatter` lib only to format my points and then send them using my http client.

Hope, you accept this issue ^_^

Have a nice day!
@aimazh

**Comment by majst01** [comment]
If you have a working solution in a Pull Request, i will review and eventually merge.

**Comment by fmachado** [comment]
IMHO this won't be easy to implement with the existing codebase. I'm closing this issue but feel free to submit a PR with your working solution and I'll reopen it.
