### ISSUE TITLE
No class definition found error when included in a library as a dependency

### ISSUE THREAD

**Issue by bhedges225** [influxdata/influxdb-java#612]
I am currently getting the following error when including the influxdb java client into a library I am creating. I am including the library which uses the influxdb client into an application with gradle. It seems the influx client is available at compile time but not runtime. 

java.lang.NoClassDefFoundError: java.util.concurrent.atomic.LongAdder
        at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:92)
        at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:123)
        at org.influxdb.impl.InfluxDBImpl.<init>(InfluxDBImpl.java:187)
        at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:48)

I have included it in the library with the following line in the build.gradle:
api 'org.influxdb:influxdb-java:2.15'

I was curious to see if anyone else had this issue. Thank you in advance
Gradle version: 5.1.1

**Comment by fmachado** [comment]
As you can find [here](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/LongAdder.html), `LongAdder` is available from Java 1.8+. Make sure you have the proper Java version installed.
