### ISSUE TITLE
BoundParameterQuery can not bind SELECT parameters

### ISSUE THREAD

**Issue by lksvenoy-r7** [influxdata/influxdb-java#615]
## Expected Behaviour
When using BoundParameterQuery with SELECT and WHERE bind parameters, the query is created successfully and results are returned, if any.

## Current Behaviour
InfluxDB throws an error when using SELECT bind parameters

## Steps to Reproduce
1. Create a BoundParameter query builder and create this query:
```
var queryBuilder = BoundParameterQuery.QueryBuilder.newQuery("SELECT $foo FROM dest WHERE bar = $bar AND baz = $baz");
queryBuilder.bind("foo", "foo");
queryBuilder.bind("bar", "bar");
queryBuilder.bind("baz", "baz");
var query = queryBuilder.create();
```
2. Execute it with
`influxDB.query(query);`
3. Observe the error
`QueryResult [results=[Result [series=null, error=field must contain at least one variable]], error=null]`

## Environment
Java: 11.0.2
InfluxDB Java: 2.15

## Detailed Description
Currently, the BoundParameterQuery query builder does not support bind parameters for the FROM and SELECT clause. When trying to execute a query with SELECT bind parameters, this error is returned in the query result: 
`QueryResult [results=[Result [series=null, error=field must contain at least one variable]], error=null]`

When trying to use a bind parameter in the FROM clause, an InfluxDBException is thrown:
`error parsing query: found $dest, expected identifier at line 1, char 23`

**Comment by fmachado** [comment]
@lksvenoy-r7 as you can see [here](https://docs.influxdata.com/influxdb/v1.7/tools/api/):

> **Bind parameters**
> The API supports binding parameters to particular field values or tag values in the *WHERE* clause. Use the syntax `$<placeholder_key>` as a placeholder in the query, and URL encode the map of placeholder keys to placeholder values in the request body: (...)

The existing implementation on influxdb-java library is supporting the InfluxDB feature.
