### ISSUE TITLE
Time doesn't change as  I give

### ISSUE THREAD

**Issue by HintonZhang** [influxdata/influxdb-java#618]
Time doesn't change as  I give. I want to define the time to be 20190705. But there are two situations. The situation is that timestamp is currently. Another is no response or exception but the data I insert could not be queried.

**Comment by majst01** [comment]
Hi @HintonZhang,

can you elaborate your issue more precisely, maybe with a short snippet of Java Code ?

**Comment by HintonZhang** [comment]
Hi,@majst01
the code:
        InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086");
        String dbName = "myTimeseries9";
        String rpName = "aRetentionPolicy";
        influxDB.query(new Query("CREATE DATABASE " + dbName));
        influxDB.setDatabase(dbName);
        influxDB.query(new Query("CREATE RETENTION POLICY " + rpName + " ON " + dbName + " DURATION 30h REPLICATION 2 SHARD DURATION 30m DEFAULT"));
        influxDB.setRetentionPolicy(rpName);
        influxDB.enableBatch(BatchOptions.DEFAULTS);
        LocalDateTime localDateTime = LocalDateTime.of(2019,6,4,0,0);
        influxDB.write(Point.measurement("cpu")
                //UtcClock is just a tool we make. UtcClock.getTimeStamp() methed can get timestamp by  
               //what definition localDateTime
                .time(UtcClock.getTimeStamp(localDateTime),TimeUnit.MILLISECONDS)
                .addField("idle", 90L)
                .addField("user", 9L)
                .addField("system", 1L)
                .build());

        influxDB.write(Point.measurement("disk")
                .time(UtcClock.getTimeStamp(localDateTime),TimeUnit.MILLISECONDS)
                .addField("used", 80L)
                .addField("free", 1L)
                .build());

        Query query = BoundParameterQuery.QueryBuilder.newQuery("SELECT * FROM cpu WHERE idle > $idle")
                .forDatabase(dbName)
                .bind("idle", 90)
                .bind("system", 5)
                .create();
        QueryResult results = influxDB.query(query);
        influxDB.close();

The result of this code executed is no response and no exception.

**Comment by majst01** [comment]
You cannot expect to get a queryresult immediately after a write as the writes get cached in batches.
You need to flush explicitly before querying.

**Comment by HintonZhang** [comment]
I open another command line to query data. The SQL is "SELECT * FROM cpu". But I could get any result After executing that code

**Comment by HintonZhang** [comment]
I can get the result at the command line when I use System.currentTimeMillis() as the parameter of time() method;

**Comment by majst01** [comment]
Timestamps must be unique, and what prevents you to set the millis as well ?

**Comment by HintonZhang** [comment]
I can get the correct result when I use the default retention policy. Thank you!
