### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by johanfylling** [influxdata/influxdb-java#630]
In version 2.16, you have an explicit dependency on com.squareup.okhttp3:okhttp:3.14.3 but a transitive dependency on com.squareup.okhttp3:okhttp:3.12.0 (via the com.squareup.retrofit2 dependencies, it looks like).
There is also a version conflict for the transitive dependencies com.squareup.okio:okio:1.17.2 and com.squareup.okio:okio:1.16.0.
Earlier versions of influxdb-java has similar issues.
This causes issues with the strict resolution strategy we employ for out project.

**Comment by majst01** [comment]
What exactly is a strict resolution strategy ? Does your code still work or does it not compile ? 
I always try to use the most recent versions of the dependencies, especially on the http client side, because this is a performance and security related part of the whole.

**Comment by johanfylling** [comment]
We're building with gradle, and the relevant part of our resolution strategy is that we don't allow dependencies with conflicting versions.
E.g: `configurations.all {
	resolutionStrategy {
		failOnVersionConflict()
	}
}`
We can solve this by excluding transitive dependencies for a given dependency, and lock down the version by defining an explicit dependency. This we must live with when separate dependencies have transitive conflicts, but we prefer not to do so for a single dependency in isolation.

**Comment by majst01** [comment]
So what do you expect from this project to do now ?

**Comment by johanfylling** [comment]
I believe excluding the transitive dependencies would help. I'm no maven expert, but have created a PR with a suggested fix: #634

**Comment by travisspencer** [comment]
Was this ever fixed?

**Comment by majst01** [comment]
Yes this was fixed with a exclusion in the pom.xml with #634
