### ISSUE TITLE
Client certificate authorization is not working

### ISSUE THREAD

**Issue by KarlikB** [influxdata/influxdb-java#632]
I have just tried to implement client certificate connection into InfluxDB using approach described there: https://github.com/influxdata/influxdb-java/issues/512#issuecomment-419839473

This mechanism produces exception 
`
org.influxdb.InfluxDBException$AuthorizationFailedException: authorization failed
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:159)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:808)
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:795)
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:552)
	at debug.Debug.go(Debug.java:81)
	at debug.Debug.main(Debug.java:29)
`

I tested my client and server certificates using curl, postman and even plain OkHttpClient and it works.

There is my testing java code based on approach described in the link above, I have added call with plain OkHttpClient and later call through InfluxDB library using the same OkHttpClient.Builder with the same sslSocketFactory.

`
private void go() {

		// Test HTTPS with client certificate
		try {

			KeyStore keyStore = KeyStore.getInstance("PKCS12");
			keyStore.load(new FileInputStream("d:/PRAC/TSP/studium/keys/keystore.p12"), "changeit".toCharArray());

			KeyStore trustStore = KeyStore.getInstance("JKS");
			trustStore.load(new FileInputStream("d:/PRAC/TSP/studium/keys/BundleCA.jks"), null);

			SSLContext sslContext = SSLContext.getInstance("SSL");

			KeyManagerFactory keyManagerFactory = KeyManagerFactory
					.getInstance(KeyManagerFactory.getDefaultAlgorithm());
			keyManagerFactory.init(keyStore, "changeit".toCharArray());

			TrustManagerFactory trustManagerFactory = TrustManagerFactory
					.getInstance(TrustManagerFactory.getDefaultAlgorithm());
			trustManagerFactory.init(trustStore);

			TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();

			sslContext.init(keyManagerFactory.getKeyManagers(), trustManagers, new SecureRandom());
			sslContext.getDefaultSSLParameters().setNeedClientAuth(true);

			OkHttpClient.Builder okhttpClientBuilder = new OkHttpClient.Builder();
			okhttpClientBuilder.sslSocketFactory(sslContext.getSocketFactory(), (X509TrustManager) trustManagers[0]);

			HttpUrl.Builder builder = HttpUrl.parse("https://federosv5.tspdata.local:8086/query").newBuilder();
			builder.addQueryParameter("db", "Metric");
			builder.addQueryParameter("q", "select mean(value) from metrictype_CPU_Utilization limit 10");
			String url = builder.build().toString();
			Request request = new Request.Builder().url(url).build();
			OkHttpClient client = okhttpClientBuilder.build();
			Response response = client.newCall(request).execute();
			System.out.println(response);
			System.out.println(response.body().string());

			InfluxDB influxDB = InfluxDBFactory.connect("https://federosv5.tspdata.local:8086", okhttpClientBuilder);
			influxDB.setDatabase("Metric");

			// test query
			QueryResult result = influxDB.query(new Query("select mean(value) from metrictype_CPU_Utilization limit 10", "Metric"));
			System.out.println("result: " + result);

		} catch (Exception e) {
			e.printStackTrace();
		}

	}
`

The textual result of this code snippet run is:

`
Response{protocol=http/1.1, code=200, message=OK, url=https://federosv5.tspdata.local:8086/query?db=Metric&q=select%20mean%28value%29%20from%20metrictype_CPU_Utilization%20limit%2010}
{"results":[{"statement_id":0,"series":[{"name":"metrictype_CPU_Utilization","columns":["time","mean"],"values":[["1970-01-01T00:00:00Z",6.076128081080365]]}]}]}

org.influxdb.InfluxDBException$AuthorizationFailedException: authorization failed
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:159)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:808)
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:795)
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:552)
	at debug.Debug.go(Debug.java:81)
	at debug.Debug.main(Debug.java:29)

`
The first part is the correct output of the plain OkHttpClient call, after that there is exception produces byu influx-db java library with provided the same OkHttpClient.Builder instance. 

I have tried to do some debug tracing in Eclipse IDE and it looks like prepared OkHttpClient  is not used, the new instance is created and it fails because the client certificate ins not added there.

**Comment by KarlikB** [comment]
Some additional info

The influxDB is commercial variant InfluxDB Enterprise 1.7.4 and there is snippet from conffile:

> \# The bundle of SSL certificates to use for client cert authentication
>   https-ca-certificate = "/opt/assure1/etc/ssl/BundleCA.crt"
>
>   \# The SSL certificate to use when HTTPS is enabled.
>   https-certificate = "/opt/assure1/etc/ssl/Host.crt"
> 
>    \# Use a separate private key location.
>   https-private-key = "/opt/assure1/etc/ssl/Host.key"
>

**Comment by majst01** [comment]
For the commercial version you should ask the influxDB support channel.

**Comment by KarlikB** [comment]
> For the commercial version you should ask the influxDB support channel.

The problem is not in the InfluxDB, as mentioned above, plain OkHttpClient acess to Influx works well.
I currently found workaround, I created additional InfluxDB user with user/password login mechanism and it works in this infuxdb-java library.
But i think that this bug is worth to be fixed or at least mentioned in documentation that client certificate auth is not supported.

Please feel free to close this issue is this bug is not worth to fix.
