### ISSUE TITLE
Multiple queries

### ISSUE THREAD

**Issue by Slava96** [influxdata/influxdb-java#636]
My problem is - I need to send multiple queries at one API call to InfluxDB.
I'm using Spring Boot.

Spring Boot version - 2.2.0.RELEASE
Influx-java version - 2.15

Does this library supports multiple queries at one API call?
Because InfluxDB  - see information on "Multiple queries" title:
https://docs.influxdata.com/influxdb/v1.7/guides/querying_data/

**Comment by majst01** [comment]
Should work, as the result is the same type, just try.

**Comment by Slava96** [comment]
I try to send it separated by semicolon, but have issue like https://github.com/influxdata/influxdb-java/issues/214.

**Comment by majst01** [comment]
please send a PR with a added unit test where we can see this BUG.

**Comment by Slava96** [comment]
Create unit-test
My queries runs good!

So close this.

**Comment by majst01** [comment]
Hi @Slava96 

If you dont mind, can you please add one of these unit-test to this repo for further reference. I will review a PR.
