### ISSUE TITLE
Unable to query measurements with non default retention policy

### ISSUE THREAD

**Issue by maanasa** [influxdata/influxdb-java#637]
I am using influxdb to store monitoring metrics. I have a single db with multiple measurements and different retention policies attached to them.
Measurement A --> retention policy rp1 (default);
Measurement B --> retention policy rp2. 

I am using influxdb-java client and using the InfluxDBMapper and QueryBuilder.
I am unable to query measurement B with rp2. I can only specify the table name and internally it takes the default RP which is rp1. 

Here is how I am building the query : 

```
private Query buildQueryHelper(Query q, Clause c)
{
	if (q instanceof WhereQueryImpl)
	{
	  q = ((WhereQueryImpl) q).and(c);
	} else
	{
	  q = ((SelectQueryImpl) q).where(c);
	}
	return q;
}
Query q = null;
q = select().from("dbname", "B"); // at this point I have tried giving dbname.rp2.B using overridden function as from("dbname.rp2.B") but it throws IllegalStateException

if (StringUtils.isNonNullNonEmpty(req.getAccountId()))
{
	q = buildQueryHelper(q, eq(InfluxConstants.TAG_ACCOUNT_ID, req.getAccountId()));
}
if (StringUtils.isNonNullNonEmpty(req.getReqUUID()))
{
	q = buildQueryHelper(q, eq(InfluxConstants.TAG_REQ_UUID, req.getReqUUID()));
}
if (StringUtils.isNonNullNonEmpty(req.getUserId()))
{
	q = buildQueryHelper(q, eq(InfluxConstants.TAG_USER_ID, req.getUserId()));
} 
final List<B> result = influxDBMapper.query(q, B.class);`
```

From influx logs, I can clearly see that rp1 is being picked. How should I use QueryBuilder to set a specific retention policy?

**Comment by fmachado** [comment]
@maanasa if you are still facing this issue, could you please change your `from` call to
`q = select().from("dbname", "rp2.B");`
instead of
`q = select().from("dbname", "B");`
and try again?

I'll update the documentation with this missing scenario.

**Comment by fmachado** [comment]
@maanasa I'm closing this issue but feel free to reopen it if you are still having problems with your query.

**Comment by GLM00-max** [comment]
q = select().from("dbname", "rp2.B");

In this way, no results can be found

q = select().from("dbname", "\"rp2\".B");

It needs to be written like this

**Comment by GLM00-max** [comment]
q = select().from("dbname", "rp2.B");

In this way, no results can be found

q = select().from("dbname", "\"rp2\".B");

It needs to be written like this

**Comment by GLM00-max** [comment]
q = select().from("dbname", "rp2.B");

In this way, no results can be found

q = select().from("dbname", "\\"rp2\\".B");

It needs to be written like this

**Comment by GLM00-max** [comment]
q = select().from("dbname", "rp2.B");

In this way, no results can be found

q = select().from("dbname", "\\"rp2\\".B");

It needs to be written like this
