### ISSUE TITLE
@Column is used for non-string field error reporting

### ISSUE THREAD

**Issue by yahyaoo** [influxdata/influxdb-java#641]
If I have a field like this:
```java
    @TimeColumn
    @Column(name = "time")
    private Instant time;

    @Column(name = "tag_id", tag = true)
    private String tagId;

    @Column(name = "group_id", tag = true)
    private String groupId;

    @Column(name = "map_id", tag = true)
    private Integer mapId;

    @Column(name = "coordinate")
    private String coordinate;
```
When I insert the data it will be strongly cast to a String and an error will be reported：
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String`
By tracing the stack information, I found that the error was caused by:
**org.influxdb.dto.Point#addFieldByAttribute**
The code snippet is:
```java
if (column.tag()) {
     this.tags.put(fieldName, (String) fieldValue);//There's an error here
} else {
     this.fields.put(fieldName, fieldValue);
}
```

**Comment by yahyaoo** [comment]
The [official website](https://docs.influxdata.com/influxdb/v1.7/concepts/key_concepts/#discussion) has such an introduction:

> are your data; they can be strings, floats, integers, or Booleans, and, because InfluxDB is a time series database, a field value is always associated with a timestamp.

**Comment by fmachado** [comment]
@yahyaoo a `tag value` is always a String as you can see here: https://docs.influxdata.com/influxdb/v1.7/concepts/glossary/#tag-value
If you want to build a `Point` from a POJO, you must use the correct types.

I'm closing this as it's not an issue.
