### ISSUE TITLE
Cannot use subquery with QueryBuilder because SubQuery.close() is package private?

### ISSUE THREAD

**Issue by tonyclyde** [influxdata/influxdb-java#647]
Am I missing something or does this method need to be made public for QueryBuilder subqueries to be usable outside of the org.influxdb.querybuilder package? Trying to imitate the examples here: https://github.com/influxdata/influxdb-java/blob/master/src/test/java/org/influxdb/querybuilder/SelectionSubQueryImplTest.java#L65 but cant without access to that method.

**Comment by majst01** [comment]
Can you show your actual code ?

**Comment by tonyclyde** [comment]
Yeah, Im using scala but get the same behavior when i change to java. Im using: `org.influxdb:influxdb-java:2.17` and my code is something like this:

    Query query = select()
                .sum("column_1").as("count")
                .fromSubQuery("database", "table")
                .where(eq("column_2", "value"))
                .groupBy("column_3")
                .close()
                .where(gt("count", 0));

When i put my class in the `org.influxdb.querybuilder` package it compiles fine, but when its in my own java package, I get:

    error: close() is not public in SubQuery; cannot be accessed from outside package
                .close()
                ^
    where T is a type-variable:
      T extends WithSubquery declared in class SubQuery

Or from my scala script:

    method close in class SubQuery cannot be accessed in org.influxdb.querybuilder.SelectSubQueryImpl[org.influxdb.querybuilder.SelectQueryImpl]

This is all java 1.8 and scala 2.12

**Comment by majst01** [comment]
seems legit, so you mind raising a PR with a test ?

**Comment by kaszperro** [comment]
any progess on this?
