### ISSUE TITLE
okhttp library not stopping dummy threads

### ISSUE THREAD

**Issue by chabapok** [influxdata/influxdb-java#648]
As far as I understand, okhttp library is library with some critical bugs.

For example, next code produces 93 threads.
```
    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 100; i++) {
            InfluxDB influxDB = InfluxDBFactory.connect("http://127.0.0.1:8086", "root", "root");

            Query query = new Query("select * from can limit 30", "mydb");
            var queryResult = influxDB.query(query);

            System.out.println(queryResult);

            influxDB.close();
            Thread.sleep(300);
        }
        System.out.println(Thread.activeCount());

        Thread.sleep(2000);
        System.out.println(Thread.activeCount());
    }
```

This is not a bug of `influxdb-java`. This is because shutdown procedure in okhttp library
does not work well:

```
//according to the okhttp documentation:
client.dispatcher().executorService().shutdown();
```

Creates a _NEW_ Thread pool (instead of use old) and shutdown them.
As far as I debug, the `executorService()` method is called only at the time of 
`close()`, but threads are created somewhere else.

So, closing InfluxDB is undesirable.

There is a workaround to use InfluxDB. Just use you own permanent ConnectionPool for all InfluxDB instnces:

```
ConnectionPool pool = new ConnectionPool();
OkHttpClient.Builder builder = new OkHttpClient.Builder().connectionPool(pool);
...
InfluxDB influxDB = InfluxDBFactory.connect("http://127.0.0.1:8086", "root", "root", builder);
```

This will help not to produce thousands of threads. But closing at least one instacne of `InfluxDB`  will break everything.

**Comment by majst01** [comment]
Have you tried this with the most recent version of okhttp (4.3.0) ?

**Comment by chabapok** [comment]
I tried starting with the new version just now. There is no bug with the `4.3.0`. 
It seems to me that with the latest version this works better. But I have no tests to check all features with latest okhttp version.

**Comment by majst01** [comment]
since yesterday influxdb-java depends and is tested against okhttp-4.3.0

**Comment by fmachado** [comment]
@chabapok I could not find the mentioned issue or any open leak issue reported to the `okttp` team and I'm skeptic that could have one such as the mentioned here.

@chabapok could you please link it here if you have reported to them?

**Comment by chabapok** [comment]
@fmachado i could not find the okhttp bugtracker.

**Comment by fmachado** [comment]
@chabapok if you found an issue with `okhttp`, please report it there so they can fix it: https://github.com/square/okhttp/issues .

I'm closing this issue here.
