### ISSUE TITLE
Builtquery.QueryBuilderd.limit(limit，offset)

### ISSUE THREAD

**Issue by wimmerX** [influxdata/influxdb-java#652]
The “offset ” variable of Builtquery.QueryBuilderd.limit(limit，offset)  cannot be zero, so how to query the first page that offset is zero？

**Comment by russorat** [comment]
@wimmerX you should be able to omit the offset completely based on this code:
https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/querybuilder/WhereCoreImpl.java#L82
