### ISSUE TITLE
Unable to get the authentication status of an InfluxDB object

### ISSUE THREAD

**Issue by eden-mar-kymera** [influxdata/influxdb-java#655]
Is there any way to access the authentication status of an InfluxDB object? I've intentionally provided bad credentials when using InfluxDBFactory, but I don't see any errors during instantiation. The only time I've seen errors is when I try to run queries against the returned object, but I'd like some way of confirming the connection is valid before sending data. 

I've tried using the InfluxDB.ping() method as well, but it doesn't require authentication, just a valid URL.

**Comment by majst01** [comment]
What about doing a simple Query before going on ?

**Comment by eden-mar-kymera** [comment]
Is that the preferred method? I know running a simple Query to check authentication was something I had explored, but I wasn't sure if that was the best way, or if I was missing a method in the API.

**Comment by majst01** [comment]
Influxdb does not come with a authenticated Ping, so the only solution would be to execute a query which requires authentication, if this are your concerns.

**Comment by eden-mar-kymera** [comment]
I see. Thanks for getting back to me, I'll follow your suggestion and run a simple query then.
