### ISSUE TITLE
Writing Duplicate Entry if its a same timestamp with Sync Logic

### ISSUE THREAD

**Issue by josephthanaraja** [influxdata/influxdb-java#659]
We use to get two different Events at the same time. So in that case one event object is overwriting the other event object and seeing two duplicate entries instead of two different object data. We are using 2.15 influxdb-java version. Will it support this scenario (one think I am not using Serializable for the measurement table). Please suggest
![image](https://user-images.githubusercontent.com/52676992/75842143-94727880-5d9d-11ea-9cbf-814bf026aae8.png)

**Comment by majst01** [comment]
This is nothing influxdb-java can do about, because this is a core design principle of the influxdb database. Points with same timestamp are considered as one.

**Comment by josephthanaraja** [comment]
Understand the InfluxDB time series concept, but I am seeing the POJO Object updated before inserting into InfluxDB using the influxDb-APi. Please refer the image which I am printing the logs before DB update (another POJO updated with another - Seeing duplicate POJO object instead of two different POJO data).

**Comment by majst01** [comment]
The image is very hard to read, and there is no real benefit of making screen shots of log entries. Maybe you can put the relevant log lines into this issue in a `code-block` and everyone can more easily read the point.
