### ISSUE TITLE
Problem: Integrating InfluxDB with android.

### ISSUE THREAD

**Issue by shobhit14gupta** [influxdata/influxdb-java#660]
Hello !!
As I am developing an application on Android using Java (Java1.8). I would like to connect to InfluxDB on a remote server. Refer from InfluxAPI documentation, I am using  influxdb-java library and  using android min api level 22.
The problem is while connecting to the InfluxData server, it crashes and show errors:
> 
> I/art: Rejecting re-init on previously-failed class java.lang.Class<org.influxdb.impl.-$$Lambda$InfluxDBImpl$fFpZuhSxlxar1tU5_rdnRDDDF2k>
>     Rejecting re-init on previously-failed class java.lang.Class<org.influxdb.impl.-$$Lambda$InfluxDBImpl$fFpZuhSxlxar1tU5_rdnRDDDF2k>

> Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.concurrent.atomic.LongAdder" on path: DexPathList[[zip file "/data/app/com.ohs_engineering.smartsenscloud-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

>  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

Kindly help!! Moreover, Is it possible to integrate InfluxDB into android or is there any other way? Kindly let me know.

**Comment by russorat** [comment]
@shobhit14gupta looks like the LongAdder class is only available in api level 24 or higher. https://developer.android.com/reference/java/util/concurrent/atomic/LongAdder

Could you update the api level and try again?
