### ISSUE TITLE
How to use QueryBuilder to construct Function eg.. the  Last() of Selector?😃

### ISSUE THREAD

**Issue by wimmerX** [influxdata/influxdb-java#663]
How to use QueryBuilder to construct Function eg.. the  Last() of Selector?😃

**Comment by russorat** [comment]
@wimmerX thank you for the question. Here is an example of using aggregates in the query builder: https://github.com/influxdata/influxdb-java/blob/master/QUERY_BUILDER.md#the-group-by-clause

**Comment by wimmerX** [comment]
Thank your reply，🤓。
Actually,I want to Implement this clause：
 
> SELECT LAST("pressure") FROM "Weather"  WHERE “wind_direction_degree” = 200；

I write the  following java clause with v2.17
`Query query=select().function("last","pressure").from(influxDBConnector.getDatabase(),"Weather").where(eq("wind_direction_degree",200));`

Is this right? It seems to have failed in  DEBUG.🤕 .@russorat

**Comment by wimmerX** [comment]
After reading the source code, I came up with a solution to the problem.Excellent!😄 I got it，solved the problem.Thank you all the same.🤠

**Comment by russorat** [comment]
@wimmerX thanks! what was your solution in case someone else has the same problem?

**Comment by wimmerX** [comment]
The `function()`takes two parameters. The first is the function name conforming to  Influx syntax , the second parameter is a indefinite length arrays, of which parameters data can be used as the first parameter.In addition, 😕**_Note_**❗❗❗  the " * " is used by a string type or text type, this issue can be resolved with `raw() `of `select()` fuction.

For example, I want to achieve

`SELECT LAST("code"),*  FROM influxdb.autogen.weather WHERE "id" = id` ,in which `weather` is measurement name,`code` is field name,by the following clause:
```
Query queryByIDWeather = select().raw("*").function("LAST", "code")
				.from(influxDBConnector.getDatabase(), "weather")
				.where(eq("id", id));
```

In this way, other and so on.If it's still not very clear, I think take a look at the source code should be able to solve.🤓🤓

**Comment by majst01** [comment]
@wimmerX do you mind writing a section of this into the https://github.com/influxdata/influxdb-java/blob/master/QUERY_BUILDER.md ? I would love to review a PR.

**Comment by wimmerX** [comment]
@majst01   It was a real pleasure for me to do it.Recently I've been contacting with the influxDB in the IoT area, java API of it  feels good👍, thank you for your contribution.It's an honor, I can give you a difference.
