### ISSUE TITLE
Obtaining JSON string from QueryResult

### ISSUE THREAD

**Issue by jfmonteil** [influxdata/influxdb-java#666]
Hi guys,
I apologize this is a beginer question.
I am performing various queries with the java API.
I
`influxDB.setDatabase(environmentSubstitute(meta.getDatabase()));
 QueryResult response = influxDB.query(new Query(query));`

What I would like to do is to get a JSON string to return (to my users)

If I do the following, I have an array retuned to me

`JSONArray ja=(JSONArray)response.getResults();
String str=ja.toString()`

I recieve this for instance
`Reponse
QueryResult [results=[Result [series=[Series [name=average_temperature, tags=null, columns=[tagKey], values=[[location]]], Series [name=cpu, tags=null, columns=[tagKey], values=[[host], [region]]], Series [name=h2o_feet, tags=null, columns=[tagKey], values=[[location]]], Series [name=h2o_pH, tags=null, columns=[tagKey], values=[[location]]], Series [name=h2o_quality, tags=null, columns=[tagKey], values=[[location], [randtag]]], Series [name=h2o_temperature, tags=null, columns=[tagKey], values=[[location]]]], error=null]], error=null]
`
What I would like is real JSON, do you know how to do that ?
I set `ResponseFormat.JSON` when I create the InfluxDB connection.

Cheers,

**Comment by majst01** [comment]
Hi @jfmonteil 

response is the result in a QueryResult Object, you can use any java based object to json serializer library you want to create json output.

https://github.com/FasterXML/jackson is one of those.

**Comment by jfmonteil** [comment]
Thank you,
If you have an example I take (I know, I am lazy ;))
Cheers,
