### ISSUE TITLE
Fix for #267 breaks binary compatibility

### ISSUE THREAD

**Issue by jjathman** [influxdata/influxdb-java#677]
I believe the fix for #267 breaks binary compatibility for classes which were previously compiled. We have an internal library that wraps calls to the `influxdb-java` library. For consuming applications of our library that try to upgrade to `2.18` they are experiencing an exception. The move from `long` primitive to `Long` the object in the method definition seems to break the code. With the latest release we are getting this error with our code at runtime.

```
'org.influxdb.dto.Point$Builder org.influxdb.dto.Point$Builder.time(long, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'org.influxdb.dto.Point$Builder org.influxdb.dto.Point$Builder.time(long, java.util.concurrent.TimeUnit)'
```

This is using Java 11, but I don't think that makes a difference. Could we put the API back to what it was before with `long` as a primitive?

**Comment by majst01** [comment]
I don't think we can keep binary compatibility between releases if a fix for BUG requires this.

**Comment by jjathman** [comment]
Not sure I understand that justification. Leaving the existing method and adding the new methods would have allowed for fixing the bug and keeping backwards compatibility right? The change from a primitive long to Long object seemed unrelated to the bug report.

**Comment by J0s3f** [comment]
I actually planned to keep binary compatibility but used Long instead of long by mistake.
This should fix it, I think?

**Comment by jjathman** [comment]
@J0s3f at this point I think you would need to add back the old one but leave the new one. Otherwise it would just break binary compatibility all over again.

**Comment by majst01** [comment]
I am unsure howto proceed here

**Comment by jjathman** [comment]
I think if you are able to have both a `Long` and `long` version of the API at the same time, I would use that and release a new version. That way people using either version will be OK from a binary perspective. If that's not possible then I think you can just leave it the way it is. Most consumers of this library probably directly compile against it, so the change would not have a visible impact. Our company has a thin wrapper library we have written around the Influx library which is why we were more susceptible to this binary change. 

If this change was accidental that's fine, bugs happen. I would not revert the change again since it would cause another breaking change. I posted this issue originally because I thought the change was made intentionally.

**Comment by nicholashagen-hagen** [comment]
I just ran into this problem as well since one of our libraries has its source compiled against 2.9 which has `time(long, TimeUnit)`, but the app was bringing in our library plus influx-db 2.18 where the signatures changed.

I agree that ideally just have all 3 signatures, tho not sure of all the nuances of that.  Autoboxing should be fine since Java only autoboxes if it does not find an exact match.  The `Number` signature may mess with that, but I think in general it's still fine.  If it does not work for any reason, I also agree, just keep it broken and force other libs to recompile against the new version.

**Comment by J0s3f** [comment]
It is possible to add both the primitive `long` and `Long` method into the class.
Can anyone test that and confirm it works with old and new projects?
