### ISSUE TITLE
批量写入

### ISSUE THREAD

**Issue by Edgar-cn** [influxdata/influxdb-java#678]
能不能给一个java批量写入的例子，我总是无法批量写入。
for (int i = 0; i< 10000; i++){
            Thread.sleep(10);

            Point point = Point.measurement("cpu22")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .addField("num",1)
                    .tag("pkg",i+"")
                    .tag("statusCode","statusCode")
                    .build();
            batchPoints.point(point);
        }
        influxDB.write(batchPoints);
我的influxdb版本为1.8，执行成功但是就是写入不了数据，数据库名和measurement名称都没有任何问题。

**Comment by majst01** [comment]
我不会看中文

**Comment by majst01** [comment]
请使用influxdb-java 2.19版

**Comment by Edgar-cn** [comment]
I am so sorry

**Comment by Edgar-cn** [comment]
I am so sorry
