### ISSUE TITLE
The problem of synchronous writing

### ISSUE THREAD

**Issue by Edgar-cn** [influxdata/influxdb-java#679]
When using the BatchPoints class，My data is only saved to influxdb the first time it is executed.
My code：
```
BatchPoints batchPoints = BatchPoints
                .database(dbName)
                .tag("async", "true")
                .retentionPolicy(rpName)
                .consistency(ConsistencyLevel.ALL)
                .build();
Point point1 = Point.measurement("cpu")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .addField("idle", 90L)
                    .addField("user", 9L)
                    .addField("system", 1L)
                    .build();
Point point2 = Point.measurement("disk")
                    .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                    .addField("used", 80L)
                    .addField("free", 1L)
                    .build();
batchPoints.point(point1);
batchPoints.point(point2);
influxDB.write(batchPoints);
```
After I executed my code for the first time,no problem.But,I execute ‘’drop measurement cup‘’
The second time I execute my code,I found that I don't have any data in my influxdb.
And I tried to change measurement but couldn't find the data the first time
Other environment：
 <dependency>
            <groupId>org.influxdb</groupId>
            <artifactId>influxdb-java</artifactId>
            <version>2.19</version>
        </dependency>

influxdb1.8

**Comment by Edgar-cn** [comment]
status code：204

**Comment by majst01** [comment]
what ist your batch configuration, number of points, time

**Comment by Edgar-cn** [comment]
influxDB.enableBatch(BatchOptions.DEFAULTS);
I don't think it has much to do with this setting
What I need is to insert immediately
change：
influxDB.enableBatch(1,10,TimeUnit.MILLISECONDS);
The result is the same

**Comment by majst01** [comment]
If the timestamp of two or more points do not differ, only one point is written
