### ISSUE TITLE
There is a thread safety issue with InfluxDBResultMapper

### ISSUE THREAD

**Issue by mayuefeng777** [influxdata/influxdb-java#683]
When I run the `toPOJO` method from the `InfluxDBResultMapper` in a multithreaded environment, some fields of the objects returned are null in some special cases.

Then I debugged and figured out that there is some problem in the `cacheMeasurementClass` method. When the first thread puts the measurement class into the cache map `CLASS_FIELD_CACHE` and before it finish putting all the field of the measurement class  into cache, other threads would get an incomplete cache object. 

I think it‘s better to make it synchronized or move the step of putting the measurement class into the cache map to the end, at least after all the field of the measurement class cached.

**Comment by russorat** [comment]
@mayuefeng777 thanks for the report. Are you interested in opening a PR?
