### ISSUE TITLE
Wrong statement in the doc.

### ISSUE THREAD

**Issue by arjenzhou** [influxdata/influxdb-java#694]
There is a wrong statement in https://github.com/influxdata/influxdb-java/blob/master/MANUAL.md#setting-a-default-database-optional,

`QueryResult queryResult = influxDB.query(new Query("SELECT * FROM h2o_feet"), databaseName);`

which should be 

`QueryResult queryResult = influxDB.query(new Query("SELECT * FROM h2o_feet", databaseName));`

in practise.

I'd like to fix it if I am right.

**Comment by sranka** [comment]
Yes, you are, pull requests are always welcome.

**Comment by majst01** [comment]
Yes please open a PR

**Comment by majst01** [comment]
merged, thanks
