### ISSUE TITLE
Issue on inserting additional fields in measurement

### ISSUE THREAD

**Issue by AdhithanD** [influxdata/influxdb-java#705]
We have an existing measurement with data and trying to insert data with new fields using java client  to store data as Batch Points.
But the attached exception is thrown.
![image](https://user-images.githubusercontent.com/67193121/97826220-f653fb00-1cfb-11eb-8d3a-9c72810c9399.png)

**Comment by majst01** [comment]
can you show me the actual code where you try to write your points

**Comment by AdhithanD** [comment]
Hi Masjst01,

try {
        influxDB.write(batchPoints);
        influxDB.close();
      } catch (InfluxDBException e) {
}

Also we haven't enabled batch processing in our code, so it should take default one.

**Comment by majst01** [comment]
2 more questions:
- version of influxdb-java and java version
- your code which creates the influxDB Instance

**Comment by AdhithanD** [comment]
Hi,

influxdb-java-2.7
java - 1.8
InfluuxDB Version - 1.3.8

InfluxDB influxDB;
    try {
      influxDB = InfluxDBFactory.connect(influxURL, influxUsername, influxPassword);
}

**Comment by majst01** [comment]
OK, thanks

can you please try with the most recent influxdb-java version 2.20  and report back if the issue still persist.

**Comment by AdhithanD** [comment]
Thanks and we will check, but it is working in a instance of influx cluster. My doubt is, are there any configuration(such as permission for altering table, enable batch processing) which related to particular error?

**Comment by AdhithanD** [comment]
Hi majst01,
Also I tried influxdb-java version 2.20, but same issue exist.

**Comment by majst01** [comment]
No this Message can only be raised if somewhere in your code `influxDB.enableBatch` is called a second time.
Are you sure you create the influxDB instance only once ?

**Comment by AdhithanD** [comment]
I am sure,  never used influxDB.enableBatch.
are there any way to enable directly in DB config?

**Comment by majst01** [comment]
This is not possible there are two places in the whole code:
https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L302
https://github.com/influxdata/influxdb-java/blob/master/src/main/java/org/influxdb/impl/InfluxDBImpl.java#L357

If you will show the whole stacktrace, from the most recent influxdb-java version we will see exactly where it comes from.

**Comment by AdhithanD** [comment]
Hi majst01,
Thanks for your support,  Actual logic is to call one function when exception happen and that function enabling the batch mode.
Also I forgot to disable batch mode in the exception block.  Closing the issue.
