### ISSUE TITLE
java.lang.RuntimeException: retention policy not found

### ISSUE THREAD

**Issue by cuthbe** [influxdata/influxdb-java#74]
When writing using the following I get

java.lang.RuntimeException: retention policy not found

Point point2 = Point.measurement("TICK")
                .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
                .field(value1, 1000000)
                .field(value3, 1.23232)
                .field(value4, 1.23232)
                .field(value5, 1.2)
                .field(value6, 1.23231)
                .build();

**Comment by caoli5288** [comment]
Please paste full stack trace.

**Comment by cuthbe** [comment]
I found if I changed the code to

		BatchPoints batchPoints = BatchPoints.database(REMOTE_INFLUXDB_DATABASE).retentionPolicy("year").build();
		
		long currentTimeMillis = System.currentTimeMillis();
		DateTime asUtc = CelerDateUtil.asUtc(currentTimeMillis);

		System.out.println("Data = "+asUtc);
		Point point2 = Point.measurement("TICK")
.time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
.field(value1, 1000000)
.field(value3, 1.23232)
.field(value4, 1.23232)
.field(value5, 1.2)
.field(value6, 1.23231)
.build();
		
		batchPoints.point(point2);
		
		System.out.println("batch = "+batchPoints);
		
		this.influxDBDestination.publishMessage(batchPoints);

This worked. But no values got written for some strange reason. More testing to be had I think.

**Comment by majst01** [comment]
Hi,

any news on this, otherwise i will close this issue.
