### ISSUE TITLE
On the problem that influxdb has no permission to delete data

### ISSUE THREAD

**Issue by frakes-zheng** [influxdata/influxdb-java#753]
Steps to reproduce:
1、String url = urlMaster+"/api/v2/delete";
2、HttpUtil http = new HttpUtil();
3、String post = http.post(url, paramMap);
Expected behavior:
delete success!!!
Actual behavior：
{"code":"unauthorized","message":"unauthorized access"}
Specifications:
Client Version:2.0
InfluxDB Version：2.0.3
Platform: IntelliJ IDEA

**Comment by majst01** [comment]
This repo is responsible for the java client to connect to influxdb. Please open  authentication related  issues in the influxdb repository.
