### ISSUE TITLE
The same SQL,sometimes is ok, but sometime can not get res.

### ISSUE THREAD

**Issue by yangh0597** [influxdata/influxdb-java#827]
we use the same sql(use java client ),sometime can get the right data, bus sometime can not. In the stress test, the parameters are the same for each call

![image](https://user-images.githubusercontent.com/86940083/162663709-2db60704-ea40-46d8-935a-35a4e96318eb.png)

error:
![image](https://user-images.githubusercontent.com/86940083/162663865-48e534a4-635e-4267-abaa-3b93fe88efd2.png)

code
![image](https://user-images.githubusercontent.com/86940083/162663993-c3fdd4e6-340b-47e2-920a-6cebd3280a48.png)

need some help,thanks

**Comment by majst01** [comment]
Would you please try to update to the most recent version of influxdb-java (v2.22)

**Comment by yangh0597** [comment]
It is not an influxdb problem because I use the same dateformat on multiple threads. thanks

**Comment by yangh0597** [comment]
done thanks
