### ISSUE TITLE
Identify repo owner and move to InfluxCommunity org

### ISSUE THREAD

**Issue by mhall119** [influxdata/influxdb-java#846]
The v1 client libraries for InfluxDB were typically developed and maintained by community members. They have all now been succeeded by v2 client libraries developed and maintained by InfluxData in partnership with Bonitoo.

If there are still users of this v1 client library, and they or somebody else are willing to keep them updated with security fixes at a minimum, this code should be moved to https://github.com/InfluxCommunity and control of it given to the new maintainers. Otherwise let's archive it in favor of the v2 client library.

**Comment by majst01** [comment]
I am the creator and maintainer of this project, i am sure there are still 1000s of users out there, there is no reason to move this project to a new location. I guess this request is for the sole purpose of making the newer library more prominent.

**Comment by mhall119** [comment]
@majst01 we opened a new org (InfluxCommunity) for hosting projects related to InfluxDB that aren't owned by InfluxData. Moving it there would allow us to give you more control over it and not require things like signing the InfluxData CLA in order for people to contribute to it. 

The only requirement for using this new org though is that projects be actively maintained (I didn't want it to be a place for things to be abandoned), which is why this issue is about identifying which of our v1 clients still have or need a maintainer.

**Comment by mhall119** [comment]
If it's okay with you, I'd like to move this code over to InfluxCommunity and make you the owner of the repo there.

**Comment by majst01** [comment]
@mhall119 why forcing all users to search again for this library, what is the burden for your company to keep it as it is, i dont get it.

**Comment by mhall119** [comment]
@majst01 no forcing, if you don't want this repo moved to the InfluxCommunity organization it can stay where it is. The intention is solely to provide the best home for these projects that we can.

**Comment by BrentonPoke** [comment]
Is this library even still being worked on? I had 2 PRs open 2 years ago that never got looked at/merged.

**Comment by majst01** [comment]
It is basically in maintenance mode.

**Comment by BrentonPoke** [comment]
Would it be possible to merge our PRs in at least? I was really hoping they could be my first accepted PRs.

**Comment by jdstrand** [comment]
Based on comments from @majst01, closing and not moving to the InfluxCommunity org. Thanks @majst01 for maintaining this!

I believe that when transferring ownership, GitHub puts redirects in place so old URLs and git fetches continue to work with the old org, so if you want to reconsider moving this to InfluxCommunity at some point, feel free to reach out.
