### ISSUE TITLE
Where can i download a compiled .jar file?

### ISSUE THREAD

**Issue by jayjupdhig** [influxdata/influxdb-java#853]
Where can i download a compiled .jar file?

Can't see something like that in the "Release" section. Why?

**Comment by jayjupdhig** [comment]
where to post my issue here: https://github.com/influxdata/influxdb-client-java/issues/375

oh HERE?

**Comment by bednar** [comment]
Hi @jayjupdhig,

you can download the jars from Maven repository:

https://mvnrepository.com/artifact/org.influxdb/influxdb-java/2.23

Regards

**Comment by jayjupdhig** [comment]
ok thx :-)

**Comment by jayjupdhig** [comment]
closed
