### ISSUE TITLE
Is the database connection pool available?

### ISSUE THREAD

**Issue by ZhenChen008** [influxdata/influxdb-java#889]
Is version 1.8 of this project now integrated with database connection pooling?
If so, please show a description or link ,THX!

**Comment by majst01** [comment]
Latest version is 2.23 and does not have a connection pool and will never have.

What is your actual problem ?

**Comment by ZhenChen008** [comment]
Thank you for reply, I just feel confused that if there is no connection pool,
 it will take time to get the connection and close it, especially when getting many connections in a short time.  Is there anything wrong with that?

**Comment by majst01** [comment]
Communication protocol is http(s) so no extra overhead here.
