### ISSUE TITLE
Not specficing a TimeUnit when intializing a BatchPoint creates an NPE on Influx.write()

### ISSUE THREAD

**Issue by royalaid** [influxdata/influxdb-java#91]
As of commit cb0ba0b when using BatchPoints if you do not specify a time when the BatchPoint is initialized later calling write with that BatchPoint will cause an NPE because the BatchPoint object does not have a given precision.

**Comment by lukewhiting** [comment]
Looking over the code there's a real problem with the whole concept of BatchPoint and it's handling of time precision. As each point is able to set this independently I don't think it should be a property of the batch at all.

Currently this is preventing 2.0 being usable in automatic batch mode as it NPEs every time it tries to send the current BatchProcessor cache contents.

**Comment by lukewhiting** [comment]
@majst01 What was the resolution of this issue?

**Comment by majst01** [comment]
Without TimeUnit there need to be a Exception thrown because its not clear howto proceed

**Comment by lukewhiting** [comment]
The point is that the time unit is specified on the batch. Why does it then need to be specified again on each batch point? Should it not default to the one on the batch?

**Comment by lukewhiting** [comment]
I seem to remember the original problem was in auto batch mode it's not possible to set the time unit? I must admit we abandoned this library due to this issue so it's been a while since I worked with it but given the number of bug reports i'm guessing it's still an issue.

**Comment by majst01** [comment]
Im happy to fix it when you can show me an appropriate reproducer
